force-app/main/default/objects/sbaa__Approval__c/fields/sbaa__Status__c.field-meta.xml
<CustomField>
    <fullName>sbaa__Status__c</fullName>
    <description>Status of this approval.</description>
    <inlineHelpText>Status of this approval.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
                <default>true</default>
                <label>Assigned</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Revoked</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Pending Approvals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Approved.recordType-meta.xml
<RecordType>
    <fullName>Approved</fullName>
    <active>true</active>
    <description>Coincides with the Approved SBQQ Status</description>
    <label>Approved</label>
</RecordType>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Pending_Approval.recordType-meta.xml
<RecordType>
    <fullName>Pending_Approval</fullName>
    <active>true</active>
    <description>Coincides with the Pending Approvals SBQQ Status</description>
    <label>Pending Approval</label>
</RecordType>

force-app/main/default/classes/ApprovalTriggerHelper.cls
public class ApprovalTriggerHelper {
    
    public static void updateQuoteStatus(Map<Id,sbaa__Approval__c> oldApprovalRecMap, List<sbaa__Approval__c> newApprovalList){
        
        /* Service Ticket # 200212 , ROHINI HATHI 
        Moved the code in Process builder: if Approval status is changed then update Q status and recordtype and opportunity stage
        Following code does not set values properly when iterating in loop, except for initial approval statuses of Approve or Reject
        It only considers two approval statuses out of four

        Map<Id,SBQQ__Quote__c> updateAllapprovedQuoteMap = new Map<Id,SBQQ__Quote__c>();
        Map<Id,SBQQ__Quote__c> updateAllrejectedQuoteMap = new Map<Id,SBQQ__Quote__c>();
        Map<Id,Id> quoteApprovalMap = new Map<Id,Id>();
        Id approvedRecId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('Approved').getRecordTypeId();
        Id pendingApprovaldRecTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByDeveloperName().get('Pending_Approval').getRecordTypeId();        
                
        for(sbaa__Approval__c approvalsObj : newApprovalList){
            
            quoteApprovalMap.put(approvalsObj.Id,approvalsObj.Quote__c);
        }
        
        if(NULL != quoteApprovalMap && quoteApprovalMap.size() > 0 ){
            Integer counter = 0;
            Integer approvedCounter = 0;
            Integer rejectedCounter = 0;
            for(SBQQ__Quote__c quoteRec : [SELECT Id, (SELECT id, sbaa__Status__c from Approvals__r) FROM SBQQ__Quote__c WHERE ID IN:quoteApprovalMap.values()]){
                
                for(sbaa__Approval__c singleApproval : quoteRec.Approvals__r){
                    counter = counter+1;
                    if(singleApproval.sbaa__Status__c == 'Approved'){
                        approvedCounter = approvedCounter + 1;
                    }else if(singleApproval.sbaa__Status__c == 'Rejected') {
                        rejectedCounter = rejectedCounter +1;
                    }
                    system.debug('counter::'+counter);
                    system.debug('approvedCounter::'+approvedCounter);
                    system.debug('rejectedCounter::'+rejectedCounter);
                    if(approvedCounter == counter){
                        system.debug('inside approvedCounter');
                        updateAllapprovedQuoteMap.put(quoteRec.Id,(new SBQQ__Quote__c(Id= quoteRec.Id, SBQQ__Status__c ='Approved',RecordTypeId= approvedRecId)));
                    }
                    
                    if(rejectedCounter == counter){
                        system.debug('inside rejectedCounter');
                        updateAllrejectedQuoteMap.put(quoteRec.Id,(new SBQQ__Quote__c(Id= quoteRec.Id, SBQQ__Status__c ='Rejected',RecordTypeId= pendingApprovaldRecTypeId)));
                    }
                }
                
            }
            
            if(NULL != updateAllapprovedQuoteMap && updateAllapprovedQuoteMap.size() > 0){
                system.debug('updateAllapprovedQuoteMap' + updateAllapprovedQuoteMap);
                update updateAllapprovedQuoteMap.values();
            }
            
            if(NULL != updateAllrejectedQuoteMap && updateAllrejectedQuoteMap.size() > 0){
                system.debug('updateAllrejectedQuoteMap'+ updateAllrejectedQuoteMap);
                update updateAllrejectedQuoteMap.values();
            }
        }
    */       
    }
}