force-app/main/default/objects/Flame_Product__c/Flame_Product__c.object-meta.xml
<CustomObject>
    <label>Flame Product</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flame Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flame Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flame_Product__c/fields/Arrester_for_Detonation_or_Deflagration__c.field-meta.xml
<CustomField>
    <fullName>Arrester_for_Detonation_or_Deflagration__c</fullName>
    <label>Detonation or Deflagration?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Detonation</fullName>
            </value>
            <value>
                <fullName>Deflagration</fullName>
            </value>
            <value>
                <fullName>Both</fullName>
                <default>true</default>
                <label>Both</label>
            </value>
            <value>
                <fullName>DEF</fullName>
                <isActive>false</isActive>
                <label>DEF</label>
            </value>
            <value>
                <fullName>DET</fullName>
                <isActive>false</isActive>
                <label>DET</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Body_Material__c.field-meta.xml
<CustomField>
    <fullName>Body_Material__c</fullName>
    <label>Body Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Constrain_Product_Selection_by_Flow__c.field-meta.xml
<CustomField>
    <fullName>Constrain_Product_Selection_by_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filter Product Selection by Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Diaphragm_Material__c.field-meta.xml
<CustomField>
    <fullName>Diaphragm_Material__c</fullName>
    <label>Diaphragm Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Drilling__c.field-meta.xml
<CustomField>
    <fullName>Drilling__c</fullName>
    <label>Drilling</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Element_Material__c.field-meta.xml
<CustomField>
    <fullName>Element_Material__c</fullName>
    <label>Element Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Element_Size__c.field-meta.xml
<CustomField>
    <fullName>Element_Size__c</fullName>
    <label>Element Size Filter (Optional)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/ESZC__c.field-meta.xml
<CustomField>
    <fullName>ESZC__c</fullName>
    <label>ESZC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Final_Assembly_Location_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Final_Assembly_Location_Requirements__c</fullName>
    <label>Final Assembly Location Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>No Restrictions</label>
            </value>
            <value>
                <fullName>US</fullName>
                <label>Perform Final Assembly in USA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Gas_Group__c.field-meta.xml
<CustomField>
    <fullName>Gas_Group__c</fullName>
    <label>Gas Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Methane (MESG ≥ 1.14)</fullName>
            </value>
            <value>
                <fullName>NEC D (MESG &gt; 0.75)</fullName>
            </value>
            <value>
                <fullName>NEC C ( MESG &gt; 0.45 ≤ 0.75)</fullName>
            </value>
            <value>
                <fullName>IEC IIA1 ( MESG ≥ 1.14)</fullName>
            </value>
            <value>
                <fullName>IEC IIA ( MESG &gt; 0.90)</fullName>
            </value>
            <value>
                <fullName>IEC IIB3 ( MESG ≥ 0.65)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Housing_Material__c.field-meta.xml
<CustomField>
    <fullName>Housing_Material__c</fullName>
    <label>Housing Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Inlet_Option_A__c.field-meta.xml
<CustomField>
    <fullName>Inlet_Option_A__c</fullName>
    <label>Inlet Option A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Inlet_Option_B__c.field-meta.xml
<CustomField>
    <fullName>Inlet_Option_B__c</fullName>
    <label>Inlet Option B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Inlet_Option_C__c.field-meta.xml
<CustomField>
    <fullName>Inlet_Option_C__c</fullName>
    <label>Inlet Option C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Liquid_Dye_Penetrant__c.field-meta.xml
<CustomField>
    <fullName>Liquid_Dye_Penetrant__c</fullName>
    <label>Liquid Dye Penetrant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Material_Sourcing_Requirements__c.field-meta.xml
<CustomField>
    <fullName>Material_Sourcing_Requirements__c</fullName>
    <label>Material Sourcing Requirements</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>00</fullName>
                <default>true</default>
                <label>No Restrictions</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Yes, Details Attached to Quote</label>
            </value>
            <value>
                <fullName>0N</fullName>
                <isActive>false</isActive>
                <label>No Materials from India or China</label>
            </value>
            <value>
                <fullName>US</fullName>
                <isActive>false</isActive>
                <label>Source all Materials from USA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Mounting__c.field-meta.xml
<CustomField>
    <fullName>Mounting__c</fullName>
    <label>Mounting</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In-Line Straight Pipe</fullName>
            </value>
            <value>
                <fullName>In-Line Pipe with Bend</fullName>
            </value>
            <value>
                <fullName>End-of-Line</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Outlet_Option_A__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Option_A__c</fullName>
    <label>Outlet Option A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Outlet_Option_B__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Option_B__c</fullName>
    <label>Outlet Option B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Outlet_Option_C__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Option_C__c</fullName>
    <label>Outlet Option C</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Painting_Coating_Option__c.field-meta.xml
<CustomField>
    <fullName>Painting_Coating_Option__c</fullName>
    <label>Painting/Coating Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Pallet_Material__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Material__c</fullName>
    <label>Pallet Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Positive_Material_Identification__c.field-meta.xml
<CustomField>
    <fullName>Positive_Material_Identification__c</fullName>
    <label>Positive Material Identification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Pressure_Setting__c.field-meta.xml
<CustomField>
    <fullName>Pressure_Setting__c</fullName>
    <label>Pressure Setting</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/PTC__c.field-meta.xml
<CustomField>
    <fullName>PTC__c</fullName>
    <label>PTC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Flame Products</relationshipLabel>
    <relationshipName>Flame_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Radiography__c.field-meta.xml
<CustomField>
    <fullName>Radiography__c</fullName>
    <label>Radiography</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Spring_Range__c.field-meta.xml
<CustomField>
    <fullName>Spring_Range__c</fullName>
    <label>Spring Range</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/SZC__c.field-meta.xml
<CustomField>
    <fullName>SZC__c</fullName>
    <label>SZC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Body_Material__c.field-meta.xml
<CustomField>
    <fullName>Body_Material__c</fullName>
    <label>Body Material</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Pressure_Setting__c.field-meta.xml
<CustomField>
    <fullName>Pressure_Setting__c</fullName>
    <label>Pressure Setting</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfigFlameProductReferenceCtrlTest.cls
@isTest
public class ConfigFlameProductReferenceCtrlTest {
    
    @isTest
    public static configureFLAMEproduct getconfigFACntrl() {

        Test.startTest();
        
        Map<String, String> mapWithFAValues = new Map<String, String>();
        mapWithFAValues.put('BRAND','Groth');
        mapWithFAValues.put('PRODUCT_CODE','FlameProducts');
        mapWithFAValues.put('PRODUCT_NAME','FlameProducts');
        
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithFAValues);
        
        TestDataFAUtility.quoteLine = quoteLine;
        TestDataFAUtility.mapWithFAValues = mapWithFAValues;
        
        system.debug('TestDataFAUtility.quoteLine:'+TestDataFAUtility.quoteLine);
        system.debug('TestDataFAUtility.mapWithFAValues:'+TestDataFAUtility.mapWithFAValues);
        TestDataFAUtility.createFATestRecords2();
        TestDataFAUtility.createFAMasterTestRecords2();
        
        PageReference pager = Page.ConfigFLAME;
        Test.setCurrentPage(pager);
        
        ApexPages.currentPage().getParameters().put('qid', String.valueOf(quoteLine.Id));
        
        Flame_Product__c conFA = [SELECT Id,Quote_Line__c,Drilling__c,Body_Material__c,Housing_Material__c,Element_Material__c,Pallet_Material__c,
            Diaphragm_Material__c,Pressure_Setting__c,Spring_Range__c,Painting_Coating_Option__c,Inlet_Option_A__c,Inlet_Option_B__c,
            Inlet_Option_C__c,Outlet_Option_A__c,Outlet_Option_B__c,Outlet_Option_C__c,Radiography__c,Liquid_Dye_Penetrant__c,
            Positive_Material_Identification__c,Final_Assembly_Location_Requirements__c,Material_Sourcing_Requirements__c,PTC__c,
            Constrain_Product_Selection_by_Flow__c,Mounting__c,Arrester_for_Detonation_or_Deflagration__c,Gas_Group__c,SZC__c,ESZC__c,Element_Size__c,Size__c FROM Flame_Product__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(conFA);
        
        ConfigFlameProductReferenceCtrl conFlame=new ConfigFlameProductReferenceCtrl(sc);
        
        
        boolean Radiography;
        Radiography=conFlame.Radiography;
        conFlame.getUserTimeZone();
        conFlame.Radiography=true;
        string str='';
        str=conFlame.GPAINT;
        str=conFlame.HCLASS;
        str=conFlame.InletA;
        str=conFlame.InletB;
        str=conFlame.InletC;
        str=conFlame.LDP;
        str=conFlame.MATLSOURCE;
        str=conFlame.MCBODY;
        str=conFlame.MCDPHM;
        str=conFlame.MCELMT;
        str=conFlame.MCHOUS;
        str=conFlame.MCPALL;
        str=conFlame.PMI;
    //    str=conFlame.ReqdGasGroupLevel;
        str=conFlame.SETTING;
        str=conFlame.SPRING;
        str=conFlame.SZC;
        str=conFlame.ESZC;
        str=conFlame.XRAY;
        str=conFlame.OutletA;
        str=conFlame.OutletB;
        str=conFlame.OutletC;
        str=conFlame.ASSYLOCATION;
        conFlame.GPAINT='test';
        conFlame.HCLASS='test';
        conFlame.InletA='test';
        conFlame.InletB='test';
        conFlame.InletC='test';
        conFlame.LDP='test';
        conFlame.MATLSOURCE='test';
        conFlame.MCBODY='test';
        conFlame.MCDPHM='test';
        conFlame.MCELMT='test';
        conFlame.MCHOUS='test';
        conFlame.MCPALL='test';
        conFlame.PMI='test';
        conFlame.ReqdGasGroupLevel='test';
        conFlame.SETTING='test';
        conFlame.SPRING='test';
        conFlame.SZC='test';
        conFlame.ESZC='test';
        conFlame.XRAY='test';
        conFlame.OutletA='test';
        conFlame.OutletB='test';
        conFlame.OutletC='test';
        conFlame.ASSYLOCATION='test';
        
        Test.stopTest();
        
        return new configureFLAMEproduct(sc);
    }
  
    @isTest
    public static configureFLAMEproduct getconfigFACntrl2() {

        Test.startTest();
        
        Map<String, String> mapWithFAValues = new Map<String, String>();
        mapWithFAValues.put('BRAND','Groth');
        mapWithFAValues.put('PRODUCT_CODE','FlameProducts');
        mapWithFAValues.put('PRODUCT_NAME','FlameProducts');
        
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithFAValues);
        
        TestDataFAUtility.quoteLine = quoteLine;
        TestDataFAUtility.mapWithFAValues = mapWithFAValues;
        
        system.debug('TestDataFAUtility.quoteLine:'+TestDataFAUtility.quoteLine);
        system.debug('TestDataFAUtility.mapWithFAValues:'+TestDataFAUtility.mapWithFAValues);
        TestDataFAUtility.createFATestRecords();
        TestDataFAUtility.createFAMasterTestRecords();
        
        PageReference pager = Page.ConfigFLAME;
        Test.setCurrentPage(pager);
        
        ApexPages.currentPage().getParameters().put('qid', String.valueOf(quoteLine.Id));
        
        Flame_Product__c conFA = [SELECT Id,Quote_Line__c,Drilling__c,Body_Material__c,Housing_Material__c,Element_Material__c,Pallet_Material__c,
            Diaphragm_Material__c,Pressure_Setting__c,Spring_Range__c,Painting_Coating_Option__c,Inlet_Option_A__c,Inlet_Option_B__c,
            Inlet_Option_C__c,Outlet_Option_A__c,Outlet_Option_B__c,Outlet_Option_C__c,Radiography__c,Liquid_Dye_Penetrant__c,
            Positive_Material_Identification__c,Final_Assembly_Location_Requirements__c,Material_Sourcing_Requirements__c,PTC__c,
            Constrain_Product_Selection_by_Flow__c,Mounting__c,Arrester_for_Detonation_or_Deflagration__c,Gas_Group__c,SZC__c,ESZC__c,Element_Size__c,Size__c FROM Flame_Product__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(conFA);
        
        ConfigFlameProductReferenceCtrl conFlame=new ConfigFlameProductReferenceCtrl(sc);

        string str='';
       
        str=conFlame.MCDPHM;
        
        str=conFlame.MCPALL;
        str=conFlame.SETTING;
        str=conFlame.SPRING;
        
        Test.stopTest();
        
        return new configureFLAMEproduct(sc);
    }
    
}