force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/Global_Site_Part_Parameters_ISPM__c.object-meta.xml
<CustomObject>
    <label>Global Site Part Parameters (ISPM)</label>
    <nameField>
        <label>Global Site Part Parameters (ISPM)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Site Part Parameters (ISPM)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/InventoryPartTemplate_ID__c.field-meta.xml
<CustomField>
    <fullName>InventoryPartTemplate_ID__c</fullName>
    <label>InventoryPartTemplate_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/InventoryPartType__c.field-meta.xml
<CustomField>
    <fullName>InventoryPartType__c</fullName>
    <label>InventoryPartType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/InventorySite__c.field-meta.xml
<CustomField>
    <fullName>InventorySite__c</fullName>
    <label>InventorySite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/LeadTimeLL__c.field-meta.xml
<CustomField>
    <fullName>LeadTimeLL__c</fullName>
    <label>LeadTimeLL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/MfgSite__c.field-meta.xml
<CustomField>
    <fullName>MfgSite__c</fullName>
    <label>MfgSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/PurchasePartTemplate_ID__c.field-meta.xml
<CustomField>
    <fullName>PurchasePartTemplate_ID__c</fullName>
    <label>PurchasePartTemplate_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/SalesSite__c.field-meta.xml
<CustomField>
    <fullName>SalesSite__c</fullName>
    <label>SalesSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/SERIALTRACKCODE__c.field-meta.xml
<CustomField>
    <fullName>SERIALTRACKCODE__c</fullName>
    <label>SERIALTRACKCODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/Sourcing_Option__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Option__c</fullName>
    <label>Sourcing_Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/Global_Site_Part_Parameters_PPS__c.object-meta.xml
<CustomObject>
    <label>Global Site Part Parameters (PPS)</label>
    <nameField>
        <label>Global Site Part Parameters (PPS)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Site Part Parameters (PPS)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/LeadTimeUL__c.field-meta.xml
<CustomField>
    <fullName>LeadTimeUL__c</fullName>
    <label>LeadTimeUL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/PPS_VendoNo__c.field-meta.xml
<CustomField>
    <fullName>PPS_VendoNo__c</fullName>
    <label>PPS_VendoNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/Primary_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vendor__c</fullName>
    <label>Primary_Vendor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/PurchaseSite__c.field-meta.xml
<CustomField>
    <fullName>PurchaseSite__c</fullName>
    <label>PurchaseSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/SITE__c.field-meta.xml
<CustomField>
    <fullName>SITE__c</fullName>
    <label>SITE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/VendorLTLL__c.field-meta.xml
<CustomField>
    <fullName>VendorLTLL__c</fullName>
    <label>VendorLTLL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/VendorLTUL__c.field-meta.xml
<CustomField>
    <fullName>VendorLTUL__c</fullName>
    <label>VendorLTUL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/VendorSite__c.field-meta.xml
<CustomField>
    <fullName>VendorSite__c</fullName>
    <label>VendorSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/Rupture_Disc__c.object-meta.xml
<CustomObject>
    <label>Rupture Disc</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rupture Disc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rupture Discs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Primary_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vendor__c</fullName>
    <label>Primary Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/RDOutputUtilityXMLTest.cls
@isTest
public class RDOutputUtilityXMLTest {

    public static id currentRD {get;set;}
    public static Rupture_Disc__c rdRecord = new Rupture_Disc__c();
    @testSetup
    public static void dataSetup() {
       
        TestDataRDUtility.createRDMasterTestRecords();
    }
    @isTest
    public static void getconfigRDCntrl() {
        Map<String, String> mapWithRDValues = new Map<String, String>();
        mapWithRDValues.put('BRAND','CDC');
        mapWithRDValues.put('PRODUCT_CODE','RD');
        mapWithRDValues.put('PRODUCT_NAME','Rupture Disc');
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithRDValues);
        TestDataRDUtility.quoteLine = quoteLine;
        TestDataRDUtility.mapWithRDValues = mapWithRDValues;
        //TestDataRDUtility.createRDMasterTestRecords();
    }
    public static RDOutputUtilityXML setValues() {

        RDOutputBaseUtilityTest.getconfigRDCntrl();
        TestDataRDUtility.createRDTestRecordWithOutput();
        List<Global_Site_Part_Parameters_ISPM__c> globalSiteParts = new List<Global_Site_Part_Parameters_ISPM__c>();
        Global_Site_Part_Parameters_ISPM__c obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '10';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777;
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);

        obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '20';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777;
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);

        obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '30';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777;
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);

        obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '40';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777;
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);

        insert globalSiteParts;


        List<Global_Site_Part_Parameters_PPS__c> siteParts = new List<Global_Site_Part_Parameters_PPS__c>();
        Global_Site_Part_Parameters_PPS__c obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '10';
        obj2.VendorSite__c = '20';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '10';
        obj2.VendorSite__c = '30';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '20';
        obj2.VendorSite__c = '10';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '20';
        obj2.VendorSite__c = '30';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '30';
        obj2.VendorSite__c = '10';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '30';
        obj2.VendorSite__c = '20';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '40';
        obj2.VendorSite__c = '10';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '40';
        obj2.VendorSite__c = '20';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '40';
        obj2.VendorSite__c = '30';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);

        insert siteParts;

        RDOutputUtilityXML obj = new RDOutputUtilityXML(TestDataRDUtility.conProd.id);
        obj.PARTNUMBER = '10000000000000000';
        obj.PARTREV = '1.0';
        obj.DESCRIPTION = 'Test Desc';
        obj.LOTTRACKCODE = '1';
        obj.PROVIDE = 'Test';
        obj.SERIALTRACKCODE = '1.0';

        Map<String, String> mapNewAttributeNames = new Map<String, String>();
        obj.mapNewAttributeNames = mapNewAttributeNames;
        obj.PARTCLASS = 'Test';
        obj.RESPONSIBLE_ID = 'Test';
        obj.ASSEMBLYWTUOM = 'Test';
        obj.ASSEMBLYWT = 'Test';
        obj.COMPRESPONID = 'Test';
       // obj.COMPDESCRIPTION = 'Test';
        obj.COMPINVSERTRK = 'Test';
        obj.COMPLOTTRACK = 'Test';
        obj.COMPPROVIDE = 'Test';
        obj.ATTRTEMPLATE = 'Test';
        obj.CUSTOMSTATNO = 'Test';
        obj.PLANNER = 'Test';
        obj.SALESGROUP = 'Test';
        obj.SALESPRICEGROUP = 'Test';
        obj.HSNSACCODE = 'Test';
        obj.PARTUOM = 'Test';
        obj.NOTE = 'Test';
        obj.PARTMANAGEDIN = 'Test';
        obj.SALESPRICEGROUP = 'Test';
        return obj;
    }
    @isTest
    public static void generalCoverage() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        //obj.GlobalSiteParametersISPM();
        obj.getGlobalSitePPS();
    }

    @isTest
    public static void testEngineeringParts() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getEngineeringParts();
    }

    @isTest
    public static void testEngPartCharacterXML() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getEngPartCharacterXML();
    }

    @isTest
    public static void testEngPartStructureXML() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getEngPartStructureXML();
    }

    @isTest
    public static void testENGPARTREV() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getENGPARTREV();
    }

    @isTest
    public static void testProdDoc() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getProdDoc();
    }

    @isTest
    public static void testProductCatalog() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getProductCatalog();
    }

    @isTest
    public static void testStructureXML() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getStructureXML();
    }

    @isTest
    public static void testInventoryPartDetails() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getInventoryPartDetails();
    }
    @isTest
    public static void testPurchasePartSuppliers() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getPurchasePartSuppliers();
    }

    @isTest
    public static void testSalesParts() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getSalesParts();
    }

    @isTest
    public static void testRoutingDetails() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.GetRoutingDetails();
    }

    @isTest
    public static void testControlPlanDetails() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.GetControlPlanDetails();
    }

    @isTest
    public static void testPurchasePart() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getPurchasePart();
    }

    @isTest
    public static void testPartNumber() {

        RDOutputUtilityXML obj = RDOutputUtilityXMLTest.setValues();
        obj.getPartNumber();
    }

}