force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/Global_Site_Part_Parameters_ISPM__c.object-meta.xml
<CustomObject>
    <label>Global Site Part Parameters (ISPM)</label>
    <nameField>
        <label>Global Site Part Parameters (ISPM)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Site Part Parameters (ISPM)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/InventoryPartTemplate_ID__c.field-meta.xml
<CustomField>
    <fullName>InventoryPartTemplate_ID__c</fullName>
    <label>InventoryPartTemplate_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/InventoryPartType__c.field-meta.xml
<CustomField>
    <fullName>InventoryPartType__c</fullName>
    <label>InventoryPartType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/InventorySite__c.field-meta.xml
<CustomField>
    <fullName>InventorySite__c</fullName>
    <label>InventorySite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/LeadTimeLL__c.field-meta.xml
<CustomField>
    <fullName>LeadTimeLL__c</fullName>
    <label>LeadTimeLL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/MfgSite__c.field-meta.xml
<CustomField>
    <fullName>MfgSite__c</fullName>
    <label>MfgSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/PurchasePartTemplate_ID__c.field-meta.xml
<CustomField>
    <fullName>PurchasePartTemplate_ID__c</fullName>
    <label>PurchasePartTemplate_ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/SalesSite__c.field-meta.xml
<CustomField>
    <fullName>SalesSite__c</fullName>
    <label>SalesSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/SERIALTRACKCODE__c.field-meta.xml
<CustomField>
    <fullName>SERIALTRACKCODE__c</fullName>
    <label>SERIALTRACKCODE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_ISPM__c/fields/Sourcing_Option__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Option__c</fullName>
    <label>Sourcing_Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/Global_Site_Part_Parameters_PPS__c.object-meta.xml
<CustomObject>
    <label>Global Site Part Parameters (PPS)</label>
    <nameField>
        <label>Global Site Part Parameters (PPS)</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global Site Part Parameters (PPS)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/LeadTimeUL__c.field-meta.xml
<CustomField>
    <fullName>LeadTimeUL__c</fullName>
    <label>LeadTimeUL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/PPS_VendoNo__c.field-meta.xml
<CustomField>
    <fullName>PPS_VendoNo__c</fullName>
    <label>PPS_VendoNo</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/Primary_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vendor__c</fullName>
    <label>Primary_Vendor</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/PurchaseSite__c.field-meta.xml
<CustomField>
    <fullName>PurchaseSite__c</fullName>
    <label>PurchaseSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/SITE__c.field-meta.xml
<CustomField>
    <fullName>SITE__c</fullName>
    <label>SITE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/VendorLTLL__c.field-meta.xml
<CustomField>
    <fullName>VendorLTLL__c</fullName>
    <label>VendorLTLL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/VendorLTUL__c.field-meta.xml
<CustomField>
    <fullName>VendorLTUL__c</fullName>
    <label>VendorLTUL</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Global_Site_Part_Parameters_PPS__c/fields/VendorSite__c.field-meta.xml
<CustomField>
    <fullName>VendorSite__c</fullName>
    <label>VendorSite</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/Holder_Outputs__c.object-meta.xml
<CustomObject>
    <label>Holder Outputs</label>
    <nameField>
        <label>Holder Output Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Outputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Outputs__c/fields/Lead_Time_Override__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_Override__c</fullName>
    <label>Lead Time Override</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/Additional_Documents__c.field-meta.xml
<CustomField>
    <fullName>Additional_Documents__c</fullName>
    <label>Additional Documents</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Lead_Time_Override__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Time Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Holders</relationshipLabel>
    <relationshipName>Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Size2__c.field-meta.xml
<CustomField>
    <fullName>Size2__c</fullName>
    <label>Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_SizeList__c/RD_SizeList__c.object-meta.xml
<CustomObject>
    <label>RD SizeList</label>
    <nameField>
        <label>RD SizeList</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RD SizeList</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RD_SizeList__c/fields/code__c.field-meta.xml
<CustomField>
    <fullName>code__c</fullName>
    <label>code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_SizeList__c/fields/Desc__c.field-meta.xml
<CustomField>
    <fullName>Desc__c</fullName>
    <label>Desc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_SizeList__c/fields/mmDesc__c.field-meta.xml
<CustomField>
    <fullName>mmDesc__c</fullName>
    <label>mmDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_SizeList__c/fields/SizeValue__c.field-meta.xml
<CustomField>
    <fullName>SizeValue__c</fullName>
    <label>SizeValue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_SizeList__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <label>Sort Order</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Lead_Time_Override__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_Override__c</fullName>
    <label>Intl. Lead Time Adder Override</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Primary_Vendor__c.field-meta.xml
<CustomField>
    <fullName>Primary_Vendor__c</fullName>
    <label>Primary Vendor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Yes_No</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/HLDOutputUtilityXMLTest.cls
@isTest
public class HLDOutputUtilityXMLTest {
    
    @testSetup
    public static void testRecords() {
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
        
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        quoteLine = [SELECT Id FROM SBQQ__QuoteLine__c LIMIT 1];
        Holders__c conHolder = [SELECT Id FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];
        conHolder.size2__c = '0400';
        conHolder.Part_Number__c = '10000000000000000';
        conHolder.Additional_Documents__c = 'Test1, Test2';
        update conHolder;
        
        Holder_Outputs__c output = [SELECT Id, Lead_Time_Override__c FROM Holder_Outputs__c LIMIT 1];
        output.Lead_Time_Override__c = 7779;
        update output;
        
        List<Global_Site_Part_Parameters_ISPM__c> globalSiteParts = new List<Global_Site_Part_Parameters_ISPM__c>();
        Global_Site_Part_Parameters_ISPM__c obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '10';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777; 
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);
        
        obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '20';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777; 
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);
        
        obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '30';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777; 
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);
        
        obj1 = new Global_Site_Part_Parameters_ISPM__c();
        obj1.InventorySite__c = '40';
        obj1.InventoryPartType__c = 'Purchased';
        obj1.InventoryPartTemplate_ID__c = 'Test';
        obj1.SalesSite__c = 'Test';
        obj1.Sourcing_Option__c = 'Test';
        obj1.PurchaseSite__c = 'Test';
        obj1.PurchasePartTemplate_ID__c = 'Test';
        obj1.MfgSite__c = 'Test';
        obj1.Site__c = '20';
        obj1.LeadTimeLL__c = 7777;
        obj1.LeadTimeUL__c = 7777; 
        obj1.SERIALTRACKCODE__c = '';
        globalSiteParts.add(obj1);
        
        insert globalSiteParts;
        
        
        List<Global_Site_Part_Parameters_PPS__c> siteParts = new List<Global_Site_Part_Parameters_PPS__c>();
        Global_Site_Part_Parameters_PPS__c obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '10';
        obj2.VendorSite__c = '20';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '10';
        obj2.VendorSite__c = '30';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '20';
        obj2.VendorSite__c = '10';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '20';
        obj2.VendorSite__c = '30';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '30';
        obj2.VendorSite__c = '10';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '30';
        obj2.VendorSite__c = '20';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '40';
        obj2.VendorSite__c = '10';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '40';
        obj2.VendorSite__c = '20';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        obj2 = new Global_Site_Part_Parameters_PPS__c();
        obj2.Name = 'Test';
        obj2.Site__c = '40';
        obj2.VendorSite__c = '30';
        obj2.VendorLTLL__c = 7777;
        obj2.VendorLTUL__c = 7778;
        obj2.Primary_Vendor__c = 'Test';
        obj2.PPS_VendoNo__c = 'Test';
        obj2.PurchaseSite__c = 'Test';
        siteParts.add(obj2);
        
        insert siteParts;
        
        RD_SizeList__c rdSize = new RD_SizeList__c();
        rdSize.code__c = '0400';
        rdSize.Desc__c  = '4" (100mm)';
        rdSize.mmDesc__c  = '(4") 100mm';
        rdSize.SizeValue__c  = '0400';
        rdSize.Sort_Order__c  = 25;
        insert rdSize;
    }
    
    public static HLDOutputUtilityXML setValues() {
        
        SBQQ__QuoteLine__c quoteLine = [SELECT Id FROM SBQQ__QuoteLine__c LIMIT 1];
        Holders__c conHolder = [SELECT Id FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];
        
        HLDOutputUtilityXML obj = new HLDOutputUtilityXML(conHolder.Id);
        obj.PARTNUMBER = '10000000000000000';
        obj.PARTREV = '1.0';
        obj.DESCRIPTION = 'Test Desc';
        obj.LOTTRACKCODE = '1';
        obj.PROVIDE = 'Test';
        obj.SERIALTRACKCODE = '1.0';
        
        Map<String, String> mapNewAttributeNames = new Map<String, String>();
        obj.mapNewAttributeNames = mapNewAttributeNames;
        obj.PARTCLASS = 'Test';
        obj.RESPONSIBLE_ID = 'Test';
        obj.ASSEMBLYWTUOM = 'Test';
        obj.ASSEMBLYWT = 'Test';
        obj.COMPRESPONID = 'Test';
        obj.COMPDESCRIPTION = 'Test';
        obj.COMPINVSERTRK = 'Test';
        obj.COMPLOTTRACK = 'Test';
        obj.COMPPROVIDE = 'Test';
        obj.ATTRTEMPLATE = 'Test';
        obj.CUSTOMSTATNO = 'Test';
        obj.PLANNER = 'Test';
        obj.SALESGROUP = 'Test';
        obj.SALESPRICEGROUP = 'Test';
        obj.HSNSACCODE = 'Test';
        obj.PARTUOM = 'Test';
        obj.NOTE = 'Test';
        obj.PARTMANAGEDIN = 'Test';
        obj.SALESPRICEGROUP = 'Test';
        
        return obj;
    }
    
    @isTest
    public static void generalCoverage() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        //obj.GlobalSiteParametersISPM();
        obj.getGlobalSitePPS();
    }
    
    @isTest
    public static void testEngineeringParts() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getEngineeringParts();
    }
    
    @isTest
    public static void testEngPartCharacterXML() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getEngPartCharacterXML();
    }
    
    @isTest
    public static void testEngPartStructureXML() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();        
        obj.getEngPartStructureXML();
    }
    
    @isTest
    public static void testENGPARTREV() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getENGPARTREV();
    }
    
    @isTest
    public static void testProdDoc() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getProdDoc();
    }
    
    @isTest
    public static void testProductCatalog() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getProductCatalog();
    }
    
    @isTest
    public static void testStructureXML() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getStructureXML();
    }
    
    @isTest
    public static void testInventoryPartDetails() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getInventoryPartDetails();
    }
    
    @isTest
    public static void testPurchasePartSuppliers() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getPurchasePartSuppliers();
    }
    
    @isTest
    public static void testSalesParts() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getSalesParts();
    }
    
    @isTest
    public static void testRoutingDetails() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.GetRoutingDetails();
    }
    
    @isTest
    public static void testControlPlanDetails() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.GetControlPlanDetails();
    }
    
    @isTest
    public static void testPurchasePart() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getPurchasePart();
    }
    
    @isTest
    public static void testPartNumber() {
       
        HLDOutputUtilityXML obj = HLDOutputUtilityXMLTest.setValues();
        obj.getPartNumber();
    }

}