force-app/main/default/objects/Holder_Additional_Acc_Details__c/Holder_Additional_Acc_Details__c.object-meta.xml
<CustomObject>
    <label>Holder Additional Acc Details</label>
    <nameField>
        <label>Holder Additional Acc Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Additional Acc Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Additional_Acc_Details__c/fields/Text2Val__c.field-meta.xml
<CustomField>
    <fullName>Text2Val__c</fullName>
    <label>Text2Val</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Additional_Acc_Details__c/fields/Text3Val__c.field-meta.xml
<CustomField>
    <fullName>Text3Val__c</fullName>
    <label>Text3Val</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Detail__c/Holder_Lookup_Detail__c.object-meta.xml
<CustomObject>
    <label>Holder Lookup Detail</label>
    <nameField>
        <displayFormat>HLD# {0000000}</displayFormat>
        <label>Holder Lookup Detail#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holder Lookup Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Lookup_Detail__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <label>Attribute</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Detail__c/fields/Holder_Lookup_Translation__c.field-meta.xml
<CustomField>
    <fullName>Holder_Lookup_Translation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Holder Lookup Translation</label>
    <referenceTo>Holder_Lookup_Translation__c</referenceTo>
    <relationshipLabel>Holder Lookup Details</relationshipLabel>
    <relationshipName>Holder_Lookup_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Detail__c/fields/Text1val__c.field-meta.xml
<CustomField>
    <fullName>Text1val__c</fullName>
    <label>Text1val</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Detail__c/fields/Text2val__c.field-meta.xml
<CustomField>
    <fullName>Text2val__c</fullName>
    <label>Text2val</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Detail__c/fields/Text3val__c.field-meta.xml
<CustomField>
    <fullName>Text3val__c</fullName>
    <label>Text3val</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Detail__c/fields/Text__c.field-meta.xml
<CustomField>
    <fullName>Text__c</fullName>
    <label>Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Lookup_Translation__c/Holder_Lookup_Translation__c.object-meta.xml
<CustomObject>
    <label>Holder Lookup Translation</label>
    <nameField>
        <displayFormat>HLT# {0000000}</displayFormat>
        <label>Holder Lookup  Translation #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holder Lookup Translations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Testing_Details__c/Holder_Testing_Details__c.object-meta.xml
<CustomObject>
    <label>Holder Testing Details</label>
    <nameField>
        <label>Holder Testing Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Testing Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Testing_Details__c/fields/TestCode__c.field-meta.xml
<CustomField>
    <fullName>TestCode__c</fullName>
    <label>TestCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Testing_Details__c/fields/Text1Val__c.field-meta.xml
<CustomField>
    <fullName>Text1Val__c</fullName>
    <label>Text1Val</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/Holddown_Ring_Material__c.field-meta.xml
<CustomField>
    <fullName>Holddown_Ring_Material__c</fullName>
    <label>Holddown Ring Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Holder_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Holder_Product_Code__c</fullName>
    <label>Holder Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Holders</relationshipLabel>
    <relationshipName>Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Spacer_Ring_Material__c.field-meta.xml
<CustomField>
    <fullName>Spacer_Ring_Material__c</fullName>
    <label>Spacer Ring Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Studs_and_Nuts__c.field-meta.xml
<CustomField>
    <fullName>Studs_and_Nuts__c</fullName>
    <label>Studs and Nuts</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ConfigHolderUtilityTest.cls
@isTest
public class ConfigHolderUtilityTest {
	
    @testSetup
    public static void dataSetup() {
        
        ConfigHoldersOutputController obj = new ConfigHoldersOutputController();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
    }
    
    @isTest
    public static ConfigHoldersOutputController getConfigHolderCntrl() {
        
        SBQQ__QuoteLine__c quoteLine  = [SELECT Id FROM SBQQ__QuoteLine__c LIMIT 1];
        
        TestDataHolderUtility.quoteLine = quoteLine;
            
        PageReference pager = Page.ConfigHoldersOutputs;
		Test.setCurrentPage(pager);
        
        ApexPages.currentPage().getParameters().put('qid', String.valueOf(quoteLine.Id));
        
        Holders__c conHolder = [SELECT Id FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];
        system.debug('conHolder:'+conHolder);
        
        System.debug('quoteId...'+quoteLine.Id);
        ApexPages.StandardController sc = new ApexPages.StandardController(quoteLine);
        
        return new ConfigHoldersOutputController(sc);
    }
    
    @isTest
    public static void testingCodeAttributesMap() {
        
        Test.startTest();        
        
        ConfigHoldersOutputController configHld = ConfigHolderUtilityTest.getConfigHolderCntrl();
        
        Holders__c conHolder = configHld.conHolder;
        ConfigHolderUtility obj = new ConfigHolderUtility(conHolder.Id);
        
        Map<String, Object> holderRequiredParameters = ConfigHolderUtility.holderRequiredParameters();
        
        Map<String, String> holderInputs = ConfigHolderUtility.holderInputs(conHolder);
        
        List<Holder_Testing_Details__c> testDetails = [SELECT Id, text1val__c, text2val__c, text3val__c FROM Holder_Testing_Details__c WHERE ( TestCode__c='A'  And text1val__c='N'  )];
        testDetails[0].text1val__c = 'N';
        testDetails[0].text2val__c = 'N';
        testDetails[0].text3val__c = 'CONFIRM';
        update testDetails;
        
        ConfigHolderUtility.testingCodeAttributesMap(holderInputs);
                
        Test.stopTest();
    }
    
    @isTest
    public static void testHolderRequiredParameters() {
        
        Test.startTest();        
        
        ConfigHoldersOutputController configHld = ConfigHolderUtilityTest.getConfigHolderCntrl();
        
        Holders__c conHolder = configHld.conHolder;
        ConfigHolderUtility obj = new ConfigHolderUtility(conHolder.Id);
        
        Map<String, Object> holderRequiredParameters = ConfigHolderUtility.holderRequiredParameters();
        
        Map<String, String> holderInputs = ConfigHolderUtility.holderInputs(conHolder);
        Map<String, Holder_Additional_Acc_Details__c> additionalAccAttributes = ConfigHolderUtility.additionalAccAttributes(holderInputs);
        
        ConfigHolderUtility.getPricing(holderInputs);
        
        Test.stopTest();
    }
    
    @isTest
    public static void testDataFromTranslation() {
        
        Test.startTest();        
        
        ConfigHoldersOutputController configHld = ConfigHolderUtilityTest.getConfigHolderCntrl();
        
        Holders__c conHolder = configHld.conHolder;
        ConfigHolderUtility obj = new ConfigHolderUtility(conHolder.Id);
        Map<String, String> holderInputs = ConfigHolderUtility.holderInputs(conHolder);
        
        Result lookupDetailList = new Result();
        List<String> selectCols = new List<String> {'Text__c'};
        ConfigHolderUtility.getDataFromTranslationObj('Attribute__c', 'Holder_Lookup_Translation__c', 'Holder_Lookup_Detail__c', holderInputs, selectCols, new List<String> {'OUTLETCOMPPTC'});

        ConfigHolderUtility.getDataFromTranslationObj('Attribute__c', 'Holder_Lookup_Translation__c', 'Holder_Lookup_Detail__c', holderInputs, selectCols, new List<String> {'OUTLETCOMPPTC'}, 'Text__c');
        
        ConfigHolderUtility.getHLDRouting(holderInputs);
        ConfigHolderUtility.getHolderControlPlan(holderInputs);
        
        Test.stopTest();
    }
    
    @isTest
    public static void testUtilityOthers() {
        
        Test.startTest();        
        
        ConfigHoldersOutputController configHld = ConfigHolderUtilityTest.getConfigHolderCntrl();
        
        Holders__c conHolder = configHld.conHolder;
        ConfigHolderUtility obj = new ConfigHolderUtility(conHolder.Id);
        Map<String, String> holderInputs = ConfigHolderUtility.holderInputs(conHolder);
   
        ConfigHolderUtility.getHolderWorkGuideLines(holderInputs);
        ConfigHolderUtility.getHolderDescription(holderInputs);
                
        Test.stopTest();
    }
    
    @isTest
    public static void testStructures() {
        
        Test.startTest();   
        
        ConfigHoldersOutputController configHld = ConfigHolderUtilityTest.getConfigHolderCntrl();
        
        Holders__c conHolder = configHld.conHolder;
        //conHolder.Spacer_Ring_Material__c = 'Test';
		//conHolder.Holder_Product_Code__c = 'PR8';
		//conHolder.Holddown_Ring_Material__c = 'Test';
        //update conHolder;
        
        ConfigHolderUtility obj = new ConfigHolderUtility(conHolder.Id);
        
        obj.getStructures();
                
        Test.stopTest();
    }
   
    @isTest
    public static void testIsHolderParamterRequired() {
        
        Test.startTest();  
     	
        ConfigHoldersOutputController configHld = ConfigHolderUtilityTest.getConfigHolderCntrl();
        
        Holders__c conHolder = configHld.conHolder;
        system.debug('conHolder.Holder_Product_Code__c:'+conHolder.Holder_Product_Code__c);
        Map<String, Object> holdersRequiredInfo = ConfigHolderUtility.holderRequiredParameters();
        system.debug('holdersRequiredInfo:'+holdersRequiredInfo);
        //ConfigHolderUtility.isHolderParamterRequired((sObject)holdersRequiredInfo.get(conHolder.Holder_Product_Code__c), 'Companion_Flange__c');
        
       	//ConfigHolderUtility.isHolderParamterRequiredString((sObject)holdersRequiredInfo.get(conHolder.Holder_Product_Code__c), 'Studs_and_Nuts__c');
        
        Test.stopTest();
    }
}