force-app/main/default/objects/BGR_Attribute_lookup_Details__c/BGR_Attribute_lookup_Details__c.object-meta.xml
<CustomObject>
    <label>BGR Attribute lookup Details</label>
    <nameField>
        <label>BGR Attribute lookup Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BGR Attribute lookup Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR_Attribute_lookup_Details__c/fields/Numval1__c.field-meta.xml
<CustomField>
    <fullName>Numval1__c</fullName>
    <label>Num1Val</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BGR_Attribute_lookup_Details__c/fields/Numval2__c.field-meta.xml
<CustomField>
    <fullName>Numval2__c</fullName>
    <label>Num2Val</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Goals_Performance__c/Goals_Performance__c.object-meta.xml
<CustomObject>
    <label>Goals &amp; Performance</label>
    <nameField>
        <displayFormat>GP-{00000}</displayFormat>
        <label>Goals &amp; Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals &amp; Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Goals_Performance__c/fields/Brands__c.field-meta.xml
<CustomField>
    <fullName>Brands__c</fullName>
    <label>Brands</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goals_Performance__c/fields/Fiscal_Month__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Month__c</fullName>
    <label>Fiscal Month</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>January</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>February</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>March</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>April</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>May</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>June</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>July</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>August</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>September</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>October</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>November</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>December</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goals_Performance__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goals_Performance__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Goal</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Goals_Performance__c/fields/Partner_Org__c.field-meta.xml
<CustomField>
    <fullName>Partner_Org__c</fullName>
    <label>Partner Org</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Goals &amp; Performance</relationshipLabel>
    <relationshipName>Goals_Performance</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CDC</fullName>
    </customValue>
    <customValue>
        <fullName>Groth</fullName>
    </customValue>
    <customValue>
        <fullName>LaMOT</fullName>
    </customValue>
    <customValue>
        <fullName>LVA</fullName>
    </customValue>
    <masterLabel>Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IFSOperationsTest.cls
@isTest 
private class IFSOperationsTest{
    @testSetup static void setup() {
       IFS_TestDataFactory.createTestRecords();        
    }
    
    static testMethod void syncCustomer(){
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.getAccountId(quote.Id);   
        IFSOperations.syncCustomer(null,quote.Id);
        Test.stopTest();
    }
    
    static testMethod void generateAndSyncParts() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.generateAndSyncParts(quote.Id);
        Test.stopTest();
    }
    
    static testMethod void generateAndSyncPartsAndOrder() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.generateAndSyncPartsAndOrder(quote.Id);
        Test.stopTest();
    }
    
     static testMethod void syncOrderValidation() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.syncOrderValidation(quote.Id);
        Test.stopTest();
    }    
    
    static testMethod void cancelOrderCancel() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.cancelOrder(null,quote.Id);
        Test.stopTest();
    }
       
    
    static testMethod void cancelOrderApprovedStatus(){      
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name=:'TEMCO INC TEST2']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.cancelOrder(accLst[0].Id,quote.Id);
        Test.stopTest();
    }
    
     /*static testMethod void getAccountId() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.getAccountId(quote.Id);
        Test.stopTest();
    }*/
    
    static testMethod void createCreditsAndBooking() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        List<Account> lstaccPartner = [Select Id,Name FROM Account WHERE Name='TEMCO INC PARTNER'];
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        date dtCloseDate =system.today();
        Goals_Performance__c oGoalsPerformance = new Goals_Performance__c();
        oGoalsPerformance.Partner_Org__c = lstaccPartner[0].Id;
        oGoalsPerformance.Brands__c = 'LaMot';
        oGoalsPerformance.Fiscal_Year__c = string.valueOf(dtCloseDate.Year());
        oGoalsPerformance.Fiscal_Month__c = string.valueOf(dtCloseDate.Month());
        oGoalsPerformance.Goal__c=4900;
        insert oGoalsPerformance;
        IFSOperations.createCreditsAndBooking(quote.Id);
        Test.stopTest();
    }
    
    static testMethod void syncCustomerClassic() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.syncCustomerClassic(accLst[0].Id,quote.Id);
        Test.stopTest();
    }
    
    static testMethod void syncPartsClassic() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        
        BGR_Attribute_lookup_Details__c oBGRAttribute = new BGR_Attribute_lookup_Details__c();
        oBGRAttribute.Name='bga001';
        oBGRAttribute.Attribute__c='RGEUNT';
        oBGRAttribute.Text__c='psig';
        oBGRAttribute.Numval1__c = 0;
        oBGRAttribute.Numval2__c = 20;
        insert oBGRAttribute;
        
        IFSOperations.syncPartsClassic(accLst[0].Id,quote.Id);
        Test.stopTest();
    }
    
    static testMethod void syncOrderClassic() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.syncOrderClassic(accLst[0].Id,quote.Id);
        IFSOperations.cancelOrderClassic(accLst[0].Id,quote.Id);
        Test.stopTest();
    }
    
    /*static testMethod void cancelOrderClassic() {
        Test.startTest();        
        List<Account> accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST']; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst[0].Id limit 1];
        IFSOperations.cancelOrderClassic(accLst[0].Id,quote.Id);
        Test.stopTest();
    }*/
    
    
}