force-app/main/default/objects/BGR_Attribute_lookup_Details__c/BGR_Attribute_lookup_Details__c.object-meta.xml
<CustomObject>
    <label>BGR Attribute lookup Details</label>
    <nameField>
        <label>BGR Attribute lookup Details</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BGR Attribute lookup Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR_Attribute_lookup_Details__c/fields/Numval1__c.field-meta.xml
<CustomField>
    <fullName>Numval1__c</fullName>
    <label>Num1Val</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BGR_Attribute_lookup_Details__c/fields/Numval2__c.field-meta.xml
<CustomField>
    <fullName>Numval2__c</fullName>
    <label>Num2Val</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/isIFSManaged__c.field-meta.xml
<CustomField>
    <fullName>isIFSManaged__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Integration use only</description>
    <label>isIFSManaged</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/IFS_ConstructPartReqWithBatchTest.cls
@isTest
private class IFS_ConstructPartReqWithBatchTest{          
   static testMethod void generateReq(){
        Test.startTest();
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1];
        BGR_Attribute_lookup_Details__c oBGRAttribute = new BGR_Attribute_lookup_Details__c();
        oBGRAttribute.Name='bga001';
        oBGRAttribute.Attribute__c='RGEUNT';
        oBGRAttribute.Text__c='psig';
        oBGRAttribute.Numval1__c = 0;
        oBGRAttribute.Numval2__c = 20;
        insert oBGRAttribute;
        List<SBQQ__QuoteLine__c> quoteLines=[Select Id,SBQQ__ProductCode__c, isIFSManaged__c FROM SBQQ__QuoteLine__c where SBQQ__Quote__c=: quote.Id];
        Map<Id,HandlerInterface> genUtilMap = new Map<id,HandlerInterface>();
        Integer recordsProcessed = 0;
        if(quoteLines.size()>0){    
            for(SBQQ__QuoteLine__c eachQuoteLine : quoteLines){ 
                Id currentId=wizardBaseDataProcessor.getCustomObjectIDbyLine(eachQuoteLine.Id);
                GenericUtilityForXML generic=new GenericUtilityForXML();
                HandlerInterface genUtil = generic.getUtilityInstance(eachQuoteLine.SBQQ__ProductCode__c,currentId);                    
                genUtilMap.put(eachQuoteLine.Id,genUtil);
                        
                recordsProcessed = recordsProcessed + 1;
            }
        }
         if(recordsProcessed > 0){            
            if(quoteLines.size()>0){                
                List<String> batchList=new List<String>();  
                for(SBQQ__QuoteLine__c quoteLine : quoteLines){                    
                        if(quoteLine.SBQQ__ProductCode__c!='PS' || !quoteLine.isIFSManaged__c){
                            batchList.add(quoteLine.Id+'_'+'getEngineeringParts');
                            batchList.add(quoteLine.Id+'_'+'getInventoryPartDetails');
                            batchList.add(quoteLine.Id+'_'+'getSalesParts');
                            batchList.add(quoteLine.Id+'_'+'getPurchasePart');
                            batchList.add(quoteLine.Id+'_'+'getPurchasePartSuppliers');
                            batchList.add(quoteLine.Id+'_'+'getProductCatalog');
                            batchList.add(quoteLine.Id+'_'+'getStructureXML');
                            batchList.add(quoteLine.Id+'_'+'GetRoutingDetails');
                            batchList.add(quoteLine.Id+'_'+'GetControlPlanDetails');
                        }                       
                }                
                try{
                if(batchList.size() > 0){   
                    IFS_ConstructPartReqWithBatch  partReq = new IFS_ConstructPartReqWithBatch(quote.Id,accLst.Id,genUtilMap,batchList,false);                    
                    Database.executeBatch(partReq);                    
                }
                }catch(Exception e){
                    System.debug('Exception :'+e.getMessage());
                }
            }
        }        
        Test.stopTest();
    }
    static testMethod void generateReq2(){
        Test.startTest();
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1];
        BGR_Attribute_lookup_Details__c oBGRAttribute = new BGR_Attribute_lookup_Details__c();
        oBGRAttribute.Name='bga001';
        oBGRAttribute.Attribute__c='RGEUNT';
        oBGRAttribute.Text__c='psig';
        oBGRAttribute.Numval1__c = 0;
        oBGRAttribute.Numval2__c = 20;
        insert oBGRAttribute;
        List<SBQQ__QuoteLine__c> quoteLines=[Select Id,SBQQ__ProductCode__c, isIFSManaged__c FROM SBQQ__QuoteLine__c where SBQQ__Quote__c=: quote.Id];
        Map<Id,HandlerInterface> genUtilMap = new Map<id,HandlerInterface>();
        Integer recordsProcessed = 0;
        if(quoteLines.size()>0){    
            for(SBQQ__QuoteLine__c eachQuoteLine : quoteLines){ 
                Id currentId=wizardBaseDataProcessor.getCustomObjectIDbyLine(eachQuoteLine.Id);
                GenericUtilityForXML generic=new GenericUtilityForXML();
                HandlerInterface genUtil = generic.getUtilityInstance(eachQuoteLine.SBQQ__ProductCode__c,currentId);                    
                genUtilMap.put(eachQuoteLine.Id,genUtil);
                        
                recordsProcessed = recordsProcessed + 1;
            }
        }
         if(recordsProcessed > 0){            
            if(quoteLines.size()>0){                
                List<String> batchList=new List<String>();  
                for(SBQQ__QuoteLine__c quoteLine : quoteLines){                    
                        if(quoteLine.SBQQ__ProductCode__c!='PS' || !quoteLine.isIFSManaged__c){
                            batchList.add(quoteLine.Id+'_'+'getEngineeringParts');
                            batchList.add(quoteLine.Id+'_'+'getInventoryPartDetails');
                            batchList.add(quoteLine.Id+'_'+'getSalesParts');
                            batchList.add(quoteLine.Id+'_'+'getPurchasePart');
                            batchList.add(quoteLine.Id+'_'+'getPurchasePartSuppliers');
                            batchList.add(quoteLine.Id+'_'+'getProductCatalog');
                            batchList.add(quoteLine.Id+'_'+'getStructureXML');
                            batchList.add(quoteLine.Id+'_'+'GetRoutingDetails');
                            batchList.add(quoteLine.Id+'_'+'GetControlPlanDetails');
                        }                       
                }                
                try{
                if(batchList.size() > 0){   
                    IFS_ConstructPartReqWithBatch  partReq = new IFS_ConstructPartReqWithBatch(quote.Id,accLst.Id,genUtilMap,batchList,true);                    
                    Database.executeBatch(partReq);                    
                }
                }catch(Exception e){
                    System.debug('Exception :'+e.getMessage());
                }
            }
        }        
        Test.stopTest();
    }
}