force-app/main/default/objects/BGR__c/BGR__c.object-meta.xml
<CustomObject>
    <label>BGR</label>
    <nameField>
        <displayFormat>BGR-{0000}</displayFormat>
        <label>Blanket Gas Regulator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BGR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR__c/fields/Connection_dynamic__c.field-meta.xml
<CustomField>
    <fullName>Connection_dynamic__c</fullName>
    <label>Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <label>1/2</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Soft_Goods_Material_dynamic__c.field-meta.xml
<CustomField>
    <fullName>Soft_Goods_Material_dynamic__c</fullName>
    <label>Soft Goods Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGR_Connections__c/BGR_Connections__c.object-meta.xml
<CustomObject>
    <label>BGR Connections</label>
    <nameField>
        <label>BGR Connections</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BGR Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR_Connections__c/fields/ConnectionDesc__c.field-meta.xml
<CustomField>
    <fullName>ConnectionDesc__c</fullName>
    <label>ConnectionDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGR_Matlist__c/BGR_Matlist__c.object-meta.xml
<CustomObject>
    <label>BGR Matlist</label>
    <nameField>
        <label>BGR Matlist</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BGR Matlist</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/configBgrReferenceCtrl.cls
public class configBgrReferenceCtrl {
    public BGR__c oBGR{get;set;}
    public User oUser {get;set;}
    public string getUserTimeZone(){
        return userinfo.getTimeZone().toString();
    }
    
    public configBgrReferenceCtrl(ApexPages.StandardController controller){
        if (!Test.isRunningTest()) { 
	   controller.addFields(new String[]{'Soft_Goods_Material_dynamic__c','Size__c','Connection_dynamic__c'});
        }
        oBGR = (BGR__c)controller.getRecord();    
        for(User u : [Select Id,Name From User Where Id =: userinfo.getUserId()]){
            oUser = u;
        }
    }
    
    
    public string getSoftGoodsMaterial() {
        List<BGR_Matlist__c> BodyMaterial = new List<BGR_Matlist__c>();
        Set<string> BodyMaterialSet = new Set<string>();
        String BaseQuery = 'Select SZC__c,Component__c,MatlCode__c,Description__c from BGR_Matlist__c ';
        String WhereClause ='';
        String Comp = 'Soft Goods Material';
        if(oBGR.Size__c!=null) { 
            BaseQuery = BaseQuery+'where SZC__c =\''+oBGR.Size__c+'\' and Component__c=\''+Comp+'\'' ;
        }
        BodyMaterial = Database.query(BaseQuery) ;
        
        for (BGR_Matlist__c bm :BodyMaterial) {
            if(bm.MatlCode__c == string.valueOf(oBGR.Soft_Goods_Material_dynamic__c) ){
               return bm.Description__c;
            }
        }
        return null;
    }
    
    public string getConnection() {
        List<BGR_Connections__c> Connection = new List<BGR_Connections__c>();
        Set<string> ConnectionSet = new Set<string>();
        String BaseQuery = 'Select SZC__c,ConnectionCode__c,ConnectionDesc__c from BGR_Connections__c ';
        String WhereClause ='';
        if(oBGR.Size__c!=null) 
            WhereClause = 'where  SZC__c =\''+oBGR.Size__c+'\'';
        //WhereClause = WhereClause +' '+ 'and'+' '+'Component__c=\''+Comp+'\'';
        
        Connection=Database.query(BaseQuery + WhereClause) ;
        
        for (BGR_Connections__c con :Connection) {
            if(con.ConnectionCode__c == string.valueOf(oBGR.Connection_dynamic__c) ){
               return con.ConnectionDesc__c;
            }
        }
        return null;
    }
}