force-app/main/default/objects/BGR__c/BGR__c.object-meta.xml
<CustomObject>
    <label>BGR</label>
    <nameField>
        <displayFormat>BGR-{0000}</displayFormat>
        <label>Blanket Gas Regulator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BGR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>BGR</relationshipLabel>
    <relationshipName>BGR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/Flame_Product__c.object-meta.xml
<CustomObject>
    <label>Flame Product</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flame Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flame Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flame_Product__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Flame Products</relationshipLabel>
    <relationshipName>Flame_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Holders</relationshipLabel>
    <relationshipName>Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/Part_Selector__c.object-meta.xml
<CustomObject>
    <label>Part Selector</label>
    <nameField>
        <label>Part Selector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Selectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Selector__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Part Selectors</relationshipLabel>
    <relationshipName>Part_Selectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/Relief_Valve__c.object-meta.xml
<CustomObject>
    <description>Relief valves custom object</description>
    <label>Relief Valve</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Relief Valve Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relief Valves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relief_Valve__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Relief Valves</relationshipLabel>
    <relationshipName>Relief_Valves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/Rupture_Disc__c.object-meta.xml
<CustomObject>
    <label>Rupture Disc</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rupture Disc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rupture Discs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rupture_Disc__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Rupture Discs</relationshipLabel>
    <relationshipName>Rupture_Discs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/WasteGasBurner__c.object-meta.xml
<CustomObject>
    <label>WasteGasBurner</label>
    <nameField>
        <displayFormat>WGB-{0000}</displayFormat>
        <label>WasteGasBurner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WasteGasBurners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteGasBurner__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>WasteGasBurners</relationshipLabel>
    <relationshipName>WasteGasBurners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ReorderDriverFutureEvents.cls
/***************************************************************************************************************
* @Name         ReorderDriverFutureEvents
* @Author       Vikram Natikar <vikram.natikar@apexit.com>
* @Date         10/14/2020
* @Description  This class is a which handles the Reorder functionality for RuptureDisc,Holders,
				WasteGasBurner,FlameProducts,BlanketGasRegulator and Relief Valve products
*****************************************************************************************************************/

public class ReorderDriverFutureEvents {
	
    @future(callout = true) 
    public static void invokeEventWGB(String quoteLineId) {
        
        WasteGasBurner__c wgb = [SELECT Id, Quote_Line__c FROM WasteGasBurner__c WHERE Id = :quoteLineId LIMIT 1];
        ConfigureWasteGasBurner conWGB = new ConfigureWasteGasBurner(wgb.Quote_Line__c);        
        conWGB.ReorderFlag = true;
        
        conWGB.saveSelections();
    }
    @future(callout = true) 
    public static void invokeEventFA(String quoteLineId) {
        
        Flame_Product__c fa = [SELECT Id, Quote_Line__c FROM Flame_Product__c WHERE Id = :quoteLineId LIMIT 1];
        configureFLAMEproduct conFA = new configureFLAMEproduct(fa.Quote_Line__c);        
        conFA.ReorderFlag = true;
        
        conFA.saveCertificateDocumentOrSourcingRestrictions();
    }
    @future(callout = true) 
    public static void invokeEventBGR(String quoteLineId) {
        
        BGR__c bgr = [SELECT Id, Quote_Line__c FROM BGR__c WHERE Id = :quoteLineId LIMIT 1];
        configureBGRProduct conBGR = new configureBGRProduct(bgr.Quote_Line__c);      
        conBGR.ReorderFlag = true;
        
        conBGR.saveDocSourcing();
    }
     @future(callout = true) 
    public static void invokeEventRV(String quoteLineId) {
        
        Relief_Valve__c rv = [SELECT Id, Quote_Line__c FROM Relief_Valve__c WHERE Id = :quoteLineId LIMIT 1];
        configureRVproduct conRV = new configureRVproduct(rv.Quote_Line__c);        
        conRV.ReorderFlag = true;
        
        conRV.saveDocSourcing();
    }
    @future(callout = true) 
    public static void invokeEventHLD(String quoteLineId) {
        
        Holders__c hld = [SELECT Id, Quote_Line__c FROM Holders__c WHERE Id = :quoteLineId LIMIT 1];
        ConfigHolderController conHLD = new ConfigHolderController(hld.Quote_Line__c);        
        conHLD.ReorderFlag = true;
        
        conHLD.saveCleaningMarkingsTesting();
    }
    @future(callout = true) 
    public static void invokeEventHLD2(String quoteLineId) {
        
        Holders__c hld = [SELECT Id, Quote_Line__c FROM Holders__c WHERE Id = :quoteLineId LIMIT 1];
        ConfigHoldersOutputController conHLD2 = new ConfigHoldersOutputController(HLD.Quote_Line__c);
        
        conHLD2.SavePriceOverride();
    }
    @future(callout = true) 
    public static void invokeEventRD(String quoteLineId) {
        
        Rupture_Disc__c rd = [SELECT Id, Quote_Line__c FROM Rupture_Disc__c WHERE Id = :quoteLineId LIMIT 1];
        ConfigureRD conRD = new ConfigureRD(rd.Quote_Line__c);        
        conRD.ReorderFlag = true;
        
        conRD.saveCleaningsTestsandProcesses();
    }
  /*  @future(callout = true) 
    public static void invokeEventPS(String quoteLineId) {
        
       	Part_Selector__c psrecord = [SELECT Id, Quote_Line__c FROM Part_Selector__c WHERE Id = :quoteLineId LIMIT 1];
        configurePartSelector PS = new configurePartSelector(psrecord.Quote_Line__c);        
      //  conRD.ReorderFlag = true;
        
        PS.saveProdPartNumber();
    }*/
    
    
}