force-app/main/default/objects/BGR__c/BGR__c.object-meta.xml
<CustomObject>
    <label>BGR</label>
    <nameField>
        <displayFormat>BGR-{0000}</displayFormat>
        <label>Blanket Gas Regulator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BGR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3011L</fullName>
            </value>
            <value>
                <fullName>3011H</fullName>
            </value>
            <value>
                <fullName>3011HP</fullName>
            </value>
            <value>
                <fullName>3020A</fullName>
            </value>
            <value>
                <fullName>3041L</fullName>
            </value>
            <value>
                <fullName>3041H</fullName>
            </value>
            <value>
                <fullName>3041HP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>BGR</relationshipLabel>
    <relationshipName>BGR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/Flame_Product__c.object-meta.xml
<CustomObject>
    <label>Flame Product</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flame Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flame Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flame_Product__c/fields/Connection_Size__c.field-meta.xml
<CustomField>
    <fullName>Connection_Size__c</fullName>
    <label>Connection Size Filter (Optional)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Element_Size__c.field-meta.xml
<CustomField>
    <fullName>Element_Size__c</fullName>
    <label>Element Size Filter (Optional)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/KD__c.field-meta.xml
<CustomField>
    <fullName>KD__c</fullName>
    <label>KD</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model with Connection and Element Sizes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/PresRatio__c.field-meta.xml
<CustomField>
    <fullName>PresRatio__c</fullName>
    <label>PresRatio</label>
    <precision>17</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Flame Products</relationshipLabel>
    <relationshipName>Flame_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FLM_KD__c/FLM_KD__c.object-meta.xml
<CustomObject>
    <label>FLM KD</label>
    <nameField>
        <label>FLM KD Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FLM KDs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FLM_KD__c/fields/ConnSizeCode__c.field-meta.xml
<CustomField>
    <fullName>ConnSizeCode__c</fullName>
    <label>ConnSizeCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FLM_KD__c/fields/EffDia__c.field-meta.xml
<CustomField>
    <fullName>EffDia__c</fullName>
    <label>EffDia</label>
    <precision>13</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FLM_KD__c/fields/ElemMatlCode__c.field-meta.xml
<CustomField>
    <fullName>ElemMatlCode__c</fullName>
    <label>ElemMatlCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FLM_KD__c/fields/Kd__c.field-meta.xml
<CustomField>
    <fullName>Kd__c</fullName>
    <label>Kd</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FLM_KD__c/fields/PresRatio__c.field-meta.xml
<CustomField>
    <fullName>PresRatio__c</fullName>
    <label>PresRatio</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/FLM_MasterBlaster__c/FLM_MasterBlaster__c.object-meta.xml
<CustomObject>
    <label>FLM MasterBlaster</label>
    <nameField>
        <label>FLM MasterBlaster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FLM MasterBlasters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FLM_MasterBlaster__c/fields/ElemSizeCode__c.field-meta.xml
<CustomField>
    <fullName>ElemSizeCode__c</fullName>
    <label>ElemSizeCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FLM_MasterBlaster__c/fields/HousingMatlCode__c.field-meta.xml
<CustomField>
    <fullName>HousingMatlCode__c</fullName>
    <label>HousingMatlCode</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/GasFlowRate__c.object-meta.xml
<CustomObject>
    <label>GasFlowRate</label>
    <nameField>
        <label>GasFlowRate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GasFlowRates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GasFlowRate__c/fields/DensityStandardFrom__c.field-meta.xml
<CustomField>
    <fullName>DensityStandardFrom__c</fullName>
    <label>DensityStandardFrom</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/DensityStandardTo__c.field-meta.xml
<CustomField>
    <fullName>DensityStandardTo__c</fullName>
    <label>DensityStandardTo</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/GasFlowRate_UOM_From__c.field-meta.xml
<CustomField>
    <fullName>GasFlowRate_UOM_From__c</fullName>
    <label>GasFlowRate_UOM_From</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACFH</fullName>
            </value>
            <value>
                <fullName>ACFM</fullName>
            </value>
            <value>
                <fullName>Am3/h</fullName>
            </value>
            <value>
                <fullName>Am3/min</fullName>
            </value>
            <value>
                <fullName>kg/h</fullName>
            </value>
            <value>
                <fullName>kg/min</fullName>
            </value>
            <value>
                <fullName>lb/h</fullName>
            </value>
            <value>
                <fullName>lb/min</fullName>
            </value>
            <value>
                <fullName>Nm3/h</fullName>
            </value>
            <value>
                <fullName>Nm3/min</fullName>
            </value>
            <value>
                <fullName>SCFH</fullName>
            </value>
            <value>
                <fullName>SCFM</fullName>
            </value>
            <value>
                <fullName>SCMH</fullName>
            </value>
            <value>
                <fullName>kg/s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/GasFlowRate_UOM_To__c.field-meta.xml
<CustomField>
    <fullName>GasFlowRate_UOM_To__c</fullName>
    <label>GasFlowRate_UOM_To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACFH</fullName>
            </value>
            <value>
                <fullName>ACFM</fullName>
            </value>
            <value>
                <fullName>Am3/h</fullName>
            </value>
            <value>
                <fullName>Am3/min</fullName>
            </value>
            <value>
                <fullName>kg/h</fullName>
            </value>
            <value>
                <fullName>kg/min</fullName>
            </value>
            <value>
                <fullName>lb/h</fullName>
            </value>
            <value>
                <fullName>lb/min</fullName>
            </value>
            <value>
                <fullName>Nm3/h</fullName>
            </value>
            <value>
                <fullName>Nm3/min</fullName>
            </value>
            <value>
                <fullName>SCFH</fullName>
            </value>
            <value>
                <fullName>SCFM</fullName>
            </value>
            <value>
                <fullName>SCMH</fullName>
            </value>
            <value>
                <fullName>kg/s</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/PFromPsia__c.field-meta.xml
<CustomField>
    <fullName>PFromPsia__c</fullName>
    <label>PFromPsia</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/PToPsia__c.field-meta.xml
<CustomField>
    <fullName>PToPsia__c</fullName>
    <label>PToPsia</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/TFromR__c.field-meta.xml
<CustomField>
    <fullName>TFromR__c</fullName>
    <label>TFromR</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GasFlowRate__c/fields/TToR__c.field-meta.xml
<CustomField>
    <fullName>TToR__c</fullName>
    <label>TToR</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>LaMOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Holders</relationshipLabel>
    <relationshipName>Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/Part_Selector__c.object-meta.xml
<CustomObject>
    <label>Part Selector</label>
    <nameField>
        <label>Part Selector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Selectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Selector__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>Quote_Line__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Part Selectors</relationshipLabel>
    <relationshipName>Part_Selectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>SBQQ__Quote__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DataSelectorWizard.cls
public with sharing class DataSelectorWizard 
{
    private static DataSelectorWizard instance = null;
    //the constructor is marked PRIVATE
    // so that no Apex code outside this class can create the instance
    private DataSelectorWizard()
    {

    }

    /*
    This static method will be the only way to get the Single
    instance of this class.
    */
    public static DataSelectorWizard getInstance()
    {
        if (instance == null)
        {
            // Create the single instance now.
            instance = new DataSelectorWizard();
        }
        return instance;
    }
    public static Flame_Product__c getFlameProductRecord(String quotelineId)
    {
        Flame_Product__c flameProduct;
        String fieldsAPIname = FLMutility.getObjectFields('Flame_Product__c');
        String soql = 'SELECT '+fieldsAPIname+' FROM Flame_Product__c where Quote_Line__c =\''+String.escapeSingleQuotes(quotelineId)+'\' limit 1';
        flameProduct  = Database.query(soql);
        return flameProduct;
    }
     public static BGR__c getBGRProductRecord(String quotelineId)
    {
        BGR__c BGRProduct;
        String fieldsAPIname = FLMutility.getObjectFields('BGR__c');
        String soql = 'SELECT Quote_Line__r.SBQQ__Quote__r.Brand__c, '+fieldsAPIname+' FROM BGR__c where Quote_Line__c =\''+String.escapeSingleQuotes(quotelineId)+'\' limit 1';
        BGRProduct  = Database.query(soql);
        return BGRProduct;
    }
    
     public static Part_Selector__c getPartSelectorRecord(String PSId)
    {
        Part_Selector__c PSProduct;
        String fieldsAPIname = FLMutility.getObjectFields('Part_Selector__c');
        String soql = 'SELECT '+fieldsAPIname+' FROM Part_Selector__c where Id=\''+String.escapeSingleQuotes(PSId)+'\' limit 1';
        PSProduct  = Database.query(soql);
        return PSProduct;
    }
    public static Holders__c getHolderProductRecord(String quotelineId)
    {
        Holders__c holderProduct;
        String fieldsAPIname = FLMutility.getObjectFields('Holders__c');
        System.debug('fieldsAPIname...'+fieldsAPIname);
        System.debug('quotelineId....'+quotelineId);
        String soql = 'SELECT '+fieldsAPIname+' FROM Holders__c where Quote_Line__c =\''+String.escapeSingleQuotes(quotelineId)+'\' limit 1';
        holderProduct  = Database.query(soql);
        return holderProduct;
    }
    
    public static Map<String, GasFlowRate__c> getFlameProductRecord()
    {
        Map<String, GasFlowRate__c> flowRateMap = new Map<String, GasFlowRate__c>();
        for(GasFlowRate__c gfw : [select Multiplier__c,DensityActualFrom__c,DensityActualTo__c,DensityStandardFrom__c,DensityStandardTo__c,PFromPsia__c,PToPsia__c,TFromR__c,TToR__c,GasFlowRate_UOM_From__c,GasFlowRate_UOM_To__c from GasFlowRate__c])
        {
            if(String.isNotBlank(gfw.GasFlowRate_UOM_From__c) && String.isNotBlank(gfw.GasFlowRate_UOM_To__c))
            {
                String flowRateKey = gfw.GasFlowRate_UOM_From__c +'_'+ gfw.GasFlowRate_UOM_To__c;
                if(!flowRateMap.containsKey(flowRateKey))
                {
                    flowRateMap.put(flowRateKey, gfw);
                }
            }
        }
        return flowRateMap;
    }

    /*
    public static List<FLM_KD__c> getFLMKDRecord()
    {
        List<FLM_KD__c> KDTable = new List<FLM_KD__c>();
        KDTable = [select KD__c,PresRatio__c,EffDia__c, Model__c,ConnSizeCode__c from FLM_KD__c
                        order by PresRatio__c ASC];
        return KDTable;
    }
    public static Map<String, Map<String, Map<String, List<FLM_MasterBlaster__c>>>> getFLMMasterBlaster(Flame_Product__c flmprod)
    {
        Map<String, Map<String, Map<String, List<FLM_MasterBlaster__c>>>> masterMap= new Map<String, Map<String, Map<String, List<FLM_MasterBlaster__c>>>>();
       //
      //   * Outer key1 = Model+connectionsize+elementsize
      //   * Outer key2 = Outerkey1+Bodymaterial
      //   * Outer key3 = Outerkey2+HousingMaterial
        
        for(FLM_MasterBlaster__c fm: [SELECT Id, Model__c, ConnSizeCode__c, ElemSizeCode__c,BodyMatlCode__c,HousingMatlCode__c,ElemMatlCode__c FROM FLM_MasterBlaster__c
                                     WHERE Model__c =:flmprod.Model__c AND ConnSizeCode__c =:flmprod.Connection_Size__c AND ElemSizeCode__c =:flmProd.Element_Size__c])
        {
            String outerKey1 = fm.Model__c +'_'+ fm.ConnSizeCode__c +'_'+ fm.ElemSizeCode__c;
            String outerKey2 = outerKey1 + '_' + fm.BodyMatlCode__c;
            String outerKey3 = outerKey2 + '_'+ fm.HousingMatlCode__c;
            if(!masterMap.containsKey(outerKey1))
            {
                masterMap.put(outerKey1,new Map<String, Map<String, List<FLM_MasterBlaster__c>>>());
                if(!masterMap.get(outerKey1).containsKey(outerKey2))
                {
                    masterMap.get(outerKey1).put(outerKey2, new Map<String, List<FLM_MasterBlaster__c>>());
                }
                if(!masterMap.get(outerKey1).get(outerKey2).containsKey(outerKey2))
                {
                    masterMap.get(outerKey1).get(outerKey2).put(outerKey3, new List<FLM_MasterBlaster__c>());
                }
            }
            masterMap.get(outerKey1).get(outerKey2).get(outerKey3).add(fm);
        }
        system.debug('**** returning masterMap = '+masterMap);
        return masterMap;
    }*/
    
    public static Result convertGasFlowRate(GasFlowRate__c temp, decimal GasFlowRate_Value_From, decimal P_psia, decimal MW, decimal T_DegR, decimal Z) 
    {
        
        decimal convertedValue;
        decimal numerator;
        decimal numerator1;
        decimal denominator1;
        decimal numerator2;
        decimal denominator2;
        Result objResult = new Result();
        try{
            if (temp != null && temp.Id != null) 
            {
                numerator=GasFlowRate_Value_From*temp.Multiplier__c;
                numerator1=Math.pow(((P_psia*MW*144)/(1545*T_DegR*Z)).doubleValue(), temp.DensityActualFrom__c.doubleValue());
                denominator1=Math.pow(((P_psia*MW*144)/(1545*T_DegR*Z)).doubleValue(), temp.DensityActualTo__c.doubleValue());
                numerator2=Math.pow(((temp.PFromPsia__c*MW*144)/(1545*temp.TFromR__c*Z)).doubleValue(), temp.DensityStandardFrom__c.doubleValue());
                denominator2=Math.pow(((temp.PToPsia__c*MW*144)/(1545*temp.TToR__c*Z)).doubleValue(), temp.DensityStandardTo__c.doubleValue());
                objResult.dblRetValue=numerator*(numerator1/denominator1)*(numerator2/denominator2);
                objResult.bResult = true;
                System.debug('***** From = '+temp.GasFlowRate_UOM_From__c+', to = '+temp.GasFlowRate_UOM_To__c);
                System.debug('***** convertGasFlowRate : ' + string.valueof(objResult.dblRetValue));
            } else {
                objResult.bResult = false; 
                //objResult.dblRetValue=0;
                objResult.strErrorMessage = 'No Data Found';
            }
            
        }
        catch(Exception e) { 
            System.debug('The following exception has occurred: unitConversions:convertGasFlowRate()' + e.getMessage());
            objResult.bResult = false;
            //objResult.dblRetValue=0;
            objResult.strErrorMessage = e.getMessage();
            System.debug(objResult.strErrorMessage);
        }
        
        return objResult;
    }
}