force-app/main/default/objects/BGR__c/BGR__c.object-meta.xml
<CustomObject>
    <label>BGR</label>
    <nameField>
        <displayFormat>BGR-{0000}</displayFormat>
        <label>Blanket Gas Regulator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BGR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR__c/fields/Non_Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_Price__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Non-Discountable Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>BGR</relationshipLabel>
    <relationshipName>BGR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <label>1/2</label>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/Flame_Product__c.object-meta.xml
<CustomObject>
    <label>Flame Product</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flame Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flame Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flame_Product__c/fields/Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Discountable_Price__c</fullName>
    <label>Discountable Price</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Non_Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_Price__c</fullName>
    <label>Non Discountable Price</label>
    <precision>18</precision>
    <scale>10</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Flame Products</relationshipLabel>
    <relationshipName>Flame_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Discountable_Price__c</fullName>
    <label>Discountable Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Non_Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_Price__c</fullName>
    <label>Non Discountable Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Holders</relationshipLabel>
    <relationshipName>Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/Relief_Valve__c.object-meta.xml
<CustomObject>
    <description>Relief valves custom object</description>
    <label>Relief Valve</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Relief Valve Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relief Valves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relief_Valve__c/fields/Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Discountable_Price__c</fullName>
    <label>Discountable Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Non_Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_Price__c</fullName>
    <label>Non Discountable Price</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>ASSYPARTEXISTING</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Relief Valves</relationshipLabel>
    <relationshipName>Relief_Valves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/Rupture_Disc__c.object-meta.xml
<CustomObject>
    <label>Rupture Disc</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rupture Disc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rupture Discs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rupture_Disc__c/fields/Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Discountable_Price__c</fullName>
    <label>Discountable Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/fields/Non_Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_Price__c</fullName>
    <label>Non Discountable Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Rupture Discs</relationshipLabel>
    <relationshipName>Rupture_Discs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/WasteGasBurner__c.object-meta.xml
<CustomObject>
    <label>WasteGasBurner</label>
    <nameField>
        <displayFormat>WGB-{0000}</displayFormat>
        <label>WasteGasBurner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WasteGasBurners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteGasBurner__c/fields/Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Discountable_Price__c</fullName>
    <label>Discountable Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Non_Discountable_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_Price__c</fullName>
    <label>Non Discountable Price</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>WasteGasBurners</relationshipLabel>
    <relationshipName>WasteGasBurners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>2&quot; (50mm)</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3&quot; (80mm)</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4&quot; (100mm)</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6&quot; (150mm)</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>8&quot; (200mm)</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10&quot; (250mm)</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12&quot; (300mm)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/customQuoteLineController.cls
public with sharing class customQuoteLineController {
    public id quoteId {set;get;} 
    public List<quoteLineWrapper> quoteLineList {get; set;}
    public SBQQ__Quote__c quote {set;get;}
    public List<SBQQ__QuoteLine__c > quoteLines {set;get;}
    public customQuoteLineController(ApexPages.StandardController controller) {
        quoteId=ApexPages.currentPage().getParameters().get('id');
        quoteLines=new List<SBQQ__QuoteLine__c >();
        quoteLines=[SELECT Id,SBQQ__Quote__c,Name,SBQQ__Product__c,SBQQ__Discount__c,SBQQ__ProductName__c,SBQQ__ProductCode__c,SBQQ__Quantity__c,LastModifiedDate FROM SBQQ__QuoteLine__c  WHERE SBQQ__Quote__c = :quoteId order by LastModifiedDate];
        quoteLineList=new List<quoteLineWrapper>();
        System.debug(quoteLines);
        // INSERT TRY/CATCH AROUND DML, IF POSSIBLE AVOID DML IN LOOPS
        for (SBQQ__QuoteLine__c q:quoteLines ) {
          id qID=q.Id;
          String query='';
          string sObject_name='';
          query='SELECT Id,Name,Discountable_Price__c,Non_Discountable_Price__c,Size__c,Part_Number__c';
          if(q.SBQQ__ProductCode__c=='BGR')
              sObject_name='BGR__c';
          else if (q.SBQQ__ProductCode__c=='RD')
              sObject_name='Rupture_Disc__c';
          else if(q.SBQQ__ProductCode__c=='RLFVLV')
              sObject_name='Relief_Valve__c';
           else if(q.SBQQ__ProductCode__c=='FlameProducts')
               sObject_name='Flame_Product__c';
             else if(q.SBQQ__ProductCode__c=='WGB')
              sObject_name='WasteGasBurner__c';
             else if(q.SBQQ__ProductCode__c=='HLD')
              sObject_name='Holders__c';            
          //  This 'else' statement will cause issues if the quote has orphaned quote line items, or quote line items from another configurator
          /*else
              sObject_name='Rupture_Disc__c';
           */ 
          query=query+' FROM '+sObject_name+' WHERE Quote_Line__c=:qID';
			
          try {
            SObject pdRec=Database.query(query);
            quoteLineWrapper ab=new quoteLineWrapper (q,pdRec);
            //System.debug('ADSDFDSGF'+ab);
            quoteLineList.add(ab);
          } catch(Exception ex) {
            System.debug(ex.getLineNumber() + ': ' + ex.getMessage());
            System.debug('Prodcut: '+ q.SBQQ__ProductCode__c);
            System.debug('QuoteLine ID: '+ qID);
            System.debug('QuoteLine: ' + q);
            System.debug('Query: '+ query);
          }
        }
        //System.debug('FGFHGJ'+quoteLineList);
    }
    public class quoteLineWrapper {
        public SBQQ__QuoteLine__c ql {set;get;}
        public SObject rD {set;get;}
         public quoteLineWrapper(SBQQ__QuoteLine__c p,SObject rD) {
            this.ql = p;
            this.rD=rD;
        }
    }
    public pageReference deleteQuoteLine() {
        return null;
    }
    public pageReference addProduct() {

        PageReference pageRef = new PageReference('/apex/customReOrderScreen?qId='+quoteId);
        pageRef.setRedirect(true);
        return pageRef;
    }
    public pageReference goBack() {

        PageReference pageRef = new PageReference('/'+quoteId);
        pageRef.setRedirect(true);
        return pageRef;
    }

}