force-app/main/default/objects/BGR__c/BGR__c.object-meta.xml
<CustomObject>
    <label>BGR</label>
    <nameField>
        <displayFormat>BGR-{0000}</displayFormat>
        <label>Blanket Gas Regulator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BGR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR__c/fields/Body_Material__c.field-meta.xml
<CustomField>
    <fullName>Body_Material__c</fullName>
    <label>Body Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <default>true</default>
                <label>316 SS</label>
            </value>
            <value>
                <fullName>Aluminium</fullName>
                <isActive>false</isActive>
                <label>Aluminium</label>
            </value>
            <value>
                <fullName>Metal</fullName>
                <isActive>false</isActive>
                <label>Metal</label>
            </value>
            <value>
                <fullName>Steel</fullName>
                <isActive>false</isActive>
                <label>Steel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Flame_Product__c/Flame_Product__c.object-meta.xml
<CustomObject>
    <label>Flame Product</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flame Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flame Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flame_Product__c/fields/Body_Material__c.field-meta.xml
<CustomField>
    <fullName>Body_Material__c</fullName>
    <label>Body Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FLMutilityTest.cls
@isTest
public class FLMutilityTest {
    
    @isTest
    static void testmethod1() {

        Test.startTest();
        
      //  FLMutility.FLMutility();
        map<string,string> myMap1 =new map<string,string>();
        string str='BGR__c';
        myMap1.put('key',str);
     //   FLMutility.getAllPicklistOptions(myMap1);
        FLMutility.getInstance();
        FLMutility.getObjectFields(str);
        Map<String, Schema.SObjectField> FLMFieldMap;
        FLMFieldMap=FLMutility.getSobjectFieldsMap(Flame_Product__c.SObjectType);
       
        Map<String,String> FLMMasterBMPicklists;
        
        FLMMasterBMPicklists=FLMutility.getPicklistLabelByValue(Flame_Product__c.SObjectType,'Body_Material__c');
            
            
        Test.stopTest();
   }
}