force-app/main/default/objects/cdcpc__SizingRequest__c/cdcpc__SizingRequest__c.object-meta.xml
<CustomObject>
    <label>Sizing Requests</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Sizing Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sizing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Is_Ready_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Is_Ready_for_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ready for Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Processed_to_quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Processed_to_quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CC - This checkbox will represent this sizing request having been successfully processed into a Salesforce CPQ Quote record.</description>
    <label>Processed to quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__ProjectName__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__ProjectName__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Sizing_Request_to_Quote__mdt/Sizing_Request_to_Quote__mdt.object-meta.xml
<CustomObject>
    <description>CC - Will hold data to change user assigned to task created from Sizing Request -&gt; Salesforce CPQ Quote creation flow.</description>
    <label>Sizing Request to Quote</label>
    <pluralLabel>Sizing Request to Quotes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sizing_Request_to_Quote__mdt/fields/Days_to_delete__c.field-meta.xml
<CustomField>
    <fullName>Days_to_delete__c</fullName>
    <defaultValue>14</defaultValue>
    <description>CC - days to delete numerical value for SizingRequestToDeleteBatch</description>
    <inlineHelpText>Set a value for dormant sizing request records to be deleted.</inlineHelpText>
    <label>Days to delete</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SizingRequestDeleteBatch.cls
global with sharing class SizingRequestDeleteBatch implements Database.Batchable<sObject>, Schedulable{

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('SizingRequestDeleteBatch start');
        Sizing_Request_to_Quote__mdt daysToDelete = Sizing_Request_to_Quote__mdt.getInstance('config');
        Datetime targetDate = DateTime.now() - daysToDelete.Days_to_delete__c;
        String query;
        if(Test.isRunningTest()){
            query = 'SELECT Id FROM cdcpc__SizingRequest__c WHERE cdcpc__Is_Ready_for_Quote__c = false AND cdcpc__Processed_to_quote__c = false AND cdcpc__ProjectName__c = \'test sizing request to delete\'';
        } else {
            query = 'SELECT Id FROM cdcpc__SizingRequest__c WHERE cdcpc__Is_Ready_for_Quote__c = false AND cdcpc__Processed_to_quote__c = false AND LastModifiedDate < :targetDate';
        }        
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<cdcpc__SizingRequest__c> sizingRequestsToDeleteList) {
            runDelete(sizingRequestsToDeleteList, true);
    }

    global void finish(Database.BatchableContext BC){
        System.debug('SizingRequestDeleteBatch finished');
    }

    /** UTILITY METHODS START **/
    private void runDelete(List<sObject> listToDelete, Boolean continueOnError){
        Database.DeleteResult[] drList = Database.delete(listToDelete, continueOnError);
        for (Database.DeleteResult dr : drList) {
            if (dr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully deleted ID: ' + dr.getId());
            }
            else {
                // Operation failed, so get all errors                
                for(Database.Error err : dr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug('fields that affected this error: ' + err.getFields());
                }
            }
        }
    }

    /** SCHEDULABLE METHODS START **/
    global void execute(SchedulableContext sc) {
        SizingRequestDeleteBatch sr2d = new SizingRequestDeleteBatch();
        database.executebatch(sr2d);
    }
}