force-app/main/default/objects/Holder_Drawings__c/Holder_Drawings__c.object-meta.xml
<CustomObject>
    <label>Holder Drawings</label>
    <nameField>
        <label>Holder Drawings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Drawings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Drawings__c/fields/Dim_A__c.field-meta.xml
<CustomField>
    <fullName>Dim_A__c</fullName>
    <label>Dim A</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/Dim_B__c.field-meta.xml
<CustomField>
    <fullName>Dim_B__c</fullName>
    <label>Dim B</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/Drawing_ID_Override__c.field-meta.xml
<CustomField>
    <fullName>Drawing_ID_Override__c</fullName>
    <label>Drawing ID Override</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/Drawing_Number__c.field-meta.xml
<CustomField>
    <fullName>Drawing_Number__c</fullName>
    <label>Drawing Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/HIC__c.field-meta.xml
<CustomField>
    <fullName>HIC__c</fullName>
    <label>HIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/HOC__c.field-meta.xml
<CustomField>
    <fullName>HOC__c</fullName>
    <label>HOC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/Holders__c.field-meta.xml
<CustomField>
    <fullName>Holders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Holders</label>
    <referenceTo>Holders__c</referenceTo>
    <relationshipLabel>Holder Drawings</relationshipLabel>
    <relationshipName>Holder_Drawings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings__c/fields/SizeClassDesc__c.field-meta.xml
<CustomField>
    <fullName>SizeClassDesc__c</fullName>
    <label>SizeClassDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/Holder_Drawings_Detail__c.object-meta.xml
<CustomObject>
    <label>Holder Drawings Detail</label>
    <nameField>
        <label>Holder Drawings Detail</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Drawings Detail</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/Drawing_Type__c.field-meta.xml
<CustomField>
    <fullName>Drawing_Type__c</fullName>
    <label>Drawing Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/DWGNO__c.field-meta.xml
<CustomField>
    <fullName>DWGNO__c</fullName>
    <label>DWGNO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/HIC__c.field-meta.xml
<CustomField>
    <fullName>HIC__c</fullName>
    <label>HIC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <label>Revision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Detail__c/fields/SizeClassDesc__c.field-meta.xml
<CustomField>
    <fullName>SizeClassDesc__c</fullName>
    <label>SizeClassDesc</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Drawings_Translation__c/Holder_Drawings_Translation__c.object-meta.xml
<CustomObject>
    <label>Holder Drawings Translation</label>
    <nameField>
        <label>Holder Drawings Translation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Drawings Translation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Drawings_Translation__c/fields/Drawing_Type__c.field-meta.xml
<CustomField>
    <fullName>Drawing_Type__c</fullName>
    <label>Drawing Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/Holder_Outputs__c.object-meta.xml
<CustomObject>
    <label>Holder Outputs</label>
    <nameField>
        <label>Holder Output Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Holder Outputs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holder_Outputs__c/fields/OA__c.field-meta.xml
<CustomField>
    <fullName>OA__c</fullName>
    <label>OA</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/fields/OA_Overridden__c.field-meta.xml
<CustomField>
    <fullName>OA_Overridden__c</fullName>
    <label>OA Overridden</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/fields/OB__c.field-meta.xml
<CustomField>
    <fullName>OB__c</fullName>
    <label>OB</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/fields/OB_Overridden__c.field-meta.xml
<CustomField>
    <fullName>OB_Overridden__c</fullName>
    <label>OB Overridden</label>
    <length>15000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/fields/OW__c.field-meta.xml
<CustomField>
    <fullName>OW__c</fullName>
    <label>OW</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/fields/OW_Overridden__c.field-meta.xml
<CustomField>
    <fullName>OW_Overridden__c</fullName>
    <label>OW Overridden</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Holder_Outputs__c/fields/ReferenceId__c.field-meta.xml
<CustomField>
    <fullName>ReferenceId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Holders</label>
    <referenceTo>Holders__c</referenceTo>
    <relationshipLabel>Holder Outputs</relationshipLabel>
    <relationshipName>Holder_Outputs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/Bolting_Class__c.field-meta.xml
<CustomField>
    <fullName>Bolting_Class__c</fullName>
    <label>Bolting Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>LaMOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holders__c/fields/DWGNO__c.field-meta.xml
<CustomField>
    <fullName>DWGNO__c</fullName>
    <label>DWGNO</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Holder_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Holder_Product_Code__c</fullName>
    <label>Holder Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Inlet_Connection__c.field-meta.xml
<CustomField>
    <fullName>Inlet_Connection__c</fullName>
    <label>Inlet Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Inlet_Option__c.field-meta.xml
<CustomField>
    <fullName>Inlet_Option__c</fullName>
    <label>Inlet Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Mid_Flange_Option__c.field-meta.xml
<CustomField>
    <fullName>Mid_Flange_Option__c</fullName>
    <label>Mid Flange Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Outlet_Connection__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Connection__c</fullName>
    <label>Outlet Connection</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Outlet_Option2__c.field-meta.xml
<CustomField>
    <fullName>Outlet_Option2__c</fullName>
    <label>Outlet Option(COOUT)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Quote_Descriptions_Override__c.field-meta.xml
<CustomField>
    <fullName>Quote_Descriptions_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Descriptions Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Size2__c.field-meta.xml
<CustomField>
    <fullName>Size2__c</fullName>
    <label>Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/QuoteLine_Mass_Update__c.object-meta.xml
<CustomObject>
    <label>QuoteLine Mass Update</label>
    <nameField>
        <displayFormat>MU-{00000}</displayFormat>
        <label>QuoteLine Mass Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteLine Mass Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimB__c.field-meta.xml
<CustomField>
    <fullName>DimB__c</fullName>
    <label>DimB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimC__c.field-meta.xml
<CustomField>
    <fullName>DimC__c</fullName>
    <label>DimC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimF__c.field-meta.xml
<CustomField>
    <fullName>DimF__c</fullName>
    <label>DimF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Drawing_ID__c.field-meta.xml
<CustomField>
    <fullName>Drawing_ID__c</fullName>
    <label>Drawing ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>SBQQ__Quote__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimB__c.field-meta.xml
<CustomField>
    <fullName>DimB__c</fullName>
    <label>DimB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimC__c.field-meta.xml
<CustomField>
    <fullName>DimC__c</fullName>
    <label>DimC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimF__c.field-meta.xml
<CustomField>
    <fullName>DimF__c</fullName>
    <label>DimF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DrawingID__c.field-meta.xml
<CustomField>
    <fullName>DrawingID__c</fullName>
    <description>This field will have the name of static resource</description>
    <label>DrawingID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigHolderUtilityBatch.cls
/**********************************************************************************************************
* @Name         ConfigHolderUtilityBatch 
* @Author       Ashim Kumar Sahoo <ashim.kumar@apexit.com>
* @Date         10/16/2020
* @Description  This class contains all utility methods related to fetching and updating of description   
*				and diagram data for Holders                               
************************************************************************************************************/
public with sharing class ConfigHolderUtilityBatch {
    
    /*******************************************************************************************************
* @Description  This method fetches description records based on the Holder Inputs 
* 				from Description Translation and Detail, and upsert the values in Holder_Description_Detail__c 
* 				against the respective Holder__c record.
* @Param 1		Id - quoteLineId
* @Param 2		Holders__c - conHolder
* @Return       String - The final description of Holder records which has concatenated values 
* 				for OA, OB & OW
* @Example     
* ConfigHolderUtilityBatch.fetchAndUpdateHolderDesc('QUOTELINE_ID', 'HOLDERS')
*********************************************************************************************************/ 
    public static Result fetchAndUpdateHolderDesc(Id quoteLineId, Holders__c conHolder) {
        
        Map<String, String> holderInputs;
        List<Holder_Outputs__c> hldOutputs;
        Holder_Outputs__c hldOutput;
        Holder_Description_Detail__c descRec;
        Result resDesc;
        String OA, OB, OW, strquoteDes;
        Result resData = new Result();
        
        List<SBQQ__QuoteLine__c> qlDet = [SELECT Id, Name FROM SBQQ__QuoteLine__c WHERE Id = :quoteLineId];
        
        try {
            
            holderInputs = ConfigHolderUtility.holderInputs(conHolder);
            //genUtil = generic.getUtilityInstance(prodCode, quoteLine.Id);
            
            hldOutputs = [SELECT OA__c, OA_Overridden__c, OB__c, OB_Overridden__c, 
                          OW__c, OW_Overridden__c 
                          FROM Holder_Outputs__c 
                          WHERE ReferenceId__c = :conHolder.Id];
            if(hldOutputs.size() > 0) {
                
                strquoteDes = '';
                OA = '';
                OB = '';
                OW = '';
                hldOutput = hldOutputs[0];
                
                resDesc = ConfigHolderUtility.getHolderDescription(holderInputs);
                if(resDesc.bResult) {
                    for(sObject sobj:resDesc.objResultList) {
                        
                        descRec = new Holder_Description_Detail__c ();
                        descRec = (Holder_Description_Detail__c ) sobj;
                        if (descRec.Attribute__c.startsWith('OA'))
                            OA += String.isNotBlank(descRec.Text__c)?descRec.Text__c+'\n':'';
                        else if (descRec.Attribute__c.startsWith('OB'))
                            OB += String.isNotBlank(descRec.Text__c)?descRec.Text__c+'\n':'';
                        else if (descRec.Attribute__c.startsWith('OW'))
                            OW += String.isNotBlank(descRec.Text__c)?descRec.Text__c+'\n':'';
                    }
                    hldOutput.put('OA__c', OA);
                    hldOutput.put('OB__c', OB);
                    hldOutput.put('OW__c', OW);
                    
                    if(conHolder.Quote_Descriptions_Override__c == false) {
                        hldOutput.put('OA_Overridden__c', OA);
                        hldOutput.put('OB_Overridden__c', OB);
                        hldOutput.put('OW_Overridden__c', OW);
                    }
                }
                update hldOutput;
                
                if(String.isNotBlank(hldOutput.OA_Overridden__c)){
                    strquoteDes += hldOutput.OA_Overridden__c +'\n';
                }
                if(String.isNotBlank(hldOutput.OB_Overridden__c)){
                    strquoteDes += hldOutput.OB_Overridden__c+'\n';
                }
                if(String.isNotBlank(hldOutput.OW_Overridden__c)){
                    strquoteDes += hldOutput.OW_Overridden__c+'\n' ;
                }
                strquoteDes = strquoteDes.replace('\\n', '\n');
                strquoteDes = strquoteDes.replace('\n', '<br/>');
                resData.strRetValue = strquoteDes;
            	resData.bResult = true;
            }
        } catch (Exception e) {
            
            resData.bResult = false;
            resData.strErrorMessage = 'Error:'+ qlDet[0].Name +' - '+e.getMessage();
        }
        
        return resData;
        //return strquoteDes;
    }
    
    /*******************************************************************************************************
    * @Description  This method fetches drawing data records based on the Holder Inputs 
    * 				from Drawing Translation and Detail, and upsert the values in Holder_Drawings__c against
    * 				the respective Holder__c record.
    * @Param 1		Holders__c - conHolder
    * @Return       Result - This a a wrapper class returning List<sObject> objResultList and Boolean bResult  
    * 				Boolean bResult: true or false (false incase of any errors and true for success)
    * 				List<sObject> objResultList: List<Holder_Description_Detail__c> Basically the list 
    * 				of Holder Drawings records.
    * @Example     
    * ConfigHolderUtilityBatch.fetchAndUpdateHolderDiagram('HOLDERS')
    *********************************************************************************************************/ 
    public static Result fetchAndUpdateHolderDiagram(Holders__c conHolder) {
        
        Result resDiaData = new Result();
        Map<String, String> mapDia = new Map<String, String>();
        
        mapDia.put('Entity', conHolder.Brand__c);
        mapDia.put('HPTC', conHolder.Holder_Product_Code__c);
        mapDia.put('SZC', conHolder.Size2__c);
        mapDia.put('HCLASS', conHolder.Bolting_Class__c);
        mapDia.put('HIC', conHolder.Inlet_Connection__c);
        mapDia.put('HOC', conHolder.Outlet_Connection__c);
        mapDia.put('COIN', conHolder.Inlet_Option__c);
        mapDia.put('COOUT', conHolder.Outlet_Option2__c);
        mapDia.put('COMF', conHolder.Mid_Flange_Option__c);
        
        List<String> selectCols = new List<String>();
        selectCols.add('Drawing_Type__c');
        selectCols.add('DrawingID__c');
        selectCols.add('DimA__c');
        selectCols.add('DimB__c');
        selectCols.add('DimC__c');
        selectCols.add('DimD__c');
        selectCols.add('DimE__c');
        selectCols.add('DimF__c');
        selectCols.add('HIC__c');
        selectCols.add('HOC__c');
        selectCols.add('SizeClassDesc__c');
        selectCols.add('DWGNO__c');
        selectCols.add('Revision__c');
        
        resDiaData = ConfigHolderUtility.getDataFromTranslationObj('Drawing_Type__c', 'Holder_Drawings_Translation__c', 'Holder_Drawings_Detail__c', mapDia, selectCols, null);
        Result resD = new Result();
        List<Holder_Drawings__c> holderDiagramList = [SELECT Drawing_Number__c,Drawing_ID__c,Drawing_Info__c,Drawing_ID_Override__c,
                                                      Dim_A__c,Dim_A_Override__c,Dim_B__c,Dim_B_Override__c,Dim_C__c,Dim_C_Override__c,
                                                      Dim_D__c,Dim_D_Override__c,Dim_E__c,Dim_E_Override__c,Dim_F__c,Dim_F_Override__c, 
                                                      IINO_DWGNO__c, JHOOK_IINO_DWGNO__c, Submittal_Drawing_DWGNO__c, Revision__c, 
                                                      Holders__c, Holders__r.Quote_Line__c, Holders__r.Quote_Line__r.Name,
                                                      Holders__r.Quote_Line__r.Drawing_to_be_created_outside_of_Config__c  
                                                      FROM Holder_Drawings__c 
                                                      WHERE Holders__c = :conHolder.id];
        Holder_Drawings__c holderD = new Holder_Drawings__c();
        
        //delete the older records
        //delete holderDiagramList;
        
        if(holderDiagramList.size()>0){
            
            holderD = holderDiagramList[0];
            
        } else {
            
            holderD.Holders__c = conHolder.Id;
        }
        Integer submittalDrawingFound = 0;
        List<Holder_Drawings__c> holderDiaList = new List<Holder_Drawings__c>();
        
        if(!conHolder.Diagram_Override__c) {
            
            if(resDiaData.bResult) {
                for (sObject sObj: resDiaData.objResultList) {
                    if ((string) sObj.get('Drawing_Type__c') == 'Submittal Drawing') {
                        
                        holderD.Drawing_ID__c = (string) sObj.get('DrawingID__c');
                        holderD.Submittal_Drawing_DWGNO__c = (string) sObj.get('DWGNO__c');
                        holderD.Drawing_ID_Override__c = (string) sObj.get('DrawingID__c');
                        holderD.Revision__c = (string) sObj.get('Revision__c');  
                        
                        holderD.Dim_A__c = (string) sObj.get('DimA__c');
                        holderD.Dim_B__c = (string) sObj.get('DimB__c');
                        holderD.Dim_C__c = (string) sObj.get('DimC__c');
                        holderD.Dim_D__c = (string) sObj.get('DimD__c');
                        holderD.Dim_E__c = (string) sObj.get('DimE__c');
                        holderD.Dim_F__c = (string) sObj.get('DimF__c');
                        
                        holderD.HIC__c = (string) sObj.get('HIC__c');
                        holderD.HOC__c = (string) sObj.get('HOC__c');
                        holderD.SizeClassDesc__c = (string) sObj.get('SizeClassDesc__c');
                        
                        if(conHolder.Diagram_Override__c == false) {
                            
                            holderD.Dim_A_Override__c = (string) sObj.get('DimA__c');
                            holderD.Dim_B_Override__c = (string) sObj.get('DimB__c');
                            holderD.Dim_C_Override__c = (string) sObj.get('DimC__c');
                            holderD.Dim_D_Override__c = (string) sObj.get('DimD__c');
                            holderD.Dim_E_Override__c = (string) sObj.get('DimE__c');
                            holderD.Dim_F_Override__c = (string) sObj.get('DimF__c');
                        }
                        
                        submittalDrawingFound = 1;
                    }
                    if ((string) sObj.get('Drawing_Type__c') == 'J-Hook IINO') {
                        
                        holderD.JHOOK_IINO_DWGNO__c = (string) sObj.get('DWGNO__c');
                        holderD.J_Hook_IINO__c=(string) sObj.get('DrawingID__c');
                    }
                    if ((string) sObj.get('Drawing_Type__c') == 'IINO'){
                        
                        holderD.IINO_DWGNO__c = (string) sObj.get('DWGNO__c');
                        holderD.IINO__c=(string) sObj.get('DrawingID__c');
                    }
                }
            }
            
            //If no drawing found then set the default drawing for "submittal drawing" to 9999
            if(submittalDrawingFound == 0 || holderD.Drawing_ID__c == null) {
                
                holderD.Drawing_ID__c = Label.Default_Submittal_Drawing;
                holderD.Drawing_ID_Override__c = Label.Default_Submittal_Drawing;
            }
        }
        
        try {
            holderDiaList.add(holderD);
            upsert holderD;
            
            system.debug('submittalDrawingFound:'+submittalDrawingFound);            
            if(holderD.Submittal_Drawing_DWGNO__c != null) {
                
                conHolder.DWGNO__c = holderD.Submittal_Drawing_DWGNO__c;
            }
            update conHolder;
            
            resD.objResultList = holderDiaList;
            resD.bResult = true;
            
        } catch (Exception e) {
            
            resD.bResult = false;
            resD.strErrorMessage = 'Error:'+ holderD.Holders__r.Quote_Line__r.Name +' - '+e.getMessage();
        }
        
        //resDiaData.objResultList.add(holderD);
        //resDiaData.bResult = true;        
        return resD;
    }
    
    /*******************************************************************************************************
    * @Description  This method updates the QL records especially the description, 
    * 				and the diagram parameters like Drawing ID, Dim A to Dim F.
    * 				This method is an future method which is invoked at last after update of description and diagram details.
    * @Param 1		String - quoteLineDetailsJSON (List of quote line records which is serialised for conerting to a String)
    * @Return       void
    * @Example     
    * ConfigHolderUtilityBatch.updateQuoteLineDesc('LIST_OF_QUOTE_LINE_AS_JSON')
    *********************************************************************************************************/
    @future(callout = true)
    public static void updateQuoteLineDesc(String quoteLineDetailsJSON) {
        
        if(quoteLineDetailsJSON != null) {
           
            List<SBQQ__QuoteLine__c> quoteLines = (List<SBQQ__QuoteLine__c>)System.JSON.deserialize(quoteLineDetailsJSON, List<SBQQ__QuoteLine__c>.class);
            
            if(quoteLines.size() > 0) {
                
                update quoteLines;  
            }
        }
    }
    
    /*********************************************************************************************************
    * @Description  This method updates the Holder specific quote line description and drawing based on inputs
    * 				
    * @Param 1		Holders__c - hld 
    * @Return       Map<String, Object>
    * 				There are 2 keys associated in the response:
    * 					QUOTE_LINE: Map<Id, SBQQ__QuoteLine__c>
    * 					ERR_DETAILS: String
    * @Example     
    * ConfigHolderUtilityBatch.updateHolderRecords('HOLDER_RECORD')
    *********************************************************************************************************/
    public static Map<String, Object> updateHolderRecords(Holders__c hld) {
        
        SBQQ__QuoteLine__c quoteLineObj;
        Map<Id, SBQQ__QuoteLine__c> quoteLineDetails = new Map<Id, SBQQ__QuoteLine__c>();
        Holders__c conHolder;
        String quoteDesc;
        String errorDetails = '';
        
        //update desc
        conHolder = DataSelectorWizard.getHolderProductRecord(hld.Quote_Line__c);
        Result quoteDescRes = ConfigHolderUtilityBatch.fetchAndUpdateHolderDesc(hld.Quote_Line__c, conHolder);
        
        if(quoteDescRes != null && quoteDescRes.bResult) {
            
            quoteDesc = quoteDescRes.strRetValue;
            if(quoteLineDetails.get(hld.Quote_Line__c) == null) {
                
                quoteLineDetails.put(hld.Quote_Line__c, new SBQQ__QuoteLine__c());
            }
            quoteLineObj = quoteLineDetails.get(hld.Quote_Line__c);
            quoteLineObj.Id = hld.Quote_Line__c;
            quoteLineObj.SBQQ__Description__c = quoteDesc;
            quoteLineDetails.put(hld.Quote_Line__c, quoteLineObj);
            
        } else {
            
            errorDetails += quoteDescRes.strErrorMessage + '\n';
        }
        
        //update image
        Result diagramRes = ConfigHolderUtilityBatch.fetchAndUpdateHolderDiagram(conHolder);
        
        if(diagramRes != null && diagramRes.bResult) {
            
            List<Holder_Drawings__c> hldDiagrams = (List<Holder_Drawings__c>) diagramRes.objResultList;
            for(Holder_Drawings__c hldDiagram: hldDiagrams) {
                
                if(hldDiagram.Submittal_Drawing_DWGNO__c != null || Test.isRunningTest()) {
                    
                    if(quoteLineDetails.get(hldDiagram.Holders__r.Quote_Line__c) == null) {
                        
                        quoteLineDetails.put(hldDiagram.Holders__r.Quote_Line__c, new SBQQ__QuoteLine__c());
                    }
                    quoteLineObj = quoteLineDetails.get(hldDiagram.Holders__r.Quote_Line__c);
                    
                    if(quoteLineObj.Id == null) {
                        
                        quoteLineObj.Id = hldDiagram.Holders__r.Quote_Line__c;
                    }
                    
                    if(hldDiagram.Holders__r.Quote_Line__r.Drawing_to_be_created_outside_of_Config__c == false) {
                        
                        quoteLineObj.DrawingID__c = hldDiagram.Drawing_ID__c;
                        quoteLineObj.DimA__c  = hldDiagram.Dim_A__c;
                        quoteLineObj.DimB__c  = hldDiagram.Dim_B__c;
                        quoteLineObj.DimC__c  = hldDiagram.Dim_C__c;
                        quoteLineObj.DimD__c  = hldDiagram.Dim_D__c;
                        quoteLineObj.DimE__c  = hldDiagram.Dim_E__c;
                        quoteLineObj.DimF__c  = hldDiagram.Dim_F__c;
                    }
                    
                    system.debug('ASHIM - '+hldDiagram.Submittal_Drawing_DWGNO__c);
                    quoteLineDetails.put(hldDiagram.Holders__r.Quote_Line__c, quoteLineObj);
                }
            }
        } else {
            
            errorDetails += quoteDescRes.strErrorMessage + '\n';
        }
        
        Map<String, Object> response = new Map<String, Object>();
        response.put('QUOTE_LINE', quoteLineDetails);
        response.put('ERROR_DETAILS', errorDetails);
        
        return response;
    }
    
    @future(callout = true) 
    public static void updateQLines() {
        
        disableCpqTriggers.disableCPQ();
        Map<Id, SBQQ__QuoteLine__c> quotelineMap = new Map<Id, SBQQ__QuoteLine__c>();
        List<QuoteLine_Mass_Update__c> records = [SELECT Id, Quote_Line__c, QuoteLine_Description__c, Drawing_ID__c, DimA__c, DimB__c, DimC__c, DimD__c, DimE__c, DimF__c FROM QuoteLine_Mass_Update__c WHERE Trigger_QL_Update__c = false ORDER BY Id DESC];
        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        SBQQ__QuoteLine__c quoteLine;
        for(QuoteLine_Mass_Update__c quoteLinesMassRecord: records) {
            
            quoteLine = new SBQQ__QuoteLine__c();
            quoteLine.Id  = quoteLinesMassRecord.Quote_Line__c;
            quoteLine.DrawingID__c = quoteLinesMassRecord.Drawing_ID__c;
            quoteLine.DimA__c = quoteLinesMassRecord.DimA__c;
            quoteLine.DimB__c = quoteLinesMassRecord.DimB__c;
            quoteLine.DimC__c = quoteLinesMassRecord.DimC__c;
            quoteLine.DimD__c = quoteLinesMassRecord.DimD__c;
            quoteLine.DimE__c = quoteLinesMassRecord.DimE__c;
            quoteLine.DimF__c = quoteLinesMassRecord.DimF__c;
            quoteLine.SBQQ__Description__c = quoteLinesMassRecord.QuoteLine_Description__c ;
            quotelineMap.put(quoteLine.Id, quoteLine);
            //quoteLines.add(quoteLine);
        }
        if(quotelineMap != null) {
            
            update quotelineMap.values();
            delete records;
        }
    }
}