force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>A-{0000000}</displayFormat>
    <label>Account Number*</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Freight_Information__c/Freight_Information__c.object-meta.xml
<CustomObject>
    <label>Freight Information</label>
    <nameField>
        <label>Freight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Freight Information</relationshipLabel>
    <relationshipName>Freight_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Freight_Information__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_Information__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Freight_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_Information__c/fields/Freight_Contact_Email__c.field-meta.xml
<CustomField>
    <fullName>Freight_Contact_Email__c</fullName>
    <label>Freight Contact Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Freight_Information__c/fields/Freight_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Freight_Contact_Phone__c</fullName>
    <label>Freight Contact Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Log__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Log__c</fullName>
    <label>Change Order Log</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Information__c.field-meta.xml
<CustomField>
    <fullName>Freight_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Freight Information</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Freight_Information__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Freight_Information__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Shipping_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Freight_Information__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <defaultValue>&quot;Primary&quot;</defaultValue>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/globalValueSets/Freight_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Freight Entities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IFS_ConstructOrderReqTest.cls
@isTest
private class IFS_ConstructOrderReqTest{            
   static testMethod void generateReq(){
        
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1]; 
        SBQQ__QuoteLine__c oQuoteLine;
        for(SBQQ__QuoteLine__c oTempQuoteLine:[Select Id From SBQQ__QuoteLine__c limit 1]){
            oQuoteLine = oTempQuoteLine;
        }
        Test.startTest();
        if(oQuoteLine!=null){
            oQuoteLine.Line_Status__c='Blocked';
            update oQuoteLine;
        }
        
        Freight_Information__c oFreightInformation = new Freight_Information__c();
        oFreightInformation.Account__c = accLst.Id;
        oFreightInformation.Account_Number__c = '55555555';
        oFreightInformation.Bill_To__c = 'Receiver';
        oFreightInformation.Entity__c = 'UPS';
        oFreightInformation.Name ='freight info';
        oFreightInformation.Freight_Contact_Email__c ='test@test.com';
        oFreightInformation.Freight_Contact_Phone__c ='555-555-5555';
        insert oFreightInformation;
        
        quote.Freight_Information__c = oFreightInformation.Id;
        quote.Change_Order_Log__c='Charges';
        update quote;
        
        IFS_ConstructOrderReq.generateReq(quote.id);
        Test.stopTest();
    }
    
    static testMethod void generateReq2(){
        
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1]; 
        SBQQ__QuoteLine__c oQuoteLine;
        for(SBQQ__QuoteLine__c oTempQuoteLine:[Select Id From SBQQ__QuoteLine__c limit 1]){
            oQuoteLine = oTempQuoteLine;
        }
        Test.startTest();
        if(oQuoteLine!=null){
            oQuoteLine.Line_Status__c='Blocked';
            update oQuoteLine;
        }
        
        Freight_Information__c oFreightInformation = new Freight_Information__c();
        oFreightInformation.Account__c = accLst.Id;
        oFreightInformation.Account_Number__c = '55555555';
        oFreightInformation.Bill_To__c = 'Receiver';
        oFreightInformation.Entity__c = 'FedEx';
        oFreightInformation.Name ='freight info';
        oFreightInformation.Freight_Contact_Email__c ='test@test.com';
        oFreightInformation.Freight_Contact_Phone__c ='555-555-5555';
        insert oFreightInformation;
        
        quote.Freight_Information__c = oFreightInformation.Id;
        update quote;
        
        IFS_ConstructOrderReq.generateReq(quote.id);
        Test.stopTest();
    }
}