force-app/main/default/objects/Account/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <displayFormat>A-{0000000}</displayFormat>
    <label>Account Number*</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Freight_Information__c/Freight_Information__c.object-meta.xml
<CustomObject>
    <label>Freight Information</label>
    <nameField>
        <label>Freight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Freight Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Freight_Information__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Freight Information</relationshipLabel>
    <relationshipName>Freight_Information</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Freight_Information__c/fields/Bill_To__c.field-meta.xml
<CustomField>
    <fullName>Bill_To__c</fullName>
    <label>Bill To</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Shipper</fullName>
            </value>
            <value>
                <fullName>Receiver</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Freight_Information__c/fields/Entity__c.field-meta.xml
<CustomField>
    <fullName>Entity__c</fullName>
    <label>Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Freight_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Freight_Information__c.field-meta.xml
<CustomField>
    <fullName>Freight_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Freight Information</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 OR 2</booleanFilter>
        <filterItems>
            <field>Freight_Information__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.SBQQ__Account__c</valueField>
        </filterItems>
        <filterItems>
            <field>Freight_Information__c.Account__c</field>
            <operation>equals</operation>
            <valueField>$Source.Shipping_Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Freight_Information__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Freight_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>FedEx</fullName>
    </customValue>
    <customValue>
        <fullName>UPS</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <masterLabel>Freight Entities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/IFS_ConstructCustReqTest.cls
@isTest
private class IFS_ConstructCustReqTest{         
   static testMethod void generateReq(){
        Test.startTest();
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1];
        
        Freight_Information__c oFreightInformation = new Freight_Information__c();
        oFreightInformation.Account__c = accLst.Id;
        oFreightInformation.Account_Number__c = '55555555';
        oFreightInformation.Bill_To__c = 'Receiver';
        oFreightInformation.Entity__c = 'UPS';
        oFreightInformation.Name ='freight info';
        insert oFreightInformation;
        
        quote.Freight_Information__c = oFreightInformation.Id;
        update quote;
        
        IFS_ConstructCustReq.generateReq(accLst.Id,quote.id);
        Test.stopTest();
    }
    static testMethod void generateReq2(){
        Test.startTest();
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1];
        
        Freight_Information__c oFreightInformation = new Freight_Information__c();
        oFreightInformation.Account__c = accLst.Id;
        oFreightInformation.Account_Number__c = '55555555';
        oFreightInformation.Bill_To__c = 'Receiver';
        oFreightInformation.Entity__c = 'FedEx';
        oFreightInformation.Name ='freight info';
        insert oFreightInformation;
        
        quote.Freight_Information__c = oFreightInformation.Id;
        update quote;
        
        IFS_ConstructCustReq.generateReq(accLst.Id,quote.id);
        Test.stopTest();
    }
}