force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AF1</fullName>
            </value>
            <value>
                <fullName>D01</fullName>
            </value>
            <value>
                <fullName>D02</fullName>
            </value>
            <value>
                <fullName>D03</fullName>
            </value>
            <value>
                <fullName>D04</fullName>
            </value>
            <value>
                <fullName>D05</fullName>
            </value>
            <value>
                <fullName>D06</fullName>
            </value>
            <value>
                <fullName>DDH1</fullName>
            </value>
            <value>
                <fullName>DEPC</fullName>
            </value>
            <value>
                <fullName>DHV</fullName>
            </value>
            <value>
                <fullName>DLD</fullName>
            </value>
            <value>
                <fullName>DNIH</fullName>
            </value>
            <value>
                <fullName>DOE1</fullName>
            </value>
            <value>
                <fullName>DOE2</fullName>
            </value>
            <value>
                <fullName>DOE3</fullName>
            </value>
            <value>
                <fullName>DUPS</fullName>
            </value>
            <value>
                <fullName>E0</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>EU1</fullName>
            </value>
            <value>
                <fullName>EU2</fullName>
            </value>
            <value>
                <fullName>EU3</fullName>
            </value>
            <value>
                <fullName>EU4</fullName>
            </value>
            <value>
                <fullName>FR1</fullName>
            </value>
            <value>
                <fullName>FR2</fullName>
            </value>
            <value>
                <fullName>LA1</fullName>
            </value>
            <value>
                <fullName>LA2</fullName>
            </value>
            <value>
                <fullName>LA3</fullName>
            </value>
            <value>
                <fullName>LOE1</fullName>
            </value>
            <value>
                <fullName>ME1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Assign_to_Partner__c.field-meta.xml
<CustomField>
    <fullName>Assign_to_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Assign to Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/objects/User/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Districts.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA PAC</fullName>
    </customValue>
    <customValue>
        <fullName>EAR</fullName>
    </customValue>
    <customValue>
        <fullName>ME/OCNA/SK</fullName>
    </customValue>
    <customValue>
        <fullName>UPSTREAM</fullName>
        <label>Domestic Upstream</label>
    </customValue>
    <masterLabel>Districts</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/AccountWiseLeadShareSyncTest.cls
@isTest
public class AccountWiseLeadShareSyncTest{
    @isTest
    static void unitTest(){
        Profile oProfile ;
        for(Profile p : [Select ID, Name from Profile Where Name = 'System Administrator']){
            oProfile = p;
        }
        System.debug('@Developer --> oProfile :' + oProfile);
        
        string sUserName = 'test_' + TestUtility.getRandomNumber() + '@test.com';
        string sUserName2 = 'test2_' + TestUtility.getRandomNumber() + '@test.com';
        
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        list<User> lstUsers = new list<User>();
        
        User oUser = new User();
        oUser.UserRoleId = portalRole.Id;
        oUser.UserName = sUserName;
        oUser.FirstName = 'Test-First';
        oUser.LastName = 'Test-Last';
        oUser.Alias = 'test';
        oUser.email = 'test' + TestUtility.getRandomNumber() + '@test.com';
        oUser.ProfileID = oProfile.Id;
        oUser.TimeZoneSidKey = 'America/New_York';   
        oUser.LocaleSidKey = 'en_US';
        oUser.EmailEncodingKey = 'UTF-8';
        oUser.LanguageLocaleKey = 'en_US';   
        lstUsers.add(oUser);
        
        User oUser2 = new User();
        oUser2.UserName = sUserName2;
        oUser2.FirstName = 'Test-First2';
        oUser2.LastName = 'Test-Last2';
        oUser2.Alias = 'test2';
        oUser2.email = 'test2' + TestUtility.getRandomNumber() + '@test.com';
        oUser2.ProfileID = oProfile.Id;
        oUser2.TimeZoneSidKey = 'America/New_York';   
        oUser2.LocaleSidKey = 'en_US';
        oUser2.EmailEncodingKey = 'UTF-8';
        oUser2.LanguageLocaleKey = 'en_US';   
        lstUsers.add(oUser2);
        insert lstUsers;
        
        list<Account> lstAccounts = new list<Account>();
        Account oAccount;
        Contact oContact;
        
        system.runAs(oUser){
            //string sCustomerAccountRecordTypeId = UtilityHelper.self.mapAccountRecordTypeNameWiseId.get('Customer Account').getRecordTypeId();
            oAccount = TestUtility.createPartnerAccount('Test',false);
            oAccount.Rep_Code__c='UCN1';
            oAccount.Region__c='DUPS';
            oAccount.District__c='AMERICAS';
            oAccount.External_ID__c='UCN1-DUPS-AMERICAS';
            lstAccounts.add(oAccount);
            
            Account oAccount2 = TestUtility.createPartnerAccount('Test2',false);
            oAccount2.Rep_Code__c='AK2';
            oAccount2.Region__c='D05';
            oAccount2.District__c='AMERICAS';
            oAccount2.External_ID__c='AK2-D05-AMERICAS';
            lstAccounts.add(oAccount2);
            insert lstAccounts;
            
            oAccount.IsPartner = true;
            oAccount2.IsPartner = true;
            update lstAccounts;
                    
            oContact = TestUtility.createContact('testCon',oAccount.Id,true);
            User oPartnerUser = TestUtility.createPartnerUser('',oAccount.Name,oContact.Id,true);
            //Account oAccCust = TestUtility.createAccount('Test Customer Acc', sCustomerAccountRecordTypeId, false);
            Account oAccCust = TestUtility.createCustomerAccount('Test Customer Acc',false);
            oAccCust.Rep_Code_Account__c = oAccount.Id;
            insert oAccCust;
            Lead oLead = new Lead();
            oLead.Firstname ='test lead';
            oLead.Lastname ='test lead';
            oLead.Status ='New';
            oLead.Company ='Test company';
            oLead.Assign_to_Partner__c =true;
            oLead.PartnerAccountId  = oAccount.Id;
            insert oLead;
            list<AccountTeamMember> lstAccountTeamMember = new list<AccountTeamMember>();
            AccountTeamMember oAccountTeamMember = new AccountTeamMember();
            oAccountTeamMember.AccountId = oAccount.Id;
            oAccountTeamMember.AccountAccessLevel = 'Edit';
            oAccountTeamMember.TeamMemberRole = 'Sales Rep';
            oAccountTeamMember.UserId = oPartnerUser.Id;
            lstAccountTeamMember.add(oAccountTeamMember);
            
            /*AccountTeamMember oAccountTeamMember2 = new AccountTeamMember();
            oAccountTeamMember2.AccountId = oAccount2.Id;
            oAccountTeamMember2.AccountAccessLevel = 'Edit';
            oAccountTeamMember2.TeamMemberRole = 'Sales Rep';
            oAccountTeamMember2.UserId = oUser2.Id;
            lstAccountTeamMember.add(oAccountTeamMember2);*/
            test.startTest();
            insert lstAccountTeamMember;
            test.stoptest(); 
            delete lstAccountTeamMember;
        }
    }
    
}