force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AF1</fullName>
            </value>
            <value>
                <fullName>D01</fullName>
            </value>
            <value>
                <fullName>D02</fullName>
            </value>
            <value>
                <fullName>D03</fullName>
            </value>
            <value>
                <fullName>D04</fullName>
            </value>
            <value>
                <fullName>D05</fullName>
            </value>
            <value>
                <fullName>D06</fullName>
            </value>
            <value>
                <fullName>DDH1</fullName>
            </value>
            <value>
                <fullName>DEPC</fullName>
            </value>
            <value>
                <fullName>DHV</fullName>
            </value>
            <value>
                <fullName>DLD</fullName>
            </value>
            <value>
                <fullName>DNIH</fullName>
            </value>
            <value>
                <fullName>DOE1</fullName>
            </value>
            <value>
                <fullName>DOE2</fullName>
            </value>
            <value>
                <fullName>DOE3</fullName>
            </value>
            <value>
                <fullName>DUPS</fullName>
            </value>
            <value>
                <fullName>E0</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>EU1</fullName>
            </value>
            <value>
                <fullName>EU2</fullName>
            </value>
            <value>
                <fullName>EU3</fullName>
            </value>
            <value>
                <fullName>EU4</fullName>
            </value>
            <value>
                <fullName>FR1</fullName>
            </value>
            <value>
                <fullName>FR2</fullName>
            </value>
            <value>
                <fullName>LA1</fullName>
            </value>
            <value>
                <fullName>LA2</fullName>
            </value>
            <value>
                <fullName>LA3</fullName>
            </value>
            <value>
                <fullName>LOE1</fullName>
            </value>
            <value>
                <fullName>ME1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <label>Division</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EPC_Firm_Involved__c.field-meta.xml
<CustomField>
    <fullName>EPC_Firm_Involved__c</fullName>
    <description>Add Information About Involved Engineering, Procurement, Construction (EPC) Firms</description>
    <label>EPC Firm Involved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sourcing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Entity__c</fullName>
    <label>Sourcing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sourcing_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(SBQQ__Opportunity2__r.Brand__c)</formula>
    <inlineHelpText>Brand of product to be configured;  To change this value, edit on the parent opportunity</inlineHelpText>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <formula>Order_Number__c +  Status_Code__c + IF(Revision__c &gt; 0, TEXT( Revision__c ),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <description>Formerly &quot;Salesman&quot;</description>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <label>Selling Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Selling_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/Approver_for_Brand__c.field-meta.xml
<CustomField>
    <fullName>Approver_for_Brand__c</fullName>
    <label>Approver for Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Approver_for_House_Code__c.field-meta.xml
<CustomField>
    <fullName>Approver_for_House_Code__c</fullName>
    <label>Approver for House Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOE1</fullName>
            </value>
            <value>
                <fullName>DOE2</fullName>
            </value>
            <value>
                <fullName>DOE3</fullName>
            </value>
            <value>
                <fullName>DDH1</fullName>
            </value>
            <value>
                <fullName>DNIH</fullName>
            </value>
            <value>
                <fullName>LOE1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Approver_for_Region__c.field-meta.xml
<CustomField>
    <fullName>Approver_for_Region__c</fullName>
    <label>Approver for Region</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Regions</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Approver_for_Selling_Entity__c.field-meta.xml
<CustomField>
    <fullName>Approver_for_Selling_Entity__c</fullName>
    <label>Approver for Selling Entity</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Selling_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Approver_Level__c.field-meta.xml
<CustomField>
    <fullName>Approver_Level__c</fullName>
    <label>Approver Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inside Sales</fullName>
            </value>
            <value>
                <fullName>Sales Director</fullName>
            </value>
            <value>
                <fullName>Sales Executive</fullName>
            </value>
            <value>
                <fullName>Regional Manager</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sales_Division__c.field-meta.xml
<CustomField>
    <fullName>Sales_Division__c</fullName>
    <label>Selling Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Selling_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sourcing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Entity__c</fullName>
    <label>Sourcing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sourcing_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CDC</fullName>
    </customValue>
    <customValue>
        <fullName>Groth</fullName>
    </customValue>
    <customValue>
        <fullName>LaMOT</fullName>
    </customValue>
    <customValue>
        <fullName>LVA</fullName>
    </customValue>
    <masterLabel>Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Districts.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA PAC</fullName>
    </customValue>
    <customValue>
        <fullName>EAR</fullName>
    </customValue>
    <customValue>
        <fullName>ME/OCNA/SK</fullName>
    </customValue>
    <customValue>
        <fullName>UPSTREAM</fullName>
        <label>Domestic Upstream</label>
    </customValue>
    <masterLabel>Districts</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Regions.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AF1</fullName>
    </customValue>
    <customValue>
        <fullName>D01</fullName>
        <label>Domestic 1</label>
    </customValue>
    <customValue>
        <fullName>D02</fullName>
        <label>Domestic 2</label>
    </customValue>
    <customValue>
        <fullName>D03</fullName>
        <label>Domestic 3</label>
    </customValue>
    <customValue>
        <fullName>D04</fullName>
        <label>Domestic 4</label>
    </customValue>
    <customValue>
        <fullName>D05</fullName>
        <label>Domestic 5</label>
    </customValue>
    <customValue>
        <fullName>D06</fullName>
        <label>Domestic 6</label>
    </customValue>
    <customValue>
        <fullName>DUPS</fullName>
        <label>Domestic Upstream</label>
    </customValue>
    <customValue>
        <fullName>E0</fullName>
        <label>East 0</label>
    </customValue>
    <customValue>
        <fullName>E1</fullName>
        <label>East 1</label>
    </customValue>
    <customValue>
        <fullName>E2</fullName>
        <label>East 2</label>
    </customValue>
    <customValue>
        <fullName>EU1</fullName>
        <label>European Union 1</label>
    </customValue>
    <customValue>
        <fullName>EU2</fullName>
        <label>European Union 2</label>
    </customValue>
    <customValue>
        <fullName>EU3</fullName>
        <label>European Union 3</label>
    </customValue>
    <customValue>
        <fullName>EU4</fullName>
        <label>European Union 4</label>
    </customValue>
    <customValue>
        <fullName>FR1</fullName>
        <label>N France</label>
    </customValue>
    <customValue>
        <fullName>LA1</fullName>
        <label>Latin America 1</label>
    </customValue>
    <customValue>
        <fullName>LA2</fullName>
        <label>Latin America 2</label>
    </customValue>
    <customValue>
        <fullName>LA3</fullName>
        <label>Latin America 3</label>
    </customValue>
    <customValue>
        <fullName>ME1</fullName>
        <label>Middle East 1</label>
    </customValue>
    <customValue>
        <fullName>ME2</fullName>
        <label>Middle East 2</label>
    </customValue>
    <customValue>
        <fullName>OC1</fullName>
        <label>Oceania</label>
    </customValue>
    <customValue>
        <fullName>FR2</fullName>
        <label>S France</label>
    </customValue>
    <customValue>
        <fullName>DOE3</fullName>
    </customValue>
    <customValue>
        <fullName>DDH1</fullName>
    </customValue>
    <customValue>
        <fullName>DOE2</fullName>
    </customValue>
    <customValue>
        <fullName>DNIH</fullName>
    </customValue>
    <customValue>
        <fullName>LOE1</fullName>
    </customValue>
    <customValue>
        <fullName>DOE1</fullName>
    </customValue>
    <customValue>
        <fullName>DLD</fullName>
    </customValue>
    <masterLabel>Regions</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Selling_Entities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>Liberty</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Stafford</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>GCMPL</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>Not Allowed</fullName>
    </customValue>
    <masterLabel>Selling Entities</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sourcing_Entities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>Liberty</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Stafford</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>GCMPL</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>Not Allowed</fullName>
    </customValue>
    <masterLabel>Sourcing Entities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteTriggerTest.cls
/**
 * @description       : 
 * @author            : ApexIT - SFDC Dev Team
 * @group             : 
 * @last modified on  : 11-02-2020
 * @last modified by  : ApexIT - SFDC Dev Team
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   11-02-2020   ApexIT - SFDC Dev Team   Initial Version
 * 1.1   16-06-2021   Rohini Hathi             Service Ticket #205643 - Testcases are failing with Duplicate account getting created in testsetup.
**/
@isTest
public class QuoteTriggerTest {
    @isTest
    static void unittest(){
        /*list<group> lstgroups = new list<group>();
        Group gpEng = new Group();
        gpEng.Name = 'ENG_LaMot_10';
        gpEng.DeveloperName = 'ENG_LaMot_10';
        lstgroups.add(gpEng);
        Group gpProd = new Group();
        gpProd.Name = 'PROD_LaMot_10';
        gpProd.DeveloperName = 'PROD_LaMot_10';
        lstgroups.add(gpProd);
        insert lstgroups;*/
        Profile oProfile ;
        for(Profile p : [Select ID, Name from Profile Where Name = 'System Administrator']){
            oProfile = p;
        }
        System.debug('@Developer --> oProfile :' + oProfile);
        string sUserName = 'test_' + TestUtility.getRandomNumber() + '@test.com';
        string sUserName2 = 'test2_' + TestUtility.getRandomNumber() + '@test.com';
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        list<User> lstUsers = new list<User>();
        User oUser = new User();
        oUser.UserRoleId = portalRole.Id;
        oUser.UserName = sUserName;
        oUser.FirstName = 'Test-First';
        oUser.LastName = 'Test-Last';
        oUser.Alias = 'test';
        oUser.email = 'test' + TestUtility.getRandomNumber() + '@test.com';
        oUser.ProfileID = oProfile.Id;
        oUser.TimeZoneSidKey = 'America/New_York';   
        oUser.LocaleSidKey = 'en_US';
        oUser.EmailEncodingKey = 'UTF-8';
        oUser.LanguageLocaleKey = 'en_US';   
        lstUsers.add(oUser);
        
        User oUser2 = new User();
        oUser2.UserName = sUserName2;
        oUser2.FirstName = 'Test-First2';
        oUser2.LastName = 'Test-Last2';
        oUser2.Alias = 'test2';
        oUser2.email = 'test2' + TestUtility.getRandomNumber() + '@test.com';
        oUser2.ProfileID = oProfile.Id;
        oUser2.TimeZoneSidKey = 'America/New_York';   
        oUser2.LocaleSidKey = 'en_US';
        oUser2.EmailEncodingKey = 'UTF-8';
        oUser2.LanguageLocaleKey = 'en_US';   
        lstUsers.add(oUser2);
        
        User oUser3 = new User();
        oUser3.UserName = 'test3_' + TestUtility.getRandomNumber() + '@test.com';
        oUser3.FirstName = 'Test-First3';
        oUser3.LastName = 'Test-Last3';
        oUser3.Alias = 'test3';
        oUser3.email = 'test3' + TestUtility.getRandomNumber() + '@test.com';
        oUser3.ProfileID = oProfile.Id;
        oUser3.TimeZoneSidKey = 'America/New_York';   
        oUser3.LocaleSidKey = 'en_US';
        oUser3.EmailEncodingKey = 'UTF-8';
        oUser3.LanguageLocaleKey = 'en_US';
        oUser3.Approver_Level__c = 'Inside Sales';
        oUser3.Approver_for_Selling_Entity__c = '10';
        oUser3.Approver_for_Brand__c = 'LaMot';
        lstUsers.add(oUser3);
        
        User oUser4 = new User();
        oUser4.UserName = 'test4_' + TestUtility.getRandomNumber() + '@test.com';
        oUser4.FirstName = 'Test-First4';
        oUser4.LastName = 'Test-Last4';
        oUser4.Alias = 'test4';
        oUser4.email = 'test4' + TestUtility.getRandomNumber() + '@test.com';
        oUser4.ProfileID = oProfile.Id;
        oUser4.TimeZoneSidKey = 'America/New_York';   
        oUser4.LocaleSidKey = 'en_US';
        oUser4.EmailEncodingKey = 'UTF-8';
        oUser4.LanguageLocaleKey = 'en_US';
        oUser4.Approver_Level__c = 'Sales Director';
        oUser4.Approver_for_Region__c = 'DUPS';
        oUser4.Approver_for_House_Code__c = 'DOE1';
        oUser4.Approver_for_Brand__c = 'LaMot';
        lstUsers.add(oUser4);
        
        User oUser5 = new User();
        oUser5.UserName = 'test5_' + TestUtility.getRandomNumber() + '@test.com';
        oUser5.FirstName = 'Test-First5';
        oUser5.LastName = 'Test-Last5';
        oUser5.Alias = 'test5';
        oUser5.email = 'test5' + TestUtility.getRandomNumber() + '@test.com';
        oUser5.ProfileID = oProfile.Id;
        oUser5.TimeZoneSidKey = 'America/New_York';   
        oUser5.LocaleSidKey = 'en_US';
        oUser5.EmailEncodingKey = 'UTF-8';
        oUser5.LanguageLocaleKey = 'en_US';
        oUser5.Approver_Level__c = 'Regional Manager';
        oUser5.Approver_for_Region__c = 'DUPS';
        lstUsers.add(oUser5);
        
        insert lstUsers;
        system.runAs(oUser){
            string sCustomerAccountRecordTypeId = UtilityHelper.self.mapAccountRecordTypeNameWiseId.get('Customer Account').getRecordTypeId();
            list<Account> lstAccounts = new list<Account>();
            Account oAccount = TestUtility.createPartnerAccount('Test',false);
            oAccount.Rep_Code__c='UCN1';
            oAccount.Region__c='DUPS';
            oAccount.District__c='AMERICAS';
            oAccount.External_ID__c='UCN1-DUPS-AMERICAS';
            lstAccounts.add(oAccount);
            Account oAccount2 = TestUtility.createPartnerAccount('Test2',false);
            oAccount2.Rep_Code__c='AK2';
            oAccount2.Region__c='D05';
            oAccount2.District__c='AMERICAS';
            oAccount2.External_ID__c='AK2-D05-AMERICAS';
            lstAccounts.add(oAccount2);
            insert lstAccounts;
            oAccount.IsPartner = true;
            oAccount2.IsPartner = true;
            update lstAccounts;
            
            contact oContact = TestUtility.createContact('testCon',oAccount.Id,true);
            User oPartnerUser = TestUtility.createPartnerUser('',oAccount.Name,oContact.Id,true);
            
            Account oAccCust = TestUtility.createAccount('Test Customer Accp', sCustomerAccountRecordTypeId, false);
            oAccCust.Rep_Code_Account__c = oAccount.Id;
            // Service Ticket #205643 Added Billing City and Street FOR VALIDATION OF BILLING ADDR ON CUSTOMER ACCOUNT            oAccCust.BillingCity = 'Mumbai';
         	oAccCust.BillingStreet = 'Park Street, Lane 1';
            oAccCust.BillingCity = 'Kolkatta';
          	oAccCust.BillingCountry = 'India';
            insert oAccCust;
            
            Opportunity oOpportunity = TestUtility.createOpportunty('Test Opportunity1', oAccCust.Id, oAccount.Id, false);
            oOpportunity.StageName = 'Discovery/Identified';
            oOpportunity.CloseDate = system.today().adddays(15);
            oOpportunity.EPC_Firm_Involved__c = 'No';
            oOpportunity.Brand__c = 'LaMot';
            oOpportunity.Sourcing_Entity__c = '10';
            oOpportunity.Sales_Division__c = '10';
            insert oOpportunity;
            
            list<OpportunityTeamMember> lstOpportunityTeamMemberToInsert = new list<OpportunityTeamMember>();
            OpportunityTeamMember oOpportunityTeamMember = new OpportunityTeamMember();
            oOpportunityTeamMember.OpportunityId = oOpportunity.Id;
            oOpportunityTeamMember.opportunityaccessLevel = 'Edit';
            oOpportunityTeamMember.TeamMemberRole = 'Sales Rep';
            oOpportunityTeamMember.UserId = oPartnerUser.Id;
            lstOpportunityTeamMemberToInsert.add(oOpportunityTeamMember);
            
            test.startTest();
            insert lstOpportunityTeamMemberToInsert;
            test.stopTest();
            SBQQ__Quote__c oQuote = new SBQQ__Quote__c();
            oQuote.SBQQ__Opportunity2__c = oOpportunity.Id;
            insert oQuote;
            update oQuote;
        }
    }  
}