force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AF1</fullName>
            </value>
            <value>
                <fullName>D01</fullName>
            </value>
            <value>
                <fullName>D02</fullName>
            </value>
            <value>
                <fullName>D03</fullName>
            </value>
            <value>
                <fullName>D04</fullName>
            </value>
            <value>
                <fullName>D05</fullName>
            </value>
            <value>
                <fullName>D06</fullName>
            </value>
            <value>
                <fullName>DDH1</fullName>
            </value>
            <value>
                <fullName>DEPC</fullName>
            </value>
            <value>
                <fullName>DHV</fullName>
            </value>
            <value>
                <fullName>DLD</fullName>
            </value>
            <value>
                <fullName>DNIH</fullName>
            </value>
            <value>
                <fullName>DOE1</fullName>
            </value>
            <value>
                <fullName>DOE2</fullName>
            </value>
            <value>
                <fullName>DOE3</fullName>
            </value>
            <value>
                <fullName>DUPS</fullName>
            </value>
            <value>
                <fullName>E0</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>EU1</fullName>
            </value>
            <value>
                <fullName>EU2</fullName>
            </value>
            <value>
                <fullName>EU3</fullName>
            </value>
            <value>
                <fullName>EU4</fullName>
            </value>
            <value>
                <fullName>FR1</fullName>
            </value>
            <value>
                <fullName>FR2</fullName>
            </value>
            <value>
                <fullName>LA1</fullName>
            </value>
            <value>
                <fullName>LA2</fullName>
            </value>
            <value>
                <fullName>LA3</fullName>
            </value>
            <value>
                <fullName>LOE1</fullName>
            </value>
            <value>
                <fullName>ME1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/globalValueSets/Districts.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA PAC</fullName>
    </customValue>
    <customValue>
        <fullName>EAR</fullName>
    </customValue>
    <customValue>
        <fullName>ME/OCNA/SK</fullName>
    </customValue>
    <customValue>
        <fullName>UPSTREAM</fullName>
        <label>Domestic Upstream</label>
    </customValue>
    <masterLabel>Districts</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DynamicCloneTest.cls
@isTest 
private class DynamicCloneTest{
    static testMethod void unitTest(){
        list<Account> lstAccounts = new list<Account>();
        Account oAccount = TestUtility.createPartnerAccount('Test',false);
        oAccount.Rep_Code__c='UCN1';
        oAccount.Region__c='DUPS';
        oAccount.District__c='AMERICAS';
        oAccount.External_ID__c='UCN1-DUPS-AMERICAS';
        lstAccounts.add(oAccount);
        Account oAccount2 = TestUtility.createPartnerAccount('Test2',false);
        oAccount2.Rep_Code__c='AK2';
        oAccount2.Region__c='D05';
        oAccount2.District__c='AMERICAS';
        oAccount2.External_ID__c='AK2-D05-AMERICAS';
        lstAccounts.add(oAccount2);
        insert lstAccounts;
        oAccount.IsPartner = true;
        oAccount2.IsPartner = true;
        update lstAccounts;
        
        list<sObject> lstsObjects = new list<sObject>(); 
        lstsObjects.add(oAccount);      
        lstsObjects.add(oAccount2);     
        DynamicClone.cloneObjects(lstsObjects,oAccount.getsObjectType());
    }
}