force-app/main/default/objects/Account/fields/District__c.field-meta.xml
<CustomField>
    <fullName>District__c</fullName>
    <label>District</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Districts</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Select the market/industry this Account falls under.</inlineHelpText>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OEM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>AF1</fullName>
            </value>
            <value>
                <fullName>D01</fullName>
            </value>
            <value>
                <fullName>D02</fullName>
            </value>
            <value>
                <fullName>D03</fullName>
            </value>
            <value>
                <fullName>D04</fullName>
            </value>
            <value>
                <fullName>D05</fullName>
            </value>
            <value>
                <fullName>D06</fullName>
            </value>
            <value>
                <fullName>DDH1</fullName>
            </value>
            <value>
                <fullName>DEPC</fullName>
            </value>
            <value>
                <fullName>DHV</fullName>
            </value>
            <value>
                <fullName>DLD</fullName>
            </value>
            <value>
                <fullName>DNIH</fullName>
            </value>
            <value>
                <fullName>DOE1</fullName>
            </value>
            <value>
                <fullName>DOE2</fullName>
            </value>
            <value>
                <fullName>DOE3</fullName>
            </value>
            <value>
                <fullName>DUPS</fullName>
            </value>
            <value>
                <fullName>E0</fullName>
            </value>
            <value>
                <fullName>E1</fullName>
            </value>
            <value>
                <fullName>E2</fullName>
            </value>
            <value>
                <fullName>EU1</fullName>
            </value>
            <value>
                <fullName>EU2</fullName>
            </value>
            <value>
                <fullName>EU3</fullName>
            </value>
            <value>
                <fullName>EU4</fullName>
            </value>
            <value>
                <fullName>FR1</fullName>
            </value>
            <value>
                <fullName>FR2</fullName>
            </value>
            <value>
                <fullName>LA1</fullName>
            </value>
            <value>
                <fullName>LA2</fullName>
            </value>
            <value>
                <fullName>LA3</fullName>
            </value>
            <value>
                <fullName>LOE1</fullName>
            </value>
            <value>
                <fullName>ME1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Default_Communication_Method__c.field-meta.xml
<CustomField>
    <fullName>Default_Communication_Method__c</fullName>
    <inlineHelpText>Preferred method for communication or contact</inlineHelpText>
    <label>Default Communication Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PHONE</fullName>
                <label>Phone</label>
            </value>
            <value>
                <fullName>E_MAIL</fullName>
                <label>E-mail</label>
            </value>
            <value>
                <fullName>FAX</fullName>
                <label>Fax</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>Please choose a contact under the end customer account or quick create a new contact from the lookup screen</errorMessage>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities - Customer Contact</relationshipLabel>
    <relationshipName>Customer_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Use_Application__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Application__c</fullName>
    <label>End Use Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 5 AND 2) OR (1 AND 4 AND (3 OR 6))</booleanFilter>
        <errorMessage>The Account provided must not be a Representative if the Type is something other than Stocking Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Representative</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent, Bill-To, Competitor, Consultant, Contractor/Sub-contractor, End User, EPC Contractor, Other, Parent, Report/Service Co., Representative, Reseller/Trader, Ship-To</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Stocking Distributor</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>notEqual</operation>
            <value>Stocking Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>End User Opportunities</relationshipLabel>
    <relationshipName>EndUserAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Market__c.field-meta.xml
<CustomField>
    <fullName>Market__c</fullName>
    <inlineHelpText>Select the market/industry this Opportunity falls under.</inlineHelpText>
    <label>Market</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Market</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OEM__c.field-meta.xml
<CustomField>
    <fullName>OEM__c</fullName>
    <label>OEM *DNU*</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Continental Disc Products</fullName>
            </value>
            <value>
                <fullName>Groth BioGas Products</fullName>
            </value>
            <value>
                <fullName>Groth Valve Products</fullName>
                <label>Groth Industrial</label>
            </value>
            <value>
                <fullName>LVA</fullName>
                <label>LaMOT Valve &amp; Arrestor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Project_Classification__c.field-meta.xml
<CustomField>
    <fullName>Project_Classification__c</fullName>
    <label>Project Classification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EXP</fullName>
                <label>New Construction - Expansion of existing Facility</label>
            </value>
            <value>
                <fullName>GRN</fullName>
                <label>New Construction - New Facility</label>
            </value>
            <value>
                <fullName>NA</fullName>
                <label>Not a Project</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/End_Use_Application__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Application__c</fullName>
    <formula>SBQQ__Opportunity2__r.End_Use_Application__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Use Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (End User)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <formula>Order_Number__c +  Status_Code__c + IF(Revision__c &gt; 0, TEXT( Revision__c ),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Project_Classification__c.field-meta.xml
<CustomField>
    <fullName>Project_Classification__c</fullName>
    <formula>Text(SBQQ__Opportunity2__r.Is_it_a_Project__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Classification</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <description>Formerly &quot;Salesman&quot;</description>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Group__c.field-meta.xml
<CustomField>
    <fullName>Product_Group__c</fullName>
    <label>Product Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TBD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Districts.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AMERICAS</fullName>
    </customValue>
    <customValue>
        <fullName>ASIA PAC</fullName>
    </customValue>
    <customValue>
        <fullName>EAR</fullName>
    </customValue>
    <customValue>
        <fullName>ME/OCNA/SK</fullName>
    </customValue>
    <customValue>
        <fullName>UPSTREAM</fullName>
        <label>Domestic Upstream</label>
    </customValue>
    <masterLabel>Districts</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Market.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>OGUPS</fullName>
        <label>Oil and Gas Upstream</label>
    </customValue>
    <customValue>
        <fullName>OGDWN</fullName>
        <label>Oil and Gas Downstream</label>
    </customValue>
    <customValue>
        <fullName>CHEM</fullName>
        <label>Chemical</label>
    </customValue>
    <customValue>
        <fullName>PHARM</fullName>
        <label>Pharmaceutical &amp; Biotech</label>
    </customValue>
    <customValue>
        <fullName>FOOD</fullName>
        <label>Food &amp; Beverage</label>
    </customValue>
    <customValue>
        <fullName>AERO</fullName>
        <label>Aircraft and Aerospace (Commercial)</label>
    </customValue>
    <customValue>
        <fullName>DEF</fullName>
        <label>Defense (Incl. Aircraft &amp; Aerospace)</label>
    </customValue>
    <customValue>
        <fullName>OTHER</fullName>
        <label>Other Industrial Markets</label>
    </customValue>
    <customValue>
        <fullName>MNICP</fullName>
        <label>Municipal</label>
    </customValue>
    <customValue>
        <fullName>PULP</fullName>
        <label>Pulp and Paper</label>
    </customValue>
    <customValue>
        <fullName>POWUT</fullName>
        <label>Power and Utilities</label>
    </customValue>
    <customValue>
        <fullName>SALESFORCE</fullName>
    </customValue>
    <customValue>
        <fullName>BIO</fullName>
        <isActive>false</isActive>
        <label>Biogas</label>
    </customValue>
    <customValue>
        <fullName>Defense</fullName>
        <isActive>false</isActive>
        <label>Defense</label>
    </customValue>
    <customValue>
        <fullName>Pharmaceutical</fullName>
        <isActive>false</isActive>
        <label>Pharmaceutical</label>
    </customValue>
    <customValue>
        <fullName>Equipment</fullName>
        <isActive>false</isActive>
        <label>Equipment</label>
    </customValue>
    <customValue>
        <fullName>Aircraft and Aerospace</fullName>
        <isActive>false</isActive>
        <label>Aircraft and Aerospace</label>
    </customValue>
    <masterLabel>Market</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/configRVReferenceCtrlTest.cls
/**
 * @description       : 
 * @author            : ApexIT - SFDC Dev Team
 * @group             : 
 * @last modified on  : 11-02-2020
 * @last modified by  : ApexIT - SFDC Dev Team
 * Modifications Log 
 * Ver   Date         Author                        Modification
 * 1.0   11-02-2020   ApexIT - SFDC Dev Team        Initial Version
 * 1.1   19-07-2021   Rohini Hathi                  Service Ticket #205643 - Testcases are failing with Duplicate account getting created in testsetup.
 **/
@istest
public class configRVReferenceCtrlTest {
    @isTest
    public static void testMethodRVReference() {   
        Account testAcc1 = new Account();
        Id recordId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Partner & House Account').getRecordTypeId();
        testAcc1.RecordtypeId = recordId;
        testAcc1.Name = 'TEMCO INC PARTNER';
        testAcc1.Rep_Code__c = '1AR3';
        testAcc1.Region__c='D01';
        testAcc1.District__c='AMERICAS';
        testAcc1.External_ID__c ='1AR3-D01-AMERICAS';              
        insert testAcc1;        
        testAcc1.IsPartner = true;      
        Update testAcc1;        
        
        Account testAcc = new Account();
        testAcc.Name = 'TEMCO INC TEST';
        testAcc.Rep_Code_Account__c = testAcc1.Id; 
        //Service Ticket #205643,29 APR 2021 FOR VALIDATION OF BILLING ADDR ON CUSTOMER ACCOUNT
        testAcc.BillingCity = 'Mumbai';
        testAcc.BillingStreet = 'ABC Street';
        testAcc.BillingCountry = 'India'; 
        insert testAcc;
        
        recordId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer Account').getRecordTypeId();
        testAcc.RecordtypeId = recordId;        
        Update testAcc;         
        
        Account testAcc2 = new Account();
        testAcc2.Name = 'TEMCO INC TEST2';
        //Service Ticket #205643,29 APR 2021 FOR VALIDATION OF BILLING ADDR ON CUSTOMER ACCOUNT
        testAcc2.BillingCity = 'Pune';
        testAcc2.BillingStreet = 'TMC Street';
        testAcc2.BillingCountry = 'India'; 
        insert testAcc2;
        testAcc2.RecordtypeId = recordId;
        testAcc2.Rep_Code_Account__c    = testAcc1.Id;          
        Update testAcc2;        
        
        Contact testCon = new Contact();
        testCon.LastName = 'TEMCO INC TEST Contact';
        testCon.AccountId = testAcc.Id;
        testCon.Default_Communication_Method__c = 'PHONE';
        insert testCon;     
        
        //Create a Product
        list<Product2> lstProducts = new list<Product2>();
        
        Product2 oProduct3 = new Product2(Name = 'Relief Valves',ProductCode = 'RLFVLV', IsActive = true);         
        lstProducts.add(oProduct3);
        
        insert lstProducts;
        
        Opportunity o = new Opportunity(Name = 'Test Opp', PartnerAccountId=testAcc1.Id, OEM__c ='Yes',Market__c    ='  CHEM',Product_Group__c    ='Continental Disc Products',Project_Classification__c='GRN',End_Use_Application__c   ='test',Contact__c  =testCon.Id,End_User__c =testAcc.Id,EPC_Firm_Involved__c='Yes',Brand__c='CDC',StageName = 'Discovery/Identified', CloseDate = Date.today(), AccountId = testAcc.Id);
        insert o;           
        
        SBQQ__Quote__c Quote = new SBQQ__Quote__c
            (
                SBQQ__Opportunity2__c = o.id,
                SBQQ__Account__c = testAcc.id,
                SBQQ__Primary__c = True,
                SBQQ__Status__c = 'Unblock',
                Destination_Rep__c = testAcc1.Id,
                Eng_Rep_1__c = testAcc1.Id,
                SBQQ__SubscriptionTerm__c = 12,
                Eng_Rep_2__c = testAcc1.Id
                
            );
        
        insert Quote;        
        
        list<SBQQ__QuoteLine__c> lstQuoteLine = new list<SBQQ__QuoteLine__c>(); 
        
        SBQQ__QuoteLine__c QuoteLine3 = new SBQQ__QuoteLine__c(SBQQ__Quote__c = Quote.Id,SBQQ__Product__c = oProduct3.Id,Line_Status__c ='Cancel');
        lstQuoteLine.add(QuoteLine3);
        
        insert lstQuoteLine;
        
        
        Relief_Valve__c RV = new Relief_Valve__c();
        RV.Quote_Line__c = QuoteLine3.Id;
        insert RV;
        
        test.startTest();
        ApexPages.StandardController sc = new ApexPages.StandardController(RV);
        configRVReferenceCtrl oconfigRVReferenceCtrl = new configRVReferenceCtrl(sc);
        
        PageReference pageRef = Page.configRVReference;
        //  pageRef.getParameters().put('id', String.valueOf(testAccountPlanInsert.Id));
        Test.setCurrentPage(pageRef);
        oconfigRVReferenceCtrl.getUserTimeZone(); 
        string sHCLASS = oconfigRVReferenceCtrl.HCLASS;
        oconfigRVReferenceCtrl.HCLASS='';
        string sMCBODY = oconfigRVReferenceCtrl.MCBODY;
        oconfigRVReferenceCtrl.MCBODY='';
        string sGPFACE = oconfigRVReferenceCtrl.GPFACE;
        oconfigRVReferenceCtrl.GPFACE='';
        string sMCSEAT = oconfigRVReferenceCtrl.MCSEAT;
        oconfigRVReferenceCtrl.MCSEAT='';
        string sMCPALL = oconfigRVReferenceCtrl.MCPALL;
        oconfigRVReferenceCtrl.MCPALL='';
        string sMCDPHM = oconfigRVReferenceCtrl.MCDPHM;
        oconfigRVReferenceCtrl.MCDPHM='';
        string sMCVALL = oconfigRVReferenceCtrl.MCVALL;
        oconfigRVReferenceCtrl.MCVALL='';
        string sMCPSGD = oconfigRVReferenceCtrl.MCPSGD;
        oconfigRVReferenceCtrl.MCPSGD='';
        string sMCWGHT = oconfigRVReferenceCtrl.MCWGHT;
        oconfigRVReferenceCtrl.MCWGHT='';
        string sMCSPRG = oconfigRVReferenceCtrl.MCSPRG;
        oconfigRVReferenceCtrl.MCSPRG='';
        string sMCSTMJ = oconfigRVReferenceCtrl.MCSTMJ;
        oconfigRVReferenceCtrl.MCSTMJ='';
        string sMCCOTB= oconfigRVReferenceCtrl.MCCOTB;
        oconfigRVReferenceCtrl.MCCOTB='';
        string sMCCOTP = oconfigRVReferenceCtrl.MCCOTP;
        oconfigRVReferenceCtrl.MCCOTP='';
        string sMCELMT = oconfigRVReferenceCtrl.MCELMT;
        oconfigRVReferenceCtrl.MCELMT='';
        string sVPRTOP = oconfigRVReferenceCtrl.VPRTOP;
        oconfigRVReferenceCtrl.VPRTOP='';
        string sPMI = oconfigRVReferenceCtrl.PMI;
        oconfigRVReferenceCtrl.PMI='';
        string sLDP = oconfigRVReferenceCtrl.LDP;
        oconfigRVReferenceCtrl.LDP='';
        Test.stopTest();   
    }
    
}