force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/cdcpc__SizingRequest__c.object-meta.xml
<CustomObject>
    <label>Sizing Requests</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Sizing Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sizing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__ContactId__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__ContactId__c</fullName>
    <description>CC: Link to User.ContactId field</description>
    <formula>Owner:User.ContactId</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ContactId</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Errors_on_Quote_Processing__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Errors_on_Quote_Processing__c</fullName>
    <description>CC - Text area to place any errors that may occur when processing Sizing Request into Salesforce CPQ Quote record.</description>
    <label>Errors on Quote Processing</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Is_Ready_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Is_Ready_for_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ready for Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Processed_to_quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Processed_to_quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CC - This checkbox will represent this sizing request having been successfully processed into a Salesforce CPQ Quote record.</description>
    <label>Processed to quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/cdcpc__Sizing_Request__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Sizing_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC - Header sizing request this opportunity was derived from. Does not need to be on page layout.</description>
    <label>Sizing Request</label>
    <referenceTo>cdcpc__SizingRequest__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Currency__c.field-meta.xml
<CustomField>
    <fullName>Customer_Currency__c</fullName>
    <inlineHelpText>This selection drives currency conversions of currency fields on quote and quote line</inlineHelpText>
    <label>Customer Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Use_Application__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Application__c</fullName>
    <label>End Use Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 5 AND 2) OR (1 AND 4 AND (3 OR 6))</booleanFilter>
        <errorMessage>The Account provided must not be a Representative if the Type is something other than Stocking Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Representative</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent, Bill-To, Competitor, Consultant, Contractor/Sub-contractor, End User, EPC Contractor, Other, Parent, Report/Service Co., Representative, Reseller/Trader, Ship-To</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Stocking Distributor</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>notEqual</operation>
            <value>Stocking Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>End User Opportunities</relationshipLabel>
    <relationshipName>EndUserAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EPC_Firm_Involved__c.field-meta.xml
<CustomField>
    <fullName>EPC_Firm_Involved__c</fullName>
    <description>Add Information About Involved Engineering, Procurement, Construction (EPC) Firms</description>
    <label>EPC Firm Involved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_it_a_Project__c.field-meta.xml
<CustomField>
    <fullName>Is_it_a_Project__c</fullName>
    <label>Is it a Project?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(SBQQ__Opportunity2__r.Brand__c)</formula>
    <inlineHelpText>Brand of product to be configured;  To change this value, edit on the parent opportunity</inlineHelpText>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Brand_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Brand_Order_Type__c</fullName>
    <label>Brand*</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brand</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Contact)</relationshipLabel>
    <relationshipName>Quotes9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/End_Use_Application__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Application__c</fullName>
    <formula>SBQQ__Opportunity2__r.End_Use_Application__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Use Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (End User)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__PrimaryContact__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__PrimaryContact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Primary contact for the quote. This person&apos;s name will appear on generated quote document.</description>
    <inlineHelpText>Primary contact for the quote. This person&apos;s name will appear on generated quote document. The e-mail address of this person will be sent the Order Acknowledgement if the Quote is ordered.</inlineHelpText>
    <label>Primary Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Shipping Account)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <description>Coincides with the Pending/In Review SBQQ Status</description>
    <label>Pending</label>
</RecordType>

force-app/main/default/objects/Sizing_Request_to_Quote__mdt/Sizing_Request_to_Quote__mdt.object-meta.xml
<CustomObject>
    <description>CC - Will hold data to change user assigned to task created from Sizing Request -&gt; Salesforce CPQ Quote creation flow.</description>
    <label>Sizing Request to Quote</label>
    <pluralLabel>Sizing Request to Quotes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Sizing_Request_to_Quote__mdt/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <description>CC - Store the Id of the recipient user to have tasks delegated to upon Salesforce CPQ quote creation.</description>
    <inlineHelpText>Id of the recipient user to have tasks delegated to upon Salesforce CPQ quote creation.</inlineHelpText>
    <label>UserId</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brand.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CDC</fullName>
    </customValue>
    <customValue>
        <fullName>Groth</fullName>
    </customValue>
    <customValue>
        <fullName>LaMOT</fullName>
    </customValue>
    <customValue>
        <fullName>LVA</fullName>
    </customValue>
    <masterLabel>Brand</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CDC</fullName>
    </customValue>
    <customValue>
        <fullName>Groth</fullName>
    </customValue>
    <customValue>
        <fullName>LaMOT</fullName>
    </customValue>
    <customValue>
        <fullName>LVA</fullName>
    </customValue>
    <masterLabel>Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SizingRequestToQuoteBatch.cls
global with sharing class SizingRequestToQuoteBatch implements Database.Batchable<sObject>, Schedulable {
    public String query;
    public Sizing_Request_to_Quote__mdt assignedToUser = Sizing_Request_to_Quote__mdt.getInstance('config');
    public List<Opportunity> newOppList = new List<Opportunity>();
    public List<Opportunity> insertedOppList = new List<Opportunity>();
    public List<SBQQ__Quote__c> newQuoteList = new List<SBQQ__Quote__c>();
    public List<Task> newTaskList = new List<Task>();
    public List<cdcpc__SizingRequest__c> sizingRequestsToUpdateList = new List<cdcpc__SizingRequest__c>();
    public List<cdcpc__SizingRequest__c> sizingRequestErrorList = new List<cdcpc__SizingRequest__c>();
    public Set<Id> sizingRequestIdSet = new Set<Id>();
    public Set<Id> insertedOpportunityIdSet = new Set<Id>();
    public Set<Id> insertedQuoteIdSet = new Set<Id>();
    public Set<Id> insertedTaskIdSet = new Set<Id>();
    public Map<Id, Contact> sizingRequestToContactMap = new Map<Id, Contact>();
    public Map<Id, Opportunity> sizingRequestToOpportunityMap = new Map<Id, Opportunity>();
    public Map<Id, SBQQ__Quote__c> sizingRequestToQuoteMap = new Map<Id, SBQQ__Quote__c>();
    public Map<Id, Id> quoteToSizingRequestIdMap = new Map<Id, Id>();
    public Map<Integer, String> oppErrorMap = new Map<Integer, String>();
    public Map<Integer, String> quoteErrorMap = new Map<Integer, String>();
    public Map<Integer, String> taskErrorMap = new Map<Integer, String>();
    public Map<Id, String> errorBankMap = new Map<Id, String>();

    public SizingRequestToQuoteBatch() {
        query = 'SELECT Id, cdcpc__Brand__c, cdcpc__ContactId__c, cdcpc__Is_Ready_for_Quote__c, cdcpc__Processed_to_quote__c, OwnerId FROM cdcpc__SizingRequest__c WHERE cdcpc__Is_Ready_for_Quote__c = true AND cdcpc__Processed_to_quote__c = false AND cdcpc__ContactId__c != null';
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        System.debug('SizingRequestToQuoteBatch start');
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<cdcpc__SizingRequest__c> sizingRequestList) {
        getContacts(sizingRequestList); // 1. set up sizing request to contact map for reference.
        createOpportunities(sizingRequestList); // 2. create opportunities from sizing request list.
        createQuotes(sizingRequestList); // 3. create quotes related to opportunities created from sizing request list.
        assignTasks(sizingRequestList); // 4. create tasks and assign them to user determined by custom metadata type record.
        updateSizingRequests(sizingRequestList); // 5. update successfully processed sizing requests as such.
    }

    global void finish(Database.BatchableContext BC){
        System.debug('SizingRequestToQuoteBatch finished');
    }

    private void getContacts(List<cdcpc__SizingRequest__c> sizingRequestList){
        Set<Id> ownerIdSet = new Set<Id>();
        for(cdcpc__SizingRequest__c sizingRequest : sizingRequestList){
            sizingRequestIdSet.add(sizingRequest.Id); //  storing sizing request Ids for later use.
            ownerIdSet.add(sizingRequest.cdcpc__ContactId__c);
        }
        List<Contact> contactList = [SELECT Id, AccountId, Account.Name, Account.Rep_Code_Account__c FROM Contact WHERE Id IN :ownerIdSet];
        for(Contact contact : contactList){
            sizingRequestToContactMap.put(contact.Id, contact);
        }
    }

    private void createOpportunities(List<cdcpc__SizingRequest__c> sizingRequestList){
        for(cdcpc__SizingRequest__c sizingRequest : sizingRequestList){
            Opportunity opp = new Opportunity(
                AccountId = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).AccountId,
                Amount = 0,
                Brand__c = sizingRequest.cdcpc__Brand__c,
                CloseDate = Date.Today().addDays(30),
                Customer_Contact__c = sizingRequest.cdcpc__ContactId__c,
                Customer_Currency__c = 'USD',
                EPC_Firm_Involved__c = 'No',
                End_Use_Application__c = 'Sizing Request TBD',
                End_User__c = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).AccountId,
                Is_it_a_project__c = 'No',
                Name = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).Account.Name + ' Sizing Request',
                PartnerAccountId = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).Account.Rep_Code_Account__c,
                cdcpc__Sizing_Request__c = sizingRequest.Id,
                Shipping_Account__c = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).AccountId,
                StageName = 'Discovery/Identified',
                Type = 'Community Sizing Request'
            );
            newOppList.add(opp);            
        }
        runInsert(newOppList, 'Opportunity', true);
        if(!oppErrorMap.isEmpty()){
            for(Integer i = 0; i < newOppList.size(); i++){
                if(newOppList[i].Id == null){
                    errorBankMap.put(newOppList[i].cdcpc__Sizing_Request__c, oppErrorMap.get(i));
                }
            }
        }
    }

    private void createQuotes(List<cdcpc__SizingRequest__c> sizingRequestList){
        List<Opportunity> insertedOpportunityList = [SELECT Id, cdcpc__Sizing_Request__c FROM Opportunity WHERE Id IN :insertedOpportunityIdSet];
        for(Opportunity opp : insertedOpportunityList){
            sizingRequestToOpportunityMap.put(opp.cdcpc__Sizing_Request__c, opp);
        }
        for(cdcpc__SizingRequest__c sizingRequest : sizingRequestList){
            SBQQ__Quote__c newQuote = new SBQQ__Quote__c(
                Brand_Order_Type__c = sizingRequest.cdcpc__Brand__c,
                RecordTypeId = Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Pending').getRecordTypeId(),
                SBQQ__Account__c = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).AccountId,
                SBQQ__Opportunity2__c = sizingRequestToOpportunityMap.get(sizingRequest.Id).Id,
                SBQQ__PrimaryContact__c = sizingRequest.cdcpc__ContactId__c
            );
            newQuoteList.add(newQuote);
            sizingRequestToQuoteMap.put(sizingRequest.Id, newQuote);
        }
        runInsert(newQuoteList, 'SBQQ__Quote__c', true);
        if(!quoteErrorMap.isEmpty()){
            for(Integer i = 0; i < newQuoteList.size(); i++){
                if(newQuoteList[i].Id == null){
                    errorBankMap.put(newQuoteList[i].SBQQ__Opportunity2__r.cdcpc__Sizing_Request__c, quoteErrorMap.get(i));
                }
            }
        }
    }

    private void assignTasks(List<cdcpc__SizingRequest__c> sizingRequestList){
        for(cdcpc__SizingRequest__c sizingRequest : sizingRequestList){
            Task newTask = new Task(
                OwnerId = assignedToUser.UserId__c,
                Subject = 'New Sizing Request Quote',
                CurrencyIsoCode = 'USD',
                WhatId = sizingRequestToQuoteMap.get(sizingRequest.Id).Id,
                ActivityDate = Date.Today().addDays(14),
                Priority = 'Normal',
                Status = 'Open'
            );
            newTaskList.add(newTask);
            quoteToSizingRequestIdMap.put(sizingRequestToQuoteMap.get(sizingRequest.Id).Id, sizingRequest.Id);
        }
        runInsert(newTaskList, 'Task', true);
        if(!taskErrorMap.isEmpty()){
            for(Integer i = 0; i < newTaskList.size(); i++){
                if(newTaskList[i].Id == null){
                    errorBankMap.put(quoteToSizingRequestIdMap.get(newTaskList[i].WhatId), taskErrorMap.get(i));
                }
            }
        }
    }

    private void updateSizingRequests(List<cdcpc__SizingRequest__c> sizingRequestList){
        Set<Id> successfullyProcessedSizingRequests = new Set<Id>();
        List<Task> insertedTasks = [SELECT Id, WhatId FROM Task WHERE Id IN :insertedTaskIdSet AND WhatId IN :insertedQuoteIdSet];
        for(Task insertedTask : insertedTasks){
            successfullyProcessedSizingRequests.add(quoteToSizingRequestIdMap.get(insertedTask.WhatId));
        }
        for(cdcpc__SizingRequest__c sizingRequest : sizingRequestList){
            if(successfullyProcessedSizingRequests.contains(sizingRequest.Id)){
                sizingRequest.cdcpc__Processed_to_quote__c = true;
                sizingRequestsToUpdateList.add(sizingRequest);
            } else {
                System.debug('error along the line with sizing request: ' + errorBankMap.get(sizingRequest.Id));
                sizingRequest.cdcpc__Errors_on_Quote_Processing__c = errorBankMap.get(sizingRequest.Id);
                sizingRequestErrorList.add(sizingRequest);
            }
        }
        if(!sizingRequestsToUpdateList.isEmpty()){
            runUpdate(sizingRequestsToUpdateList, 'cdcpc__SizingRequest__c', true);
        }
        if(!sizingRequestErrorList.isEmpty()){
            runUpdate(sizingRequestErrorList, 'cdcpc__SizingRequest__c', true);
        }
    }

    /** UTILITY METHODS START **/
    private void runInsert(List<sObject> listToInsert, String objectType, Boolean continueOnError){
        System.debug('runInsert');
        System.debug(objectType + ' listToInsert: ' + listToInsert);
        Database.SaveResult[] srList = Database.insert(listToInsert, continueOnError);
        for (Integer i = 0; i < srList.size(); i++) {            
            if (srList[i].isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully inserted ' + objectType + ', ID: ' + srList[i].getId());
                switch on objectType {
                    when 'Opportunity' {
                        insertedOpportunityIdSet.add(srList[i].getId());
                    }
                    when 'SBQQ__Quote__c' {
                        insertedQuoteIdSet.add(srList[i].getId());
                    }
                    when 'Task' {
                        insertedTaskIdSet.add(srList[i].getId());                        
                    }
                }
            }
            else {
                // Operation failed, so get all errors
                errorHandle(i, srList[i], objectType);               
            }
        }
    }

    private void runUpdate(List<sObject> listToUpdate, String objectType, Boolean continueOnError){
        System.debug('runUpdate');
        System.debug(objectType + ' listToUpdate: ' + listToUpdate);
        Database.SaveResult[] srList = Database.update(listToUpdate, continueOnError);
        for(Database.SaveResult sr : srList){
            if (sr.isSuccess()) {
                // Operation was successful, so get the ID of the record that was processed
                System.debug('Successfully updated '+ objectType + ' record with ID: ' + sr.getId());
            } else {
                // Operation failed, so get all errors 
                for(Database.Error err : sr.getErrors()) {
                    System.debug('The following error has occurred.');                    
                    System.debug(err.getStatusCode() + ': ' + err.getMessage());
                    System.debug(objectType + ' fields that affected this error: ' + err.getFields());
                }
            }
        }
    }

    private void errorHandle(Integer i, Database.SaveResult sr, String objectType){
        for(Database.Error err : sr.getErrors()) {
            System.debug('The following error has occurred.');                    
            System.debug(err.getStatusCode() + ': ' + err.getMessage());
            System.debug(objectType + ' fields that affected this error: ' + err.getFields());
            String errorMessage = 'Error inserting ' + objectType + ' ' + err.getMessage() + ' ' + err.getFields();
            switch on objectType {
                when 'Opportunity' {
                    oppErrorMap.put(i, errorMessage);
                }
                when 'SBQQ__Quote__c' {
                    quoteErrorMap.put(i, errorMessage);
                }
                when 'Task' {
                    taskErrorMap.put(i, errorMessage);                        
                }
            }
        }        
    }

    global void execute(SchedulableContext sc) {
        SizingRequestToQuoteBatch srq = new SizingRequestToQuoteBatch();
        database.executebatch(srq);
    }
}