force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>Customer_Account</fullName>
    <active>true</active>
    <description>All prospect or customer accounts will be assigned to &quot;Customer Account&quot; record type</description>
    <label>Customer Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner_House_Account.recordType-meta.xml
<RecordType>
    <fullName>Partner_House_Account</fullName>
    <active>true</active>
    <description>All rep code accounts are assigned to &quot;Partner &amp; House Account&quot; record type</description>
    <label>Partner &amp; House Account</label>
</RecordType>

force-app/main/default/objects/cdcpc__SizingRequest__c/cdcpc__SizingRequest__c.object-meta.xml
<CustomObject>
    <label>Sizing Requests</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Sizing Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sizing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Is_Ready_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Is_Ready_for_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ready for Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Processed_to_quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Processed_to_quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CC - This checkbox will represent this sizing request having been successfully processed into a Salesforce CPQ Quote record.</description>
    <label>Processed to quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__ProjectName__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__ProjectName__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <formula>Order_Number__c +  Status_Code__c + IF(Revision__c &gt; 0, TEXT( Revision__c ),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <description>Formerly &quot;Salesman&quot;</description>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/User/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/PartnerCommunityControllerTest.cls
@isTest
private class PartnerCommunityControllerTest {
    
    @isTest
    static void getSizingRequestsTest(){
        User testLicensedUser = CCTestUtils.createAdminUser(true);
        System.runAs(testLicensedUser){
            Account testPartnerRepAccount = CCTestUtils.createAccount('test partner rep account', false);
            testPartnerRepAccount.Rep_Code__c = 'V3';
            testPartnerRepAccount.External_ID__c = '55555';
            testPartnerRepAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_House_Account').getRecordTypeId();
            insert testPartnerRepAccount;
            testPartnerRepAccount.IsPartner = true;
            update testPartnerRepAccount;
            Account testAccount = CCTestUtils.createAccount('test account', false);
            testAccount.Rep_Code_Account__c = testPartnerRepAccount.Id;
            testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer_Account').getRecordTypeId();
            testAccount.Type = 'Agent';
            insert testAccount;
            Contact testContact = CCTestUtils.createContact(testAccount, true);
            User testUser = CCTestUtils.createTestUser(testContact, false);
            testUser.ContactId = testContact.Id;
            insert testUser;
            cdcpc__SizingRequest__c readySizingRequest = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'CDC', cdcpc__Is_Ready_for_Quote__c = true, cdcpc__Processed_to_quote__c = false, cdcpc__ProjectName__c = 'sizing request ready to be processed.');
            readySizingRequest.OwnerId = testUser.Id;
            cdcpc__SizingRequest__c notReadySizingRequest = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'Groth', cdcpc__Is_Ready_for_Quote__c = false, cdcpc__Processed_to_quote__c = false, cdcpc__ProjectName__c = 'sizing request not yet ready to be processed.');
            notReadySizingRequest.OwnerId = testUser.Id;
            cdcpc__SizingRequest__c alreadySubmittedSizingRequest = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'LaMOT', cdcpc__Is_Ready_for_Quote__c = true, cdcpc__Processed_to_quote__c = true, cdcpc__ProjectName__c = 'sizing request already processed to quote.');
            alreadySubmittedSizingRequest.OwnerId = testUser.Id;
            insert new List<cdcpc__SizingRequest__c>{readySizingRequest, notReadySizingRequest, alreadySubmittedSizingRequest};
                
            List<cdcpc__SizingRequest__c> sizingRequestsList = PartnerCommunityController.getUserSizingRequests(testUser.Id);
        	System.assertEquals(3, sizingRequestsList.size(), 'We expect to have queried for the correct number of exisitng szing request records associated to our test user.');
        }        
    }

    @isTest
    static void getQuoteLinesTest(){
        Account testPartnerRepAccount = CCTestUtils.createAccount('test partner rep account', true);
        testPartnerRepAccount.IsPartner = true;
        testPartnerRepAccount.Rep_Code__c = 'V3';
        testPartnerRepAccount.External_ID__c = '55555';
        testPartnerRepAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_House_Account').getRecordTypeId();
        update testPartnerRepAccount;
        Account testAccount = CCTestUtils.createAccount('test account', false);     
        testAccount.Rep_Code_Account__c = testPartnerRepAccount.Id; 
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer_Account').getRecordTypeId();
        testAccount.Type = 'Agent';
        insert testAccount;
        Opportunity testOpportunity = CCTestUtils.createOpportunity(testAccount, false);
        testOpportunity.PartnerAccountId = testPartnerRepAccount.Id;
        insert testOpportunity;
        Product2 testProduct = CCTestUtils.createProduct('test product', 'TEST', true);
        SBQQ__Quote__c testQuote = CCTesTUtils.createQuote(testAccount, testOpportunity, true, true, true);
        SBQQ__QuoteLine__c testQuoteLine = CCTestUtils.createQuoteLine(testProduct, null, testQuote, true, true);

        List<SBQQ__QuoteLine__c> testQuoteLines = PartnerCommunityController.getQuoteLines(testQuote.Id);
        System.assert(!testQuoteLines.isEmpty());
    }
}