force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>Customer_Account</fullName>
    <active>true</active>
    <description>All prospect or customer accounts will be assigned to &quot;Customer Account&quot; record type</description>
    <label>Customer Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner_House_Account.recordType-meta.xml
<RecordType>
    <fullName>Partner_House_Account</fullName>
    <active>true</active>
    <description>All rep code accounts are assigned to &quot;Partner &amp; House Account&quot; record type</description>
    <label>Partner &amp; House Account</label>
</RecordType>

force-app/main/default/objects/cdcpc__SizingRequest__c/cdcpc__SizingRequest__c.object-meta.xml
<CustomObject>
    <label>Sizing Requests</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Sizing Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sizing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Is_Ready_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Is_Ready_for_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ready for Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Processed_to_quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Processed_to_quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CC - This checkbox will represent this sizing request having been successfully processed into a Salesforce CPQ Quote record.</description>
    <label>Processed to quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__ProjectName__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__ProjectName__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/objects/User/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SizingRequestDeleteBatchTest.cls
@isTest
private class SizingRequestDeleteBatchTest {
    public static String CRON_EXP = '0 0 0 3 9 ? 2023';
    
    @TestSetup
    static void makeData(){
        User testLicensedUser = CCTestUtils.createAdminUser(true);
        System.runAs(testLicensedUser){
            Account testPartnerRepAccount = CCTestUtils.createAccount('test partner rep account', false);
            testPartnerRepAccount.Rep_Code__c = 'V3';
            testPartnerRepAccount.External_ID__c = '55555';
            testPartnerRepAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_House_Account').getRecordTypeId();
            insert testPartnerRepAccount;
            testPartnerRepAccount.IsPartner = true;
            update testPartnerRepAccount;
            Account testAccount = CCTestUtils.createAccount('test account', false);
            testAccount.Rep_Code_Account__c = testPartnerRepAccount.Id;
            testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer_Account').getRecordTypeId();
            testAccount.Type = 'Agent';
            insert testAccount;
            Contact testContact = CCTestUtils.createContact(testAccount, true);
            User testUser = CCTestUtils.createTestUser(testContact, false);
            testUser.ContactId = testContact.Id;
            insert testUser;
            cdcpc__SizingRequest__c sizingRequestToDelete = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'CDC', cdcpc__Is_Ready_for_Quote__c = false, cdcpc__Processed_to_quote__c = false, cdcpc__ProjectName__c = 'test sizing request to delete');
            sizingRequestToDelete.OwnerId = testUser.Id;
            insert sizingRequestToDelete;
        }
    }

    @isTest
    private static void testSizingRequestToQuoteProcess(){
        Test.startTest();
        SizingRequestDeleteBatch s2db = new SizingRequestDeleteBatch();
        Database.executeBatch(s2db);
        Test.stopTest();
        List<cdcpc__SizingRequest__c> remainingSizingRequests = [SELECT Id FROM cdcpc__SizingRequest__c];
        System.assert(remainingSizingRequests.isEmpty(), 'We expect our sizing requests to have been deleted.');
    }
    
    @isTest
    static void testScheduler(){
        Test.startTest();
        SizingRequestDeleteBatch scheduledBatchJob = new SizingRequestDeleteBatch();
        String batchJob = System.schedule('testBatchJob', CRON_EXP, scheduledBatchJob);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :batchJob];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        Test.stopTest();
    }
}