force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <label>Customer Contact</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Customer_Currency__c.field-meta.xml
<CustomField>
    <fullName>Customer_Currency__c</fullName>
    <inlineHelpText>This selection drives currency conversions of currency fields on quote and quote line</inlineHelpText>
    <label>Customer Currency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
            <value>
                <fullName>INR</fullName>
            </value>
            <value>
                <fullName>USD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_Use_Application__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Application__c</fullName>
    <label>End Use Application</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Account</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 5 AND 2) OR (1 AND 4 AND (3 OR 6))</booleanFilter>
        <errorMessage>The Account provided must not be a Representative if the Type is something other than Stocking Distributor.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>notEqual</operation>
            <value>Representative</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value>Agent, Bill-To, Competitor, Consultant, Contractor/Sub-contractor, End User, EPC Contractor, Other, Parent, Report/Service Co., Representative, Reseller/Trader, Ship-To</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Stocking Distributor</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>notEqual</operation>
            <value>Stocking Distributor</value>
        </filterItems>
        <filterItems>
            <field>Account.Type</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>End User Opportunities</relationshipLabel>
    <relationshipName>EndUserAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EPC_Firm_Involved__c.field-meta.xml
<CustomField>
    <fullName>EPC_Firm_Involved__c</fullName>
    <description>Add Information About Involved Engineering, Procurement, Construction (EPC) Firms</description>
    <label>EPC Firm Involved</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Is_it_a_Project__c.field-meta.xml
<CustomField>
    <fullName>Is_it_a_Project__c</fullName>
    <label>Is it a Project?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To Account)</relationshipLabel>
    <relationshipName>Opportunities3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(SBQQ__Opportunity2__r.Brand__c)</formula>
    <inlineHelpText>Brand of product to be configured;  To change this value, edit on the parent opportunity</inlineHelpText>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Quotes (Customer Contact)</relationshipLabel>
    <relationshipName>Quotes9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/End_Use_Application__c.field-meta.xml
<CustomField>
    <fullName>End_Use_Application__c</fullName>
    <formula>SBQQ__Opportunity2__r.End_Use_Application__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>End Use Application</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/End_User__c.field-meta.xml
<CustomField>
    <fullName>End_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>End User Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (End User)</relationshipLabel>
    <relationshipName>Quotes1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Type__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Type__c</fullName>
    <description>Indicates the type of quote.</description>
    <inlineHelpText>Indicates the type of quote.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Buy/Resell</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
            </value>
            <value>
                <fullName>Quote</fullName>
            </value>
            <value>
                <fullName>Renewal</fullName>
            </value>
            <value>
                <fullName>Amendment</fullName>
            </value>
            <value>
                <fullName>Re-Quote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Shipping_Account__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Shipping Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Quotes (Shipping Account)</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>SBQQ__Quote__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Customer_Currency__c.field-meta.xml
<CustomField>
    <fullName>Customer_Currency__c</fullName>
    <formula>TEXT( SBQQ__Quote__r.Currency__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ChargeType__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ChargeType__c</fullName>
    <description>The type of the product charge.  This is a system field that is derived from the associated product.</description>
    <inlineHelpText>The type of the product charge.  This is a system field that is derived from the associated product.</inlineHelpText>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SBQQ__ChargeType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__NetPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__NetPrice__c</fullName>
    <description>Net unit price for the product quoted by this line item.</description>
    <inlineHelpText>Net unit price for the product quoted by this line item.</inlineHelpText>
    <label>Net Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__RegularPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__RegularPrice__c</fullName>
    <description>Unit price before additional discount.</description>
    <inlineHelpText>DO NOT USE</inlineHelpText>
    <label>Regular Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/User/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CDC</fullName>
    </customValue>
    <customValue>
        <fullName>Groth</fullName>
    </customValue>
    <customValue>
        <fullName>LaMOT</fullName>
    </customValue>
    <customValue>
        <fullName>LVA</fullName>
    </customValue>
    <masterLabel>Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CCTestUtils.cls
/**
 *
 * @author Kevin Fleck - Coastal Cloud
 * kevin.fleck@coastalcloud.us
 *
 */
@IsTest
public without sharing class CCTestUtils {

    public static Account createAccount(String name, Boolean doInsert) {
        Account obj = new Account();
        obj.Name = name;

        if(doInsert) {
            insert obj;
        }

        return obj;
    }

    public static Opportunity createOpportunity(Account testAccount, Boolean doInsert){
        Opportunity obj = new Opportunity();
        obj.Name = testAccount.Name + ' test opportunity';
        obj.StageName = 'Discovery/Identified';
        obj.AccountId = testAccount.Id;
        obj.Amount = 0;
        obj.Brand__c = 'CDC';
        obj.CloseDate = Date.Today().addDays(30);
        // Customer_Contact__c = sizingRequest.cdcpc__ContactId__c,
        obj.Customer_Currency__c = 'USD';
        obj.EPC_Firm_Involved__c = 'No';
        obj.End_Use_Application__c = 'Test';
        obj.End_User__c = testAccount.Id;
        obj.Is_it_a_project__c = 'No';
        // PartnerAccountId = sizingRequestToContactMap.get(sizingRequest.cdcpc__ContactId__c).Account.Rep_Code_Account__c,
        obj.Shipping_Account__c = testAccount.Id;
        obj.Type = 'Test';

        if(doInsert){
            insert obj;
        }
        return obj;
    }

    public static Contact createContact(Account acc, Boolean doInsert) {

        Contact testContact = new Contact(
            FirstName = 'test',
            LastName = 'contact',
            AccountId = acc != null ? acc.Id : null,
            Email = 'fullname@domain.com'
        );

        if(doInsert) {
            insert testContact;
        }
        return testContact;
    }

    public static Product2 createProduct(String name, String productCode, Boolean doInsert) {
        Product2 obj = (Product2)Product2.sObjectType.newSObject(
            null, // null will make it the default record type for the user
            true // loadDefaultValues
        );
        obj.Name = name;
        obj.IsActive = true;
        obj.ProductCode = productCode;
        obj.IsActive = true;



        if(doInsert) {
            insert obj;
        }

        return obj;
    }

    public static SBQQ__Quote__c createQuote(Account acct, Opportunity opp, Boolean isPrimary, Boolean populateDefaultValues, Boolean doInsert) {
        SBQQ__Quote__c obj = (SBQQ__Quote__c)SBQQ__Quote__c.sObjectType.newSObject(
            null, // null will make it the default record type for the user
            true // loadDefaultValues
        );
        obj.SBQQ__Primary__c = isPrimary;
        obj.SBQQ__StartDate__c = Date.today();
        //obj.SBQQ__EndDate__c = Date.today().addMonths(1);
        obj.SBQQ__Opportunity2__c = opp == null ? null : opp.Id;
        obj.SBQQ__SubscriptionTerm__c = 12;
        obj.SBQQ__ExpirationDate__c = Date.today() + 30;
        obj.SBQQ__Account__c = acct == null ? null : acct.Id;
        obj.SBQQ__Type__c = 'Quote';

        if(doInsert) {
            insert obj;
        }
        return obj;
    }

    public static SBQQ__QuoteLine__c createQuoteLine(Product2 product, PriceBookEntry pbe, SBQQ__Quote__c quote, Boolean populateDefaultValues, Boolean doInsert) {
        SBQQ__QuoteLine__c obj = (SBQQ__QuoteLine__c)SBQQ__QuoteLine__c.sObjectType.newSObject(
            null, // null will make it the default record type for the user
            populateDefaultValues // loadDefaultValues
        );
        obj.SBQQ__Product__c = product.Id;
        obj.SBQQ__Quote__c = quote.Id;
        obj.SBQQ__PricebookEntryId__c = pbe == null ? null : pbe.Id;
        obj.SBQQ__PricingMethod__c = 'List';
        obj.SBQQ__StartDate__c = Date.today();
        obj.SBQQ__ListPrice__c = 100;
        obj.SBQQ__Quantity__c = 1;
        obj.SBQQ__PriorQuantity__c = 0;
        obj.SBQQ__RegularPrice__c = 100;
        obj.SBQQ__NetPrice__c = 100;
        obj.SBQQ__Number__c = 1;
        obj.SBQQ__ProrateMultiplier__c = 1;
        obj.SBQQ__SubscriptionPricing__c = 'Fixed Price';
        obj.SBQQ__SubscriptionScope__c = 'Quote';
        obj.SBQQ__DefaultSubscriptionTerm__c = 1;
        obj.SBQQ__ChargeType__c = product.SBQQ__ChargeType__c;
        obj.SBQQ__BillingType__c = product.SBQQ__BillingType__c;
        obj.SBQQ__BillingFrequency__c = product.SBQQ__BillingFrequency__c;

        if(doInsert) {
            insert obj;
        }
        return obj;
    }

    public static User createTestUser(Contact contact, Boolean doInsert){
        Profile communityProfile = [SELECT Id FROM Profile WHERE Name = 'CDC Public Community User' LIMIT 1];
        User obj = new User();
        obj.FirstName = contact.firstName;
        obj.LastName = contact.lastName;
        obj.Email = contact.email;
        obj.UserName = contact.email;
        obj.ContactId = contact.Id;
        obj.ProfileId = communityProfile.Id;
        obj.TimeZoneSidKey = 'America/Chicago'; 
        obj.LocaleSidKey = 'en_US'; 
        obj.EmailEncodingKey = 'ISO-8859-1'; 
        obj.LanguageLocaleKey = 'en_US';
        obj.Alias ='tstUsr';

        if(doInsert) {
            insert obj;
        }

        return obj;

    }

    public static User createAdminUser(Boolean doInsert){ // created to run certain tests as admin, where needed.
        Profile communityProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1];
        UserRole testRole = [SELECT Id FROM UserRole WHERE Name = 'Application Engineer' LIMIT 1];
        User obj = new User();
        obj.FirstName = 'admin';
        obj.LastName = 'user';
        obj.Email = 'admin@user.com';
        obj.UserName = 'admin@cdcusertest147.com';
        obj.UserRoleId = testRole.Id;
        obj.ProfileId = communityProfile.Id;
        obj.TimeZoneSidKey = 'America/Chicago'; 
        obj.LocaleSidKey = 'en_US'; 
        obj.EmailEncodingKey = 'ISO-8859-1'; 
        obj.LanguageLocaleKey = 'en_US';
        obj.Alias ='tstUsr';

        if(doInsert) {
            insert obj;
        }

        return obj;

    }
    
    // public static Order createOrder(Account account, Pricebook2 pricebook, Boolean doInsert) {
    //         Order obj = new Order();
    //         obj.AccountId = account.Id;
    //         obj.BillingCity = 'Gainesville';
    //         obj.BillingCountry = 'United States';
    //         obj.BillingPostalCode = '32107';
    //         obj.BillingState = 'Florida';
    //         obj.BillingStreet = '4600 E University Avenue';
    //         obj.EffectiveDate = Date.today();
    //         obj.Pricebook2Id = priceBook == null ? Test.getStandardPricebookId() : priceBook.Id;
    //         obj.ShippingCity = 'Gainesville';
    //         obj.ShippingCountry = 'United States';
    //         obj.ShippingPostalCode = '32107';
    //         obj.ShippingState = 'Florida';
    //         obj.ShippingStreet = '1000 Archer Road';
    //         obj.Status = 'Draft';
    //         obj.Type = 'OR';
        
    //         if(doInsert){ 
    //             insert obj;
    //         }

    //         return obj;
    // }

    // public static OrderItem createOrderItem(Order order, Product2 product, PricebookEntry pricebookEntry, Boolean doInsert){
    //     OrderItem obj = new OrderItem();
    //     obj.OrderId = order.Id;
    //     obj.Product2Id = product.Id;
    //     obj.PricebookEntryId = pricebookEntry.Id;
    //     obj.ListPrice = pricebookEntry.UnitPrice;
    //     obj.UnitPrice = 123;
    //     obj.Quantity = 3;
    //     obj.Type = 'Order Product';

    //     if(doInsert){ 
    //         insert obj;
    //     }

    //     return obj;
    // }
    
}