force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Rep_Code_Account__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rep Code</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please choose valid partner account</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Partner &amp; House Account</value>
        </filterItems>
        <filterItems>
            <field>Account.Rep_Code__c</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>Customer_Account</fullName>
    <active>true</active>
    <description>All prospect or customer accounts will be assigned to &quot;Customer Account&quot; record type</description>
    <label>Customer Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Partner_House_Account.recordType-meta.xml
<RecordType>
    <fullName>Partner_House_Account</fullName>
    <active>true</active>
    <description>All rep code accounts are assigned to &quot;Partner &amp; House Account&quot; record type</description>
    <label>Partner &amp; House Account</label>
</RecordType>

force-app/main/default/objects/cdcpc__SizingRequest__c/cdcpc__SizingRequest__c.object-meta.xml
<CustomObject>
    <label>Sizing Requests</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Sizing Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sizing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Is_Ready_for_Quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Is_Ready_for_Quote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Ready for Quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__Processed_to_quote__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Processed_to_quote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>CC - This checkbox will represent this sizing request having been successfully processed into a Salesforce CPQ Quote record.</description>
    <label>Processed to quote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/cdcpc__SizingRequest__c/fields/cdcpc__ProjectName__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__ProjectName__c</fullName>
    <label>Project Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/cdcpc__Sizing_Request__c.field-meta.xml
<CustomField>
    <fullName>cdcpc__Sizing_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>CC - Header sizing request this opportunity was derived from. Does not need to be on page layout.</description>
    <label>Sizing Request</label>
    <referenceTo>cdcpc__SizingRequest__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/External_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Id__c</fullName>
    <formula>Order_Number__c +  Status_Code__c + IF(Revision__c &gt; 0, TEXT( Revision__c ),&apos;&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>External Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <description>Formerly &quot;Salesman&quot;</description>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/External_ID__c.field-meta.xml
<CustomField>
    <fullName>External_ID__c</fullName>
    <externalId>true</externalId>
    <label>External ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/SizingRequestToQuoteBatchTest.cls
@isTest
private class SizingRequestToQuoteBatchTest {    
    public static String CRON_EXP = '0 0 0 3 9 ? 2023';
    
    @TestSetup
    static void makeData(){
        User testLicensedUser = CCTestUtils.createAdminUser(true);
        System.runAs(testLicensedUser){
            Account testPartnerRepAccount = CCTestUtils.createAccount('test partner rep account', false);
            testPartnerRepAccount.Rep_Code__c = 'V3';
            testPartnerRepAccount.External_ID__c = '55555';
            testPartnerRepAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_House_Account').getRecordTypeId();
            insert testPartnerRepAccount;
            testPartnerRepAccount.IsPartner = true;
            update testPartnerRepAccount;
            Account testAccount = CCTestUtils.createAccount('test account', false);
            testAccount.Rep_Code_Account__c = testPartnerRepAccount.Id;
            testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Customer_Account').getRecordTypeId();
            testAccount.Type = 'Agent';
            insert testAccount;
            Contact testContact = CCTestUtils.createContact(testAccount, true);
            User testUser = CCTestUtils.createTestUser(testContact, false);
            testUser.ContactId = testContact.Id;
            insert testUser;
            cdcpc__SizingRequest__c readySizingRequest = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'CDC', cdcpc__Is_Ready_for_Quote__c = true, cdcpc__Processed_to_quote__c = false, cdcpc__ProjectName__c = 'sizing request ready to be processed.');
            readySizingRequest.OwnerId = testUser.Id;
            cdcpc__SizingRequest__c notReadySizingRequest = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'Groth', cdcpc__Is_Ready_for_Quote__c = false, cdcpc__Processed_to_quote__c = false, cdcpc__ProjectName__c = 'sizing request not yet ready to be processed.');
            notReadySizingRequest.OwnerId = testUser.Id;
            cdcpc__SizingRequest__c alreadySubmittedSizingRequest = new cdcpc__SizingRequest__c(cdcpc__Brand__c = 'LaMOT', cdcpc__Is_Ready_for_Quote__c = true, cdcpc__Processed_to_quote__c = true, cdcpc__ProjectName__c = 'sizing request already processed to quote.');
            alreadySubmittedSizingRequest.OwnerId = testUser.Id;
            insert new List<cdcpc__SizingRequest__c>{readySizingRequest, notReadySizingRequest, alreadySubmittedSizingRequest};
        }
    }

    @isTest
    private static void testSizingRequestToQuoteProcess(){
        Test.startTest();
        SizingRequestToQuoteBatch sb = new SizingRequestToQuoteBatch();
        Database.executeBatch(sb);
        Test.stopTest();

        cdcpc__SizingRequest__c readySizingRequest = [SELECT Id, cdcpc__ProjectName__c FROM cdcpc__SizingRequest__c WHERE cdcpc__ProjectName__c = 'sizing request ready to be processed.' LIMIT 1];
        Opportunity newOpp = [SELECT Id, cdcpc__Sizing_Request__c FROM Opportunity WHERE cdcpc__Sizing_Request__c = :readySizingRequest.Id LIMIT 1];
        SBQQ__Quote__c newQuote = [SELECT Id, SBQQ__Opportunity2__c FROM SBQQ__Quote__c WHERE SBQQ__Opportunity2__c = :newOpp.Id LIMIT 1];
        Task newTask = [SELECT Id, WhatId, OwnerId FROM Task WHERE WhatId = :newQuote.Id LIMIT 1];

        System.assertEquals(readySizingRequest.Id, newOpp.cdcpc__Sizing_Request__c, 'We expect a new opportunity to have been created from our sizing request that was ready to have been processed into a quote.');
        System.assertEquals(newOpp.Id, newQuote.SBQQ__Opportunity2__c, 'We expect a new Salesforce CPQ SBQQ__Quote__c record to have been created from our new opportunity.');
        System.assertEquals(newQuote.Id, newTask.WhatId, 'We expect a task to have been created from our new Quote record.');
    }
    
    @isTest
    static void testScheduler(){
        Test.startTest();
        SizingRequestToQuoteBatch scheduledBatchJob = new SizingRequestToQuoteBatch();
        String batchJob = System.schedule('testBatchJob', CRON_EXP, scheduledBatchJob);
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :batchJob];
        System.assertEquals(CRON_EXP, ct.CronExpression);
        Test.stopTest();
    } 
}