force-app/main/default/objects/Account/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code (Partner)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rep_Code__c/Rep_Code__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Rep Code</label>
</CustomObject>

force-app/main/default/objects/Rep_Code__c/fields/Company_Code__c.field-meta.xml
<CustomField>
    <fullName>Company_Code__c</fullName>
    <label>Company Code</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rep_Code__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <label>Company Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PopulateProspectRepCodeOppControllerTest.cls
@isTest
public class PopulateProspectRepCodeOppControllerTest {

    @isTest
    public static void PopulateProspectRepCodeOppController_Test(){
        //Create dummy account for controller
        Opportunity opp = new Opportunity();
        List<Rep_Code__c> repList = new List<Rep_Code__c>();
        for(Integer i=0; i<=1; i++){
            Rep_Code__c rep = new Rep_Code__c();
            rep.Name = 'Test'+i;
            rep.Company_Name__c = 'Test';
            rep.Company_Code__c = '005';
            repList.add(rep);
        }
        insert repList;
        //call the current page for testing
        Test.setCurrentPage(Page.PopulateProspectRepCode);
        
        //create a standard controller and pass the dummy account controller
        ApexPages.StandardController accountController = new ApexPages.StandardController(opp);
        
        //Get the Standard Controller ang pass it to controller extension
        PopulateProspectRepCodeOppController ace = new PopulateProspectRepCodeOppController(accountController);
        try{            
            //Start the Test            
            ace.opp.Name = 'Testing';
            ace.selectedRepCode = 'Test';
            ace.getRepCodeFields();
            ace.updateOpportunity();
            //PageReference redPage = ace.updateAccount();
            //End Test
        }catch(Exception ex){
            
        }        
    }
}