force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Leadtime__c.field-meta.xml
<CustomField>
    <fullName>Leadtime__c</fullName>
    <description>Maximum leadtime for product</description>
    <label>Leadtime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__ListPrice__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__ListPrice__c</fullName>
    <description>List unit price for the product quoted by this line item. List Price originates from the price book.</description>
    <inlineHelpText>List unit price for the product quoted by this line item. List Price originates from the price book.</inlineHelpText>
    <label>List Unit Price</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CPQContentPageController.cls
public class CPQContentPageController {
  protected Id quoteId;
  public static List<SBQQ__QuoteLine__c> quoteLineObj {get; set;}
  
  public CPQContentPageController() {
      quoteId = (Id)ApexPages.currentPage().getParameters().get('qid');
      System.debug('\n****quoteId'+quoteId);
  }
  
  public PageReference init() {
      quoteLineObj = [
          SELECT	id, 
          			SBQQ__ListPrice__c,
          			Leadtime__c,
          			SBQQ__Quantity__c,
          			SBQQ__OriginalQuoteLineId__c,
          			SBQQ__ProductName__c
          FROM SBQQ__QuoteLine__c
          WHERE SBQQ__Quote__c = :quoteId];
      
      System.debug('\n****quoteLineObj'+quoteLineObj);
      return null;
  }
}