force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UpdateRevisionNumber.cls
public class UpdateRevisionNumber {

    public UpdateRevisionNumber(ApexPages.StandardController stdController) {
        SBQQ__Quote__c qtRec = (SBQQ__Quote__c)stdController.getRecord();
        updateRevision(qtRec.Id);
    }
    public void updateRevision(Id qId)
    {
        SBQQ__Quote__c qt = [Select Id,Revision__c from SBQQ__Quote__c where Id=:qId];
        qt.Revision__c = qt.Revision__c + 1;
        update qt;
        SYstem.debug('Revision__c'+qt.Revision__c); 

    }
}