force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Comments__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Comments__c</fullName>
    <label>Change Order Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Status__c</fullName>
    <label>Change Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Change Order Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IFS_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>IFS_Order_Status__c</fullName>
    <defaultValue>&quot;Not Submitted&quot;</defaultValue>
    <label>IFS Order Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <formula>TEXT( Sales_Division__c )&amp;RIGHT(Quote_Number__c,LEN(Quote_Number__c)-2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Change_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Status__c</fullName>
    <label>Change Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Delivery_Number__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Number__c</fullName>
    <defaultValue>1</defaultValue>
    <description>Used for Rel_No in the integration</description>
    <label>Delivery Number</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <description>Used to override the default Line_No mapping on a line item</description>
    <label>Line Number (IFS Override)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/QuoteLineNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteLineNumber__c</fullName>
    <defaultValue>1</defaultValue>
    <label>QuoteLineNumber</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Status_Reason__c</fullName>
    <label>Status Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Change_Order_Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHNG ORD</fullName>
                <label>Change Order Processed, New Order Entered</label>
            </value>
            <value>
                <fullName>CUST REQ</fullName>
                <label>Customer Requested to Cancel Order</label>
            </value>
            <value>
                <fullName>ERROR</fullName>
                <label>Cancel Order Due to Internal Mistake</label>
            </value>
            <value>
                <fullName>NON PMT</fullName>
                <label>Cancel Order Due to Lack of Payment By Customer</label>
            </value>
            <value>
                <fullName>CHG ORDER</fullName>
                <label>Change Order in Process</label>
            </value>
            <value>
                <fullName>CUST HOLD</fullName>
                <label>Waiting for Approval from Customer to Proceed with Production</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFS_ConstructCancelOLineReq.cls
/******************************************************************************************
* Class Name: IFS_ConstructCancelOLineReq
* This class constructs Cancel Order Line XML request from quote line for IFS Integration
******************************************************************************************/
public class IFS_ConstructCancelOLineReq{

    public void IFS_ConstructCancelOLineReq(){
    }
   
    public static String generateReq(SBQQ__QuoteLine__c quoteLine){ 

        XmlStreamWriter xmlStream = new XmlStreamWriter();         
         
        xmlStream.writeStartElement('soap','Envelope','http://schemas.xmlsoap.org/soap/envelope/');
        xmlStream.writeNamespace('soap','http://schemas.xmlsoap.org/soap/envelope/');    
        xmlStream.writeStartElement('soap','Body','');
        xmlStream.writeStartElement('','ORDER_LINE_CANCEL_BLOCK','urn:ifsworld-com:schemas:inbound_sales_force_cpq_int_receive_line_cancel_block_request');// begin order line cancel block
        xmlStream.writeNamespace('xsi','http://www.w3.org/2001/XMLSchema-instance');
        xmlStream.writeNamespace('','urn:ifsworld-com:schemas:inbound_sales_force_cpq_int_receive_line_cancel_block_request');        
        
        xmlStream.writeStartElement('', 'SF_MESSAGE_ID', '');
        xmlStream.writeCharacters('NO_MAPPING'); 
        xmlStream.writeEndElement();
                              
        if(quoteLine.SBQQ__Quote__r.SBQQ__Opportunity2__r.Integration_Message_Counter__c!=NULL){
            xmlStream.writeStartElement('', 'CONTRACT', '');
            xmlStream.writeCharacters(String.valueof(quoteLine.SBQQ__Quote__r.SBQQ__Opportunity2__r.Integration_Message_Counter__c)); 
            xmlStream.writeEndElement();                                    
        }
        if(quoteLine.SBQQ__Quote__r.Order_Number__c!=NULL){
            xmlStream.writeStartElement('', 'ORDER_NO', '');
            xmlStream.writeCharacters(String.valueof(quoteLine.SBQQ__Quote__r.Order_Number__c)); 
            xmlStream.writeEndElement();
        }
        if(quoteLine.Line_Number__c!=NULL || quoteLine.QuoteLineNumber__c!=NULL){
            xmlStream.writeStartElement('', 'LINE_NO', '');            
            if(quoteLine.Line_Number__c!=NULL){
                xmlStream.writeCharacters(String.valueof(quoteLine.Line_Number__c)); 
            }else if(quoteLine.QuoteLineNumber__c!=NULL){
                xmlStream.writeCharacters(String.valueof(quoteLine.QuoteLineNumber__c)); 
            }             
            xmlStream.writeEndElement();
        }
        if(quoteLine.Delivery_Number__c!=NULL){
            xmlStream.writeStartElement('', 'DEL_NO', '');
            //xmlStream.writeCharacters(String.valueof(quoteLine.SBQQ__Number__c));
            xmlStream.writeCharacters(String.valueof(quoteLine.Delivery_Number__c));            
            xmlStream.writeEndElement();
        }        
        if(quoteLine.Change_Order_Status__c!=NULL){
            xmlStream.writeStartElement('', 'STATUS', '');
            xmlStream.writeCharacters(quoteLine.Change_Order_Status__c); 
            xmlStream.writeEndElement();
        }
        if(quoteLine.Status_Reason__c!=NULL){
            xmlStream.writeStartElement('', 'REASON', '');
            xmlStream.writeCharacters(quoteLine.Status_Reason__c); 
            xmlStream.writeEndElement();
        }
        /*if(quoteLine.SBQQ__Quote__r.IFS_Order_Status__c!=NULL){
            xmlStream.writeStartElement('', 'TRANSACTION_STATUS', '');
            xmlStream.writeCharacters(quoteLine.SBQQ__Quote__r.IFS_Order_Status__c); 
            xmlStream.writeEndElement();
        }
        if(quoteLine.SBQQ__Quote__r.Change_Order_Comments__c!=NULL){
            xmlStream.writeStartElement('', 'MESSAGE', '');
            xmlStream.writeCharacters(quoteLine.SBQQ__Quote__r.Change_Order_Comments__c); 
            xmlStream.writeEndElement();
        }*/
                                    
        xmlStream.writeEndElement(); //endof order line cancel block  
        xmlStream.writeEndElement();      // end og body
        xmlStream.writeEndElement();     // end of Envelope         
        //System.debug('Order/Quote Req:'+xmlStream.getXMLString());
        
        String xmlRequest = xmlStream.getXMLString();
        return xmlRequest;        
      }
}