force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Eng_Review_Status__c.field-meta.xml
<CustomField>
    <fullName>Eng_Review_Status__c</fullName>
    <defaultValue>&apos;Not Started&apos;</defaultValue>
    <label>Eng Review Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>In Process</fullName>
            </value>
            <value>
                <fullName>On Hold - Sales</fullName>
            </value>
            <value>
                <fullName>On Hold - Config Issue</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Invalid_Quote_Line_Item_Count__c.field-meta.xml
<CustomField>
    <fullName>Invalid_Quote_Line_Item_Count__c</fullName>
    <label>Invalid Quote Line Item Count</label>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.Is_Expired__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Pending_Engineering_Review_Count__c.field-meta.xml
<CustomField>
    <fullName>Pending_Engineering_Review_Count__c</fullName>
    <label>Pending Engineering Review Count</label>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.Engineering_Status__c</field>
        <operation>equals</operation>
        <value>Requires Approval</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.Line_Status__c</field>
        <operation>equals</operation>
        <value>Primary, Alternate</value>
    </summaryFilterItems>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Pending_Production_Planning_Review_Count__c.field-meta.xml
<CustomField>
    <fullName>Pending_Production_Planning_Review_Count__c</fullName>
    <label>Pending Production Planning Review Count</label>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.Product_Planning_Status__c</field>
        <operation>equals</operation>
        <value>Requires Approval</value>
    </summaryFilterItems>
    <summaryFilterItems>
        <field>SBQQ__QuoteLine__c.Line_Status__c</field>
        <operation>equals</operation>
        <value>Primary, Alternate</value>
    </summaryFilterItems>
    <summaryForeignKey>SBQQ__QuoteLine__c.SBQQ__Quote__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Prod_Planning_Status__c.field-meta.xml
<CustomField>
    <fullName>Prod_Planning_Status__c</fullName>
    <defaultValue>&apos;Not Started&apos;</defaultValue>
    <label>Prod Planning Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>In Review</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Primary__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Primary__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checkbox which if checked designates the quote as the Primary Quote</description>
    <inlineHelpText>Select this checkbox to designate this quote as the primary one on the opportunity and sync quote line items with opportunity line items.</inlineHelpText>
    <label>Primary</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Pending Approvals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SubmitApprovalController.cls
public class SubmitApprovalController {
    
    @AuraEnabled 
    public static ResponseWrapper validateAndSubmitApproval(String quoteId){
        ResponseWrapper rw = new ResponseWrapper();
        SBQQ__Quote__c qt = [
            SELECT Id,Invalid_Quote_Line_Item_Count__c,RecordTypeId,SBQQ__Status__c,SBQQ__Opportunity2__c,SBQQ__Primary__c,
                Eng_Review_Status__c,Pending_Engineering_Review_Count__c,Prod_Planning_Status__c,Pending_Production_Planning_Review_Count__c
            FROM SBQQ__Quote__c
            WHERE Id=:quoteId
            LIMIT 1
        ];
        
        rw.message += (qt.Prod_Planning_Status__c != 'Completed' && qt.Pending_Production_Planning_Review_Count__c > 0) ?
            'There are ' + String.valueOf(qt.Pending_Production_Planning_Review_Count__c) + ' line items that require Prod Planning Review\n' : '';
        rw.message += (qt.Eng_Review_Status__c != 'Completed' && qt.Pending_Engineering_Review_Count__c > 0) ?
            'There are ' + String.valueOf(qt.Pending_Engineering_Review_Count__c) + ' line items that require Engineering Review\n' : '';
        //"message": 'Cannot Submit. Invalid Quote Line Count greater than zero!',
        //"message": 'Engineering and Product Planning Reviews must be complete before submitting this Quote',
        rw.status = String.isBlank(rw.message) ? 'SUCCESS' : 'ERROR';
        if(String.isBlank(rw.message)) {
            qt.SBQQ__Primary__c = true;
            upsert qt;
        }
        return rw;
    }
}