force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Comments__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Comments__c</fullName>
    <label>Change Order Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Status__c</fullName>
    <label>Change Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Change Order Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IFS_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>IFS_Order_Status__c</fullName>
    <defaultValue>&quot;Not Submitted&quot;</defaultValue>
    <label>IFS Order Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <formula>TEXT( Sales_Division__c )&amp;RIGHT(Quote_Number__c,LEN(Quote_Number__c)-2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Pending Approvals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IFS_ConstructCancelOrderReqTest.cls
@isTest
private class IFS_ConstructCancelOrderReqTest{          
   static testMethod void generateReq(){
        Test.startTest();
        IFS_TestDataFactory.createTestRecords();    
        Account accLst = [Select Id,Name FROM Account WHERE Name='TEMCO INC TEST' limit 1]; 
        SBQQ__Quote__c  quote = [Select Id,Name,SBQQ__Account__c,SBQQ__Opportunity2__r.Integration_Message_Counter__c,Order_Number__c,SBQQ__Status__c,Status_Reason__c,IFS_Order_Status__c,Change_Order_Comments__c,Change_Order_Status__c FROM SBQQ__Quote__c  WHERE SBQQ__Account__c=:accLst.Id limit 1];
        quote.Change_Order_Status__c='Cancel';
        quote.Status_Reason__c='CHG ORDER';
        IFS_ConstructCancelOrderReq.generateReq(quote);
        Test.stopTest();
    }
}