force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Comments__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Comments__c</fullName>
    <label>Change Order Comments</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_Status__c</fullName>
    <label>Change Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Change Order Initiated</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/IFS_Order_Status__c.field-meta.xml
<CustomField>
    <fullName>IFS_Order_Status__c</fullName>
    <defaultValue>&quot;Not Submitted&quot;</defaultValue>
    <label>IFS Order Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <formula>TEXT( Sales_Division__c )&amp;RIGHT(Quote_Number__c,LEN(Quote_Number__c)-2)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Order Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/IFS_ConstructCancelOrderReq.cls
/*********************************************************************************
* Class Name: IFS_ConstructCancelOrderReq
* This class constructs Cancel Order XML request from quote for IFS Integration
*********************************************************************************/
public class IFS_ConstructCancelOrderReq{

    public void IFS_ConstructCancelOrderReq(){
    }
    
    public static String generateReq(SBQQ__Quote__c quote){
        XmlStreamWriter xmlStream = new XmlStreamWriter();       
        xmlStream.writeStartElement('soap','Envelope','http://schemas.xmlsoap.org/soap/envelope/');
        xmlStream.writeNamespace('soap','http://schemas.xmlsoap.org/soap/envelope/');    
        xmlStream.writeStartElement('soap','Body','');
        xmlStream.writeStartElement('','ORDER_CANCEL_BLOCK','urn:ifsworld-com:schemas:inbound_sales_force_cpq_int_receive_order_cancel_block_request');// begin ORDER_CANCEL_BLOCK
        xmlStream.writeNamespace('xsi','http://www.w3.org/2001/XMLSchema-instance');
        xmlStream.writeNamespace('','urn:ifsworld-com:schemas:inbound_sales_force_cpq_int_receive_order_cancel_block_request');         
        
        xmlStream.writeStartElement('', 'SF_MESSAGE_ID', '');
        xmlStream.writeCharacters('NO_MAPPING'); 
        xmlStream.writeEndElement();
                               
        if(quote.SBQQ__Opportunity2__r.Integration_Message_Counter__c!=NULL){ 
            xmlStream.writeStartElement('', 'CONTRACT', '');
            xmlStream.writeCharacters(String.valueof(quote.SBQQ__Opportunity2__r.Integration_Message_Counter__c)); 
            xmlStream.writeEndElement();
        }
        if(quote.Order_Number__c!=NULL){
            xmlStream.writeStartElement('', 'ORDER_NO', '');
            xmlStream.writeCharacters(quote.Order_Number__c); 
            xmlStream.writeEndElement();
        }
        if(quote.Change_Order_Status__c!=NULL){
            xmlStream.writeStartElement('', 'STATUS', '');
            xmlStream.writeCharacters(quote.Change_Order_Status__c); 
            xmlStream.writeEndElement();
        }                                    
        if(quote.Status_Reason__c!=NULL){
            xmlStream.writeStartElement('', 'REASON', '');
            xmlStream.writeCharacters(quote.Status_Reason__c); 
            xmlStream.writeEndElement();
        }
        /*if(quote.IFS_Order_Status__c!=NULL){
            xmlStream.writeStartElement('', 'TRANSACTION_STATUS', '');
            xmlStream.writeCharacters(quote.IFS_Order_Status__c); 
            xmlStream.writeEndElement();
        }
        if(quote.Change_Order_Comments__c!=NULL){
            xmlStream.writeStartElement('', 'MESSAGE', '');
            xmlStream.writeCharacters(quote.Change_Order_Comments__c); 
            xmlStream.writeEndElement();
        }*/
                                    
        xmlStream.writeEndElement(); // end of ORDER_CANCEL_BLOCK 
        xmlStream.writeEndElement();      // end of body
        xmlStream.writeEndElement();      // end of Envelope        
        //System.debug('Order/Quote Req:'+xmlStream.getXMLString());
        
        String xmlRequest = xmlStream.getXMLString();
        return xmlRequest;
    }
}