force-app/main/default/objects/Relief_Valve__c/Relief_Valve__c.object-meta.xml
<CustomObject>
    <description>Relief valves custom object</description>
    <label>Relief Valve</label>
    <nameField>
        <displayFormat>RV-{0000}</displayFormat>
        <label>Relief Valve Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relief Valves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Relief_Valve__c/fields/Body_Coating_Material__c.field-meta.xml
<CustomField>
    <fullName>Body_Coating_Material__c</fullName>
    <label>Body Coating Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Body_Material__c.field-meta.xml
<CustomField>
    <fullName>Body_Material__c</fullName>
    <label>Body Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Brinell_hardness_examination__c.field-meta.xml
<CustomField>
    <fullName>Brinell_hardness_examination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brinell hardness examination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Charpy_Impact_Testing__c.field-meta.xml
<CustomField>
    <fullName>Charpy_Impact_Testing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Charpy Impact Testing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Constraint_Product_Selection_By_Flow__c.field-meta.xml
<CustomField>
    <fullName>Constraint_Product_Selection_By_Flow__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Filter Product Selection by Flow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Diaphragm_Material__c.field-meta.xml
<CustomField>
    <fullName>Diaphragm_Material__c</fullName>
    <label>Diaphragm Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Drilling__c.field-meta.xml
<CustomField>
    <fullName>Drilling__c</fullName>
    <label>Drilling</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Element_Material__c.field-meta.xml
<CustomField>
    <fullName>Element_Material__c</fullName>
    <label>Element Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Fastener_Material__c.field-meta.xml
<CustomField>
    <fullName>Fastener_Material__c</fullName>
    <label>Fastener Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Field_Test_Connection__c.field-meta.xml
<CustomField>
    <fullName>Field_Test_Connection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Field Test Connection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Fillet_Weld_Liquid_Dye_Penetrant__c.field-meta.xml
<CustomField>
    <fullName>Fillet_Weld_Liquid_Dye_Penetrant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fillet Weld-Liquid Dye Penetrant</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Flame_Arrester_Option__c.field-meta.xml
<CustomField>
    <fullName>Flame_Arrester_Option__c</fullName>
    <label>Flame Arrester Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Intergranular_Corossion_Test__c.field-meta.xml
<CustomField>
    <fullName>Intergranular_Corossion_Test__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Intergranular Corrosion Test</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Liquid_Dye_Penetrant__c.field-meta.xml
<CustomField>
    <fullName>Liquid_Dye_Penetrant__c</fullName>
    <label>Liquid Dye Penetrant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Magnetic_Particle_Examination__c.field-meta.xml
<CustomField>
    <fullName>Magnetic_Particle_Examination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Magnetic Particle Examination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Manual_Blowdown__c.field-meta.xml
<CustomField>
    <fullName>Manual_Blowdown__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Manual Blowdown</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Method21_Leak_Detection__c.field-meta.xml
<CustomField>
    <fullName>Method21_Leak_Detection__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Method21 Leak Detection</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Painting_Coating_Option__c.field-meta.xml
<CustomField>
    <fullName>Painting_Coating_Option__c</fullName>
    <label>Painting/Coating Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pallet_Fastener_Coating_Material__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Fastener_Coating_Material__c</fullName>
    <label>Pallet/Fastener Coating Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pallet_Type__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Type__c</fullName>
    <label>Pallet Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pilot_Action__c.field-meta.xml
<CustomField>
    <fullName>Pilot_Action__c</fullName>
    <label>Pilot Action</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pilot_Exhaust_Piped_to_Discharge_Header__c.field-meta.xml
<CustomField>
    <fullName>Pilot_Exhaust_Piped_to_Discharge_Header__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pilot Exhaust Piped to Discharge Header</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pilot_Soft_Goods_Material__c.field-meta.xml
<CustomField>
    <fullName>Pilot_Soft_Goods_Material__c</fullName>
    <label>Pilot Soft Goods Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pilot_Supply_Filter__c.field-meta.xml
<CustomField>
    <fullName>Pilot_Supply_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pilot Supply Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Positive_Material_Identification__c.field-meta.xml
<CustomField>
    <fullName>Positive_Material_Identification__c</fullName>
    <label>Positive Material Identification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pressure_Pallet_Material__c.field-meta.xml
<CustomField>
    <fullName>Pressure_Pallet_Material__c</fullName>
    <label>Pressure Pallet Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Pressure_Port_Proximity_Sensor__c.field-meta.xml
<CustomField>
    <fullName>Pressure_Port_Proximity_Sensor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pressure Port Proximity Sensor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Radiography__c.field-meta.xml
<CustomField>
    <fullName>Radiography__c</fullName>
    <label>Radiography</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Remote_Sense__c.field-meta.xml
<CustomField>
    <fullName>Remote_Sense__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Remote Sense</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Seat_Material__c.field-meta.xml
<CustomField>
    <fullName>Seat_Material__c</fullName>
    <label>Seat Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Spring_Material__c.field-meta.xml
<CustomField>
    <fullName>Spring_Material__c</fullName>
    <label>Spring Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Steam_Jacket_Material__c.field-meta.xml
<CustomField>
    <fullName>Steam_Jacket_Material__c</fullName>
    <label>Steam Jacket Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Ultrasonic_Examination__c.field-meta.xml
<CustomField>
    <fullName>Ultrasonic_Examination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ultrasonic Examination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Vacuum_Pallet_Material__c.field-meta.xml
<CustomField>
    <fullName>Vacuum_Pallet_Material__c</fullName>
    <label>Vacuum Pallet Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Vacuum_Port_Option__c.field-meta.xml
<CustomField>
    <fullName>Vacuum_Port_Option__c</fullName>
    <label>Vacuum Port Option</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Vacuum_Port_Proximity_Sensor__c.field-meta.xml
<CustomField>
    <fullName>Vacuum_Port_Proximity_Sensor__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Vacuum Port Proximity Sensor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Visual_Casting_Examination__c.field-meta.xml
<CustomField>
    <fullName>Visual_Casting_Examination__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Visual Casting Examination</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Relief_Valve__c/fields/Weight_Material__c.field-meta.xml
<CustomField>
    <fullName>Weight_Material__c</fullName>
    <label>Weight Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RV_Input_Attr_Value_Desc__c/RV_Input_Attr_Value_Desc__c.object-meta.xml
<CustomObject>
    <label>RV Input Attr Value Desc</label>
    <nameField>
        <label>RV Input Attr Value Desc</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RV Input Attr Value Desc</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RV_Input_Attr_Value_Desc__c/fields/Text_Description_of_AttributeValue__c.field-meta.xml
<CustomField>
    <fullName>Text_Description_of_AttributeValue__c</fullName>
    <label>Text Description of Attribute/Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/configRVReferenceCtrl.cls
public class configRVReferenceCtrl 
{
    public Relief_Valve__c oRV{get;set;}
    public User oUser {get;set;}
    public string getUserTimeZone()
    {
        return userinfo.getTimeZone().toString();
    }
    
    public configRVReferenceCtrl(ApexPages.StandardController controller)
    {
        if (!Test.isRunningTest()) { 
        controller.addFields(new String[]{'Drilling__c','Body_Material__c','Facing__c','Seat_Material__c','Pressure_Pallet_Material__c','Pallet_Type__c','Diaphragm_Material__c','Vacuum_Pallet_Material__c',
            'Pilot_Soft_Goods_Material__c','Weight_Material__c','Spring_Material__c','Fastener_Material__c','Steam_Jacket_Material__c','Painting_Coating_Option__c',
            'Body_Coating_Material__c','Pallet_Fastener_Coating_Material__c','Element_Material__c','Flame_Arrester_Option__c','Vacuum_Port_Option__c','Pressure_Port_Proximity_Sensor__c',
            'Vacuum_Port_Proximity_Sensor__c','Pilot_Action__c','Manual_Blowdown__c','Remote_Sense__c',
            'Pilot_Exhaust_Piped_to_Discharge_Header__c','Field_Test_Connection__c','Pilot_Supply_Filter__c',
            'Method21_Leak_Detection__c','Radiography__c','Fillet_Weld_Liquid_Dye_Penetrant__c','Liquid_Dye_Penetrant__c',
            'Positive_Material_Identification__c','Ultrasonic_Examination__c','Magnetic_Particle_Examination__c',
            'Brinell_hardness_examination__c','Charpy_Impact_Testing__c','Visual_Casting_Examination__c','Intergranular_Corossion_Test__c',
            'Constraint_Product_Selection_By_Flow__c'});
        }
        oRV = (Relief_Valve__c)controller.getRecord();    
        for(User u : [Select Id,Name From User Where Id =: userinfo.getUserId()]){
            oUser = u;
        }
    }
    
     private string fetchInputAttributeDesc(string att, string sVal)
     {
         List<RV_Input_Attr_Value_Desc__c > inputvaluesList=[select id,Text_Description_of_AttributeValue__c,Attribute__c,Value__c
                                                             from RV_Input_Attr_Value_Desc__c
                                                             where Attribute__c = : att 
                                                             and value__c = : sVal LIMIT 1
                                                            ];
         if(inputvaluesList.size() > 0)
         {
             return  inputvaluesList[0].Text_Description_of_AttributeValue__c;
         }
         else
         {
             return null;
         }
     }
    
    public string HCLASS{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('HCLASS',oRV.Drilling__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.HCLASS=value;
        }
    }
        
	public string MCBODY{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCBODY',oRV.Body_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCBODY=value;
        }
    }
    
    public string GPFACE{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('GPFACE',oRV.Facing__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.GPFACE=value;
        }
    }
    
    public string MCSEAT{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCSEAT',oRV.Seat_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCSEAT=value;
        }
    }
    
    public string MCPALL{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCPALL',oRV.Pressure_Pallet_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCPALL=value;
        }
    }
    
    public string MCDPHM{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCDPHM',oRV.Diaphragm_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCDPHM=value;
        }
    }
    
    public string MCVALL{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCPALL',oRV.Vacuum_Pallet_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCVALL=value;
        }
    }
    
    public string MCPSGD{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCPSGD',oRV.Pilot_Soft_Goods_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCPSGD=value;
        }
    }
    
    public string MCWGHT{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCWGHT',oRV.Weight_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCWGHT=value;
        }
    }
    
    public string MCSPRG{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCSPRG',oRV.Spring_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCSPRG=value;
        }
    }
    
    public string MCSTMJ{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCSTMJ',oRV.Steam_Jacket_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCSTMJ=value;
        }
    }
    
    public string MCCOTB{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCCOTB',oRV.Body_Coating_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCCOTB=value;
        }
    }
    
    public string MCCOTP{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCCOTP',oRV.Pallet_Fastener_Coating_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCCOTP=value;
        }
    }
    
    public string MCELMT{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('MCELMT',oRV.Element_Material__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.MCELMT=value;
        }
    }
    
    public string VPRTOP{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('VPRTOP',oRV.Vacuum_Port_Option__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.VPRTOP=value;
        }
    }
    
    public string PMI{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('PMI',oRV.Positive_Material_Identification__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.PMI=value;
        }
    }
    
    public string LDP{
        get{
				string labelval='';
            	labelval=fetchInputAttributeDesc('LDP',oRV.Liquid_Dye_Penetrant__c);
            	if(labelval!=null)
					return labelval;
			    else
					return ' ';
        }
        set{
            this.LDP=value;
        }
    }
    
    
}