force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>QC-{0000000000}</displayFormat>
        <label>Charge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount in Customer Currency</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Amount_Updated__c.field-meta.xml
<CustomField>
    <fullName>Amount_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Amount Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Parent_Quote__c.field-meta.xml
<CustomField>
    <fullName>Parent_Quote__c</fullName>
    <label>Parent Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Previous_Amount__c.field-meta.xml
<CustomField>
    <fullName>Previous_Amount__c</fullName>
    <label>Previous Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Previous_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Previous_Quantity__c</fullName>
    <label>Previous Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Quantity_Updated__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quantity Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>Sequence</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Charged&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
                <default>true</default>
                <label>Charged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Status_Updated__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Status Updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOCUMENTATION</fullName>
                <label>Order Document Charge</label>
            </value>
            <value>
                <fullName>FIELD SERVICE</fullName>
                <label>Field Service Charge</label>
            </value>
            <value>
                <fullName>FLOW LAB</fullName>
                <label>Flow Lab Testing Charge</label>
            </value>
            <value>
                <fullName>PROCESSING CHARGE</fullName>
                <label>Product Processing Charge</label>
            </value>
            <value>
                <fullName>REDBALL FEE</fullName>
                <label>Expedited Service Charge</label>
            </value>
            <value>
                <fullName>RESTOCK</fullName>
                <label>Restock Charge For Returned Material</label>
            </value>
            <value>
                <fullName>SHIPPING</fullName>
                <label>Shipping Charge</label>
            </value>
            <value>
                <fullName>CANCELLATION</fullName>
                <label>Cancellation Charge</label>
            </value>
            <value>
                <fullName>START UP</fullName>
                <label>Start Up Charge</label>
            </value>
            <value>
                <fullName>NUCLEAR</fullName>
                <label>Nuclear Charge</label>
            </value>
            <value>
                <fullName>ITAR CHARGE</fullName>
                <label>ITAR Charge</label>
            </value>
            <value>
                <fullName>EAR CHARGE</fullName>
                <label>EAR Charge</label>
            </value>
            <value>
                <fullName>SPECIAL PACKING</fullName>
                <label>Special Packing Charge</label>
            </value>
            <value>
                <fullName>SET UP</fullName>
                <label>Set Up Charge</label>
            </value>
            <value>
                <fullName>WARRANTY</fullName>
                <label>Warranty Charge</label>
            </value>
            <value>
                <fullName>DEVELOPMENT</fullName>
                <label>Development Charge</label>
            </value>
            <value>
                <fullName>STORAGE</fullName>
                <label>Storage Charges</label>
            </value>
            <value>
                <fullName>ATTESTATION</fullName>
                <label>Document Attestation Charge</label>
            </value>
            <value>
                <fullName>CHANGE</fullName>
                <label>Change Order Charge</label>
            </value>
            <value>
                <fullName>INSPECTION</fullName>
                <label>Source Inspection Charge</label>
            </value>
            <value>
                <fullName>CERTIFICATION</fullName>
                <label>Certification Charge</label>
            </value>
            <value>
                <fullName>HANDLING</fullName>
                <label>Handling Charge</label>
            </value>
            <value>
                <fullName>BOND</fullName>
                <label>Bank Bonds</label>
            </value>
            <value>
                <fullName>MISC</fullName>
                <label>Miscellaneous Charge</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Update__c.field-meta.xml
<CustomField>
    <fullName>Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Credits_and_Booking__c/Credits_and_Booking__c.object-meta.xml
<CustomObject>
    <label>Credits and Booking</label>
    <nameField>
        <displayFormat>CB-{0000}</displayFormat>
        <label>Credits and Booking Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Credits and Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Credits_and_Booking__c/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Field Service</fullName>
            </value>
            <value>
                <fullName>Flow Lab Testing</fullName>
            </value>
            <value>
                <fullName>Processing Charge</fullName>
            </value>
            <value>
                <fullName>Redball Fee</fullName>
            </value>
            <value>
                <fullName>Restock Fee</fullName>
            </value>
            <value>
                <fullName>Shipping</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Credits_and_Booking__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <defaultValue>now()</defaultValue>
    <label>Created Date Manual</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Credits_and_Booking__c/fields/Goals_Performance__c.field-meta.xml
<CustomField>
    <fullName>Goals_Performance__c</fullName>
    <label>Goals &amp; Performance</label>
    <referenceTo>Goals_Performance__c</referenceTo>
    <relationshipLabel>Credits and Bookings</relationshipLabel>
    <relationshipName>Credits_and_Bookings</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Credits_and_Booking__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Credits and Bookings</relationshipLabel>
    <relationshipName>Credits_and_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Credits_and_Booking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Credit</fullName>
                <default>true</default>
                <label>Credit</label>
            </value>
            <value>
                <fullName>Booking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Goals_Performance__c/Goals_Performance__c.object-meta.xml
<CustomObject>
    <label>Goals &amp; Performance</label>
    <nameField>
        <displayFormat>GP-{00000}</displayFormat>
        <label>Goals &amp; Performance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Goals &amp; Performance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ChargeUpsertBookingAndCharges.cls
public class ChargeUpsertBookingAndCharges {
    public static void upsertCandB(List<Charge__c> chargeLst){
        List<Credits_and_Booking__c> candbList = new List<Credits_and_Booking__c>();
        
        Id gandpId = [select id from Goals_Performance__c limit 1].Id;
        
        list<Charge__c> lstChargeToUpdate = new list<Charge__c>();
        for(Charge__c c : chargeLst){
            //charge key fields are updated
            
            if(c.Update__c || c.Status_Updated__c || c.Quantity_Updated__c || c.Amount_Updated__c){
                Credits_and_Booking__c cb = new Credits_and_Booking__c();
                cb.Created_Date__c = system.now();
                cb.Type__c = 'Booking';
                cb.Quote__c = c.Parent_Quote__c;
                system.debug('Seq #: =>' + c.Sequence__c);
                cb.External_Id__c = c.Sequence__c;
                cb.Goals_Performance__c = gandpId;
                cb.Charge_Type__c = c.Type__c;
                
                if(c.Status_Updated__c ){
                    if(c.Status__c == 'Cancelled'){ //create new booking with -ve amount
                        cb.Amount__c = -1 * c.Amount__c * c.Quantity__c; //negative booking
                    }
                    else{ //create new booking with +ve amount
                        cb.Amount__c = c.Amount__c * c.Quantity__c; 
                    }
                    candbList.add(cb);
                }
                else if(c.Amount_Updated__c || c.Quantity_Updated__c ){
                    decimal previousCBAmount;
                    decimal currentCBAmount;
                    System.debug('@Developer --> c.Previous_Amount__c :' + c.Previous_Amount__c);
                    System.debug('@Developer --> c.Amount__c :' + c.Amount__c);
                    
                    System.debug('@Developer --> c.Previous_Quantity__c :' + c.Previous_Quantity__c);
                    System.debug('@Developer --> c.Amount__c :' + c.Amount__c);
                    
                    if(c.Amount_Updated__c && c.Quantity_Updated__c ){
                        previousCBAmount = c.Previous_Amount__c * c.Previous_Quantity__c;
                        currentCBAmount = c.Amount__c * c.Quantity__c;
                    }
                    else if(c.Amount_Updated__c && !c.Quantity_Updated__c ){
                        previousCBAmount = c.Previous_Amount__c * c.Quantity__c;
                        currentCBAmount = c.Amount__c * c.Quantity__c;
                    }
                    else if(!c.Amount_Updated__c && c.Quantity_Updated__c ){
                        previousCBAmount = c.Amount__c * c.Previous_Quantity__c;
                        currentCBAmount = c.Amount__c * c.Quantity__c;
                    }
                    System.debug('@Developer --> previousCBAmount :' + previousCBAmount);
                    System.debug('@Developer --> currentCBAmount :' + currentCBAmount);
                    
                    if(currentCBAmount != previousCBAmount){
                        if(currentCBAmount > previousCBAmount){
                            //incremental booking
                            cb.Amount__c = currentCBAmount - previousCBAmount;
                        }
                        else if(previousCBAmount > currentCBAmount ){
                            //negative booking
                            cb.Amount__c = -1 * (previousCBAmount - currentCBAmount);
                        }
                        candbList.add(cb);
                    }
                }
                c.Status_Updated__c = false;    
                c.Quantity_Updated__c = false;
                c.Amount_Updated__c = false;
                lstChargeToUpdate.add(c);
            }
            else { // new charge created
                if(c.Status__c != 'Cancelled'){ // it must not be cancelled
                    Credits_and_Booking__c cb = new Credits_and_Booking__c();
                    cb.Amount__c = c.Amount__c * c.Quantity__c;
                    cb.Created_Date__c = system.now();
                    cb.Type__c = 'Booking';
                    cb.Quote__c = c.Parent_Quote__c;
                    system.debug('Seq #: =>' + c.Sequence__c);
                    cb.External_Id__c = c.Sequence__c;
                    cb.Goals_Performance__c = gandpId;
                    cb.Charge_Type__c = c.Type__c;
                    candbList.add(cb);
                    c.Update__c = true;
                    lstChargeToUpdate.add(c);
                }
            }
        }
        
        if(!candbList.isEmpty()) {
            upsert candbList;
        }
        
        if(lstChargeToUpdate.size() > 0){
            update lstChargeToUpdate;
        }
    }
}