force-app/main/default/objects/Charge__c/Charge__c.object-meta.xml
<CustomObject>
    <label>Charge</label>
    <nameField>
        <displayFormat>QC-{0000000000}</displayFormat>
        <label>Charge</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Charges</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Charge__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount in Customer Currency</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Amount_Cust_Curr__c.field-meta.xml
<CustomField>
    <fullName>Amount_Cust_Curr__c</fullName>
    <formula>Amount__c * CURRENCYRATE(TEXT(  Parent_Quote__r.Currency__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount (Cust. Curr.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Parent_Quote__c.field-meta.xml
<CustomField>
    <fullName>Parent_Quote__c</fullName>
    <label>Parent Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Charges</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Quote_Customer_Currency__c.field-meta.xml
<CustomField>
    <fullName>Quote_Customer_Currency__c</fullName>
    <formula>Parent_Quote__r.DocumentCurrencySymbol__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Customer Currency</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Charged&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Charged</fullName>
                <default>true</default>
                <label>Charged</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Total_Charge__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge__c</fullName>
    <formula>(Amount__c  /  Exchange_Rate__c) * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Total_Charge_Cust_Curr__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge_Cust_Curr__c</fullName>
    <formula>Total_Charge__c * CURRENCYRATE(TEXT(  Parent_Quote__r.Currency__c  ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Charge (Cust. Curr.)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Total_Charge_Cust_Curr_Flow__c.field-meta.xml
<CustomField>
    <fullName>Total_Charge_Cust_Curr_Flow__c</fullName>
    <label>Total Charge (Cust.Curr.) (Flow)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Charge__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOCUMENTATION</fullName>
                <label>Order Document Charge</label>
            </value>
            <value>
                <fullName>FIELD SERVICE</fullName>
                <label>Field Service Charge</label>
            </value>
            <value>
                <fullName>FLOW LAB</fullName>
                <label>Flow Lab Testing Charge</label>
            </value>
            <value>
                <fullName>PROCESSING CHARGE</fullName>
                <label>Product Processing Charge</label>
            </value>
            <value>
                <fullName>REDBALL FEE</fullName>
                <label>Expedited Service Charge</label>
            </value>
            <value>
                <fullName>RESTOCK</fullName>
                <label>Restock Charge For Returned Material</label>
            </value>
            <value>
                <fullName>SHIPPING</fullName>
                <label>Shipping Charge</label>
            </value>
            <value>
                <fullName>CANCELLATION</fullName>
                <label>Cancellation Charge</label>
            </value>
            <value>
                <fullName>START UP</fullName>
                <label>Start Up Charge</label>
            </value>
            <value>
                <fullName>NUCLEAR</fullName>
                <label>Nuclear Charge</label>
            </value>
            <value>
                <fullName>ITAR CHARGE</fullName>
                <label>ITAR Charge</label>
            </value>
            <value>
                <fullName>EAR CHARGE</fullName>
                <label>EAR Charge</label>
            </value>
            <value>
                <fullName>SPECIAL PACKING</fullName>
                <label>Special Packing Charge</label>
            </value>
            <value>
                <fullName>SET UP</fullName>
                <label>Set Up Charge</label>
            </value>
            <value>
                <fullName>WARRANTY</fullName>
                <label>Warranty Charge</label>
            </value>
            <value>
                <fullName>DEVELOPMENT</fullName>
                <label>Development Charge</label>
            </value>
            <value>
                <fullName>STORAGE</fullName>
                <label>Storage Charges</label>
            </value>
            <value>
                <fullName>ATTESTATION</fullName>
                <label>Document Attestation Charge</label>
            </value>
            <value>
                <fullName>CHANGE</fullName>
                <label>Change Order Charge</label>
            </value>
            <value>
                <fullName>INSPECTION</fullName>
                <label>Source Inspection Charge</label>
            </value>
            <value>
                <fullName>CERTIFICATION</fullName>
                <label>Certification Charge</label>
            </value>
            <value>
                <fullName>HANDLING</fullName>
                <label>Handling Charge</label>
            </value>
            <value>
                <fullName>BOND</fullName>
                <label>Bank Bonds</label>
            </value>
            <value>
                <fullName>MISC</fullName>
                <label>Miscellaneous Charge</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/Change_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_No__c</fullName>
    <label>Change Order No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Change_Order_No__c.field-meta.xml
<CustomField>
    <fullName>Change_Order_No__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Change Order No</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/DisplayCDCLogo__c.field-meta.xml
<CustomField>
    <fullName>DisplayCDCLogo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display CDC Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/DisplayGrothContinentalLogo__c.field-meta.xml
<CustomField>
    <fullName>DisplayGrothContinentalLogo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Groth Continental Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/DisplayGrothLogo__c.field-meta.xml
<CustomField>
    <fullName>DisplayGrothLogo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Groth Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/DisplayLaMotLogo__c.field-meta.xml
<CustomField>
    <fullName>DisplayLaMotLogo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display LaMot Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/DisplayLVALogo__c.field-meta.xml
<CustomField>
    <fullName>DisplayLVALogo__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display LVA Logo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Number__c</fullName>
    <label>Original Quote Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimB__c.field-meta.xml
<CustomField>
    <fullName>DimB__c</fullName>
    <label>DimB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimC__c.field-meta.xml
<CustomField>
    <fullName>DimC__c</fullName>
    <label>DimC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimF__c.field-meta.xml
<CustomField>
    <fullName>DimF__c</fullName>
    <label>DimF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DrawingID__c.field-meta.xml
<CustomField>
    <fullName>DrawingID__c</fullName>
    <description>This field will have the name of static resource</description>
    <label>DrawingID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Drawings_Status__c.field-meta.xml
<CustomField>
    <fullName>Drawings_Status__c</fullName>
    <label>Drawings Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>Required</fullName>
            </value>
            <value>
                <fullName>Attached</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <defaultValue>&quot;Primary&quot;</defaultValue>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DrawingsCtrl.cls
public class DrawingsCtrl {
    private string quoteId;
    public SBQQ__Quote__c oQuote {get;set;}
    public list<SBQQ__QuoteLine__c> lstQuoteLine {get;set;}
    public list<Charge__c> lstCharge {get;set;} 
    public map<String,String> mapImageData {get;set;}
    public map<String,List<String>> mapDescription {get;set;}
    public string baseURL {get;set;}
    
    private string logoName = '';
    public string logo {get;set;}
    
    public DrawingsCtrl(){
        System.debug('@Developer -->DrawingsCtrl:' );
    }
    
    public PageReference init(){
            System.debug('@Developer -->init:' );
        
        if(ApexPages.currentPage().getParameters().get('qid') != null){
            quoteId = ApexPages.currentPage().getParameters().get('qid');    
            System.debug('@Developer --> quoteId :' + quoteId);

            //baseURL = 'https://' + ApexPages.currentPage().getHeaders().get('Host') + '/servlet/servlet.ImageServer?oid=' + userInfo.getOrganizationId() + '&id=';
            //baseURL = 'https://contdisccorp--uat--c.cs66.content.force.com/servlet/servlet.ImageServer?oid=' + userInfo.getOrganizationId() + '&id=';
            baseURL = URL.getSalesforceBaseUrl().toExternalForm() + '/servlet/servlet.ImageServer?oid=' + userInfo.getOrganizationId() + '&id=';
            System.debug('@Developer --> baseURL :' + baseURL);
            
            mapDescription = new map<String,list<String>>();
            
            set<string> setDrawingId = new set<String>();
            
            for(SBQQ__Quote__c qt : [SELECT Id,Name,Quote_Number__c,Change_Order_No__c,
                                     DisplayCDCLogo__c, DisplayGrothContinentalLogo__c, DisplayGrothLogo__c, 
                                     DisplayLaMotLogo__c, DisplayLVALogo__c,
                                     (SELECT Id,Name,DimA__c, DimB__c, DimC__c, DimD__c,DimE__c, DimF__c,SBQQ__Number__c,  
                                      DrawingID__c, Drawings_Status__c, SBQQ__Description__c 
                                      FROM SBQQ__LineItems__r
                                      WHERE Line_Status__c in ('Primary','Alternate')
                                      ORDER BY CreatedDate DESC
                                     )
                                     FROM SBQQ__Quote__c
                                     WHERE Id = :quoteId
                                    ])
            {
                oQuote = qt;
                if(qt.DisplayCDCLogo__c){
                	logoName = 'CDC Logo New';    
                }
                else if(qt.DisplayGrothContinentalLogo__c){
                	logoName = 'groth continental manufacturing pvt ltdNew';    
                }
                else if(qt.DisplayGrothLogo__c){
                	logoName = 'grothLogoNew';    
                }
                else if(qt.DisplayLaMotLogo__c){
                	logoName = 'laMotLogoNew';    
                }
                else if(qt.DisplayLVALogo__c){
                	logoName = 'lamot_LVA_logo.pngNEW';    
                }
                
                lstQuoteLine = new list<SBQQ__QuoteLine__c>();
                for(SBQQ__QuoteLine__c qln : qt.SBQQ__LineItems__r){
                    System.debug('@Developer --> qln :' + qln);
                    if(qln.DrawingID__c != null){
                        setDrawingId.add(qln.DrawingID__c);
                    }
                    lstQuoteLine.add(qln);
                    
                    //qln.SBQQ__Description__c = qln.SBQQ__Description__c.replaceAll('<[^>]+>',' ');
                    if(qln.SBQQ__Description__c != null ){
                        list<String> lstDesc = new list<String>();
                        list<String> lstTmp = qln.SBQQ__Description__c.split('<br>');
                        Integer nCount = lstTmp.size() > 20 ? 20 : lstTmp.size();
                        for(integer indx=0; indx < nCount; indx++){
                            String sTmp = lstTmp[indx];
                            if(sTmp != null && sTmp != ''){
                                lstDesc.add(sTmp); 
                            }
                        }
                        mapDescription.put(qln.Id,lstDesc);
                    }
                    else{
                    	mapDescription.put(qln.Id,new list<String>());    
                    }
                }
            }
            
            setDrawingId.add(logoName);
            mapImageData = new map<String,String>();
            for(String sDrawingId :setDrawingId){
                System.debug('@Developer --> sDrawingId :' + sDrawingId);
                mapImageData.put(sDrawingId,' ');
            }
            for(Document doc : [SELECT Id,Name FROM Document WHERE Name IN :setDrawingId And Name != '9999']){
                mapImageData.put(doc.Name,baseURL + doc.Id);
            }
            System.debug('@Developer --> mapImageData :' + mapImageData);
            
            System.debug('@Developer --> logoName :' + logoName);
            if(mapImageData.containsKey(logoName)){
                logo = mapImageData.get(logoName);
                System.debug('@Developer --> logo :' + logo);
            }
            
            lstCharge = [SELECT Id, Amount__c, Quantity__c, Type__c, Status__c,Total_Charge__c,Quote_Customer_Currency__c,
                         Total_Charge_Cust_Curr__c,Amount_Cust_Curr__c,Total_Charge_Cust_Curr_Flow__c
                         FROM Charge__c 
                         WHERE Parent_Quote__c =:quoteId
                         ORDER BY CreatedDate];
            System.debug('@Developer --> lstCharge :' + lstCharge);
        }
        else{
            System.debug('@Developer -->Invalid quote reference:' );
        }
        return null;
    }
}