force-app/main/default/objects/Part_Selector__c/Part_Selector__c.object-meta.xml
<CustomObject>
    <label>Part Selector</label>
    <nameField>
        <label>Part Selector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Selectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Selector__c/fields/OA__c.field-meta.xml
<CustomField>
    <fullName>OA__c</fullName>
    <label>OA</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/OB__c.field-meta.xml
<CustomField>
    <fullName>OB__c</fullName>
    <label>OB</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/OW__c.field-meta.xml
<CustomField>
    <fullName>OW__c</fullName>
    <label>OW</label>
    <length>131070</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Quote_Description_Engineer_Override__c.field-meta.xml
<CustomField>
    <fullName>Quote_Description_Engineer_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Description Engineer Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Part Selectors</relationshipLabel>
    <relationshipName>Part_Selectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PS_Output__c/PS_Output__c.object-meta.xml
<CustomObject>
    <label>PS_Output</label>
    <nameField>
        <label>PS_Output</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS_Output</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/PS_Output__c/fields/OA_Override__c.field-meta.xml
<CustomField>
    <fullName>OA_Override__c</fullName>
    <label>OA_Override</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PS_Output__c/fields/OB_Override__c.field-meta.xml
<CustomField>
    <fullName>OB_Override__c</fullName>
    <label>OB_Override</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PS_Output__c/fields/OW_Override__c.field-meta.xml
<CustomField>
    <fullName>OW_Override__c</fullName>
    <label>OW_Override</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PS_Output__c/fields/Part_Selector__c.field-meta.xml
<CustomField>
    <fullName>Part_Selector__c</fullName>
    <label>Part Selector</label>
    <referenceTo>Part_Selector__c</referenceTo>
    <relationshipLabel>PS_Output</relationshipLabel>
    <relationshipName>PS_Output</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ConfigPSUtilityBatch.cls
public class ConfigPSUtilityBatch {
    
    public static Map<String, Object> updatePSRecords(Part_Selector__c psRecord) {
        
        String errorDetails = '';
        String quoteDesc;
        Result resData = new Result();
        SBQQ__QuoteLine__c quoteLine;
        
        configurePartSelector conObj = new configurePartSelector(psRecord.Id);      
        conObj.GetQuoteDescriptionRecords();
        
        List<configurePartSelector.QuoteDescriptionWrapper> res1 = conObj.quoteDescriptionList;
        PS_Output__c outputs = conObj.PSOutsideInstance;
        Part_Selector__c recDetail = conObj.PS;
        
        try {
         	
            update outputs;
            update recDetail;
            
            system.debug('TEST res1:'+recDetail.OA__c);
			system.debug('TEST res1:'+recDetail.OB__c);
            system.debug('TEST res1:'+recDetail.OW__c);
            
            if(recDetail.Quote_Description_Engineer_Override__c) {
                quoteDesc = '';
                if(outputs.OA_Override__c != null) {
                	
                    quoteDesc = outputs.OA_Override__c;
                }
                if(outputs.OB_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.OB_Override__c;
                }
                
                if(outputs.OW_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.OW_Override__c;
                }
                
            } else {
                
                quoteDesc = '';
                if(recDetail.OA__c != null) {
                	
                    quoteDesc = recDetail.OA__c;
                }
                if(recDetail.OB__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += recDetail.OB__c;
                }
                if(recDetail.OW__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += recDetail.OW__c;
                }
            }
            quoteDesc = quoteDesc.replace('\\n', '\n');
            quoteDesc = quoteDesc.replace('\n', '<br/>');
            quoteLine = new SBQQ__QuoteLine__c();
            quoteLine.Id = recDetail.Quote_Line__c;
            quoteLine.SBQQ__Description__c = quoteDesc;
            
        } catch (Exception e) {
            
            errorDetails = 'Error:'+ recDetail.Quote_Line__c +' - '+e.getMessage();
            system.debug('ERROR:'+errorDetails);
        }
        
        Map<String, Object> response = new Map<String, Object>();
        response.put('QUOTE_LINE', quoteLine);
        response.put('ERROR_DETAILS', errorDetails);
        
        return response;
    }
}