force-app/main/default/objects/Opportunity/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <label>Quote Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Buy/Resell</fullName>
            </value>
            <value>
                <fullName>Commission</fullName>
                <default>true</default>
                <label>Commission</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sourcing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Entity__c</fullName>
    <label>Sourcing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sourcing_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>TEXT(SBQQ__Opportunity2__r.Brand__c)</formula>
    <inlineHelpText>Brand of product to be configured;  To change this value, edit on the parent opportunity</inlineHelpText>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <formula>IF( Wanted_Delivery_Date__c  &lt; Standard_Delivery_Date__c , &apos;01&apos;, &apos;00&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Priority</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Quote_Type__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type__c</fullName>
    <formula>TEXT(SBQQ__Opportunity2__r.Quote_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quote Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <description>Formerly &quot;Salesman&quot;</description>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Revision__c.field-meta.xml
<CustomField>
    <fullName>Revision__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Revision</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Opportunity2__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Opportunity2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Opportunity associated with this Quote.</description>
    <inlineHelpText>Opportunity associated with this Quote.</inlineHelpText>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/fields/Wanted_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Wanted_Delivery_Date__c</fullName>
    <defaultValue>ADDMONTHS( TODAY() ,2)</defaultValue>
    <description>Date customer requests delivery</description>
    <label>Wanted Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>SBQQ__Quote__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Config_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Config_Record_ID__c</fullName>
    <label>Config Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Customer_Leadtime__c.field-meta.xml
<CustomField>
    <fullName>Customer_Leadtime__c</fullName>
    <label>Customer Leadtime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Director_Max_Discount__c.field-meta.xml
<CustomField>
    <fullName>Director_Max_Discount__c</fullName>
    <label>Director Max Discount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Discount__c.field-meta.xml
<CustomField>
    <fullName>Discount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Discount. (%)</label>
    <precision>13</precision>
    <scale>5</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Discountable_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Discountable_List_Price__c</fullName>
    <label>Discountable List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Engineering_Notes__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Notes__c</fullName>
    <label>Engineering Notes</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Engineering_Status__c.field-meta.xml
<CustomField>
    <fullName>Engineering_Status__c</fullName>
    <defaultValue>&apos;No&apos;</defaultValue>
    <label>Engineering Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <label>Requires Approval</label>
            </value>
            <value>
                <fullName>No</fullName>
                <label>No Approval Required</label>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Inside_Sales_Max_Discount__c.field-meta.xml
<CustomField>
    <fullName>Inside_Sales_Max_Discount__c</fullName>
    <label>Inside Sales Max Discount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Leadtime__c.field-meta.xml
<CustomField>
    <fullName>Leadtime__c</fullName>
    <description>Maximum leadtime for product</description>
    <label>Leadtime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Leadtime_Site_10__c.field-meta.xml
<CustomField>
    <fullName>Leadtime_Site_10__c</fullName>
    <label>Config Lead Time Site 10</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Leadtime_Site_20__c.field-meta.xml
<CustomField>
    <fullName>Leadtime_Site_20__c</fullName>
    <label>Config Lead Time Site 20</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Leadtime_Site_30__c.field-meta.xml
<CustomField>
    <fullName>Leadtime_Site_30__c</fullName>
    <label>Config Lead Time Site 30</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Leadtime_Site_40__c.field-meta.xml
<CustomField>
    <fullName>Leadtime_Site_40__c</fullName>
    <label>Config Lead Time Site 40</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Max_Lead_Time__c.field-meta.xml
<CustomField>
    <fullName>Max_Lead_Time__c</fullName>
    <label>Max Lead Time</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Non_Discountable_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Non_Discountable_List_Price__c</fullName>
    <label>Non Discountable List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <label>Red-ball</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Production_Planning_Leadtime__c.field-meta.xml
<CustomField>
    <fullName>Production_Planning_Leadtime__c</fullName>
    <label>Production Planning Leadtime</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Quote_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Number__c</fullName>
    <label>Quote Line Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Quote_Line_Reference__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Reference__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line Reference</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Quote Lines (Quote Line Reference)</relationshipLabel>
    <relationshipName>Quote_Lines1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Requires_Inside_Sales_Approval__c.field-meta.xml
<CustomField>
    <fullName>Requires_Inside_Sales_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Inside Sales Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Requires_Sales_Director_Approval__c.field-meta.xml
<CustomField>
    <fullName>Requires_Sales_Director_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Sales Director Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Requires_Sales_Executive_Approval__c.field-meta.xml
<CustomField>
    <fullName>Requires_Sales_Executive_Approval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Requires Sales Executive Approval</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Sales_Rep_Max_Discount__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep_Max_Discount__c</fullName>
    <label>Sales Rep Max Discount</label>
    <precision>11</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quantity__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quantity__c</fullName>
    <description>Quantity being quoted.</description>
    <inlineHelpText>Quantity being quoted.</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Wanted_Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Wanted_Delivery_Date__c</fullName>
    <label>Wanted Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/CDC_Source_Entity__c.field-meta.xml
<CustomField>
    <fullName>CDC_Source_Entity__c</fullName>
    <label>CDC Source Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Selling_Entity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Rep_Code__c.field-meta.xml
<CustomField>
    <fullName>Rep_Code__c</fullName>
    <label>Rep Code</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Rep_Code</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Sourcing_Entity__c.field-meta.xml
<CustomField>
    <fullName>Sourcing_Entity__c</fullName>
    <label>Sourcing Entity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Sourcing_Entities</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Brands.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>CDC</fullName>
    </customValue>
    <customValue>
        <fullName>Groth</fullName>
    </customValue>
    <customValue>
        <fullName>LaMOT</fullName>
    </customValue>
    <customValue>
        <fullName>LVA</fullName>
    </customValue>
    <masterLabel>Brands</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Selling_Entity.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>Liberty</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Stafford</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>GCMPL</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>Not Allowed</fullName>
    </customValue>
    <masterLabel>Selling Entity</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Sourcing_Entities.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>10</fullName>
        <label>Liberty</label>
    </customValue>
    <customValue>
        <fullName>20</fullName>
        <label>Stafford</label>
    </customValue>
    <customValue>
        <fullName>30</fullName>
        <label>GCMPL</label>
    </customValue>
    <customValue>
        <fullName>40</fullName>
        <label>Europe</label>
    </customValue>
    <customValue>
        <fullName>Not Allowed</fullName>
    </customValue>
    <masterLabel>Sourcing Entities</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/QuoteLineTriggerHelper.cls
public class QuoteLineTriggerHelper {

    public static User userData = [
        SELECT Id, Brand__c, CDC_Source_Entity__c, Groth_Source_Entity__c, LVA_Source_Entity__c, LaMOT_Source_Entity__c
        FROM User
        WHERE Id=:UserInfo.getUserId() LIMIT 1];
    public static Map<Id, SBQQ__Quote__c> getQuoteData(List<Id> quoteIdList) {
        Map<Id, SBQQ__Quote__c> quoteMap = new Map<Id, SBQQ__Quote__c>();
        try {
            quoteMap = new Map<Id, SBQQ__Quote__c>([
                SELECT Id,Wanted_Delivery_Date__c,Brand__c,Rep_Code__c,Revision__c,Sourcing_Entity__c,
                        SBQQ__Opportunity2__r.Quote_Type__c,
                (
                    SELECT Id,LeadTime__c,Production_Planning_Leadtime__c,Customer_Leadtime__c,SBQQ__Quote__c
                    FROM SBQQ__LineItems__r
                )
                FROM SBQQ__Quote__c WHERE Id IN :quoteIdList
            ]);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        return quoteMap;
    }
    public static Map<Id, SBQQ__QuoteLine__c> getQuoteLineRefData(List<Id> quoteLineRefIdList) {
        Map<Id, SBQQ__QuoteLine__c> quoteLineRefMap = new Map<Id, SBQQ__QuoteLine__c>();
        try {
            quoteLineRefMap = new Map<Id, SBQQ__QuoteLine__c>([
                SELECT Id,Config_Record_Id__c,SBQQ__Quantity__c,
                    Engineering_Notes__c,Non_Discountable_List_Price__c,Discountable_List_Price__c,
                    Leadtime_Site_10__c,Leadtime_Site_20__c,Leadtime_Site_30__c,Leadtime_Site_40__c
                FROM SBQQ__QuoteLine__c WHERE Id IN :quoteLineRefIdList
            ]);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
        return quoteLineRefMap;
    }

    //Feature #30261
    public static void runBeforeInsertOperations(List<SBQQ__QuoteLine__c> lineItems) {
        List<Id> qtIds = new List<Id>();
        List<SBQQ__QuoteLine__c> quoteLinesWithoutPricebookEntryId = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c lineItem : lineItems) {
            // Add all SBQQ Quote IDs to list for queries
            if(qtIds.indexOf(lineItem.SBQQ__Quote__c) == -1) {
                qtIds.add(lineItem.SBQQ__Quote__c);
            }
        }
        Map<Id, SBQQ__Quote__c> sourceQuotes = new Map<Id, SBQQ__Quote__c>(
            [
                SELECT Id, Brand__c, Sourcing_Entity__c, SBQQ__Pricebook__c
                FROM SBQQ__Quote__c
                WHERE Id IN :qtIds
            ]
        );
        // Set more complex logic, based on Quote
        Set<Id> quotePriceBookIds = new Set<Id>();
        for(SBQQ__QuoteLine__c lineItem:lineItems) {
            // If Sourcing Entity
            lineItem.Sourcing_Entity__c = sourceQuotes.get(lineItem.SBQQ__Quote__c).Sourcing_Entity__c;
            //if(quotePriceBookId.size() == 0){
            //system.debug('test 1');
            quotePriceBookIds.add(sourceQuotes.get(lineItem.SBQQ__Quote__c).SBQQ__Pricebook__c);
               //system.debug('set pricebook ' + quotePriceBookId[0]);
            //}
            //add to group of quote lines to gather Pricebook Entry ID 
            if(lineItem.SBQQ__PricebookEntryId__c == null){
            //system.debug('test 2');
                quoteLinesWithoutPricebookEntryId.add(lineItem);
            }
            

        }
        //system.debug('quote pricebook ' + quotePriceBookId);
        //system.debug('quote lines ' + quoteLinesWithoutPricebookEntryId);
        List<SBQQ__Quote__c> quoteRecords = sourceQuotes.values();
        setCPQQuoteLinePricebookEntry.setQuoteLinePricebookEntryId(quoteRecords, quoteLinesWithoutPricebookEntryId, quotePriceBookIds);
        /** MOVE MAPPINGUTIL CALL HERE */
    }
    /**
     *  Purpose : Get Lead Time (leadtime__c) based on sourcing entity
     */
    public static Decimal getDefaultLeadTime(SBQQ__QuoteLine__c lineItem) {
        Decimal leadTime;
        switch on lineItem.Sourcing_Entity__c {
            when '10' {
                leadTime = lineItem.Leadtime_Site_10__c;
            }
            when '20' {
                leadTime = lineItem.Leadtime_Site_20__c;
            }
            when '30' {
                leadTime = lineItem.Leadtime_Site_30__c;
            }
            when '40' {
                leadTime = lineItem.Leadtime_Site_40__c;
            }
        }
        return leadTime;
    }
    /**
     * Purpose: Get Default Sourcing Entity based on users brand
     */
    public static String getDefaultUserSourcingEntity(String brand) {
        String sourcingEntity;
        String test = brand.toUpperCase();
        switch on test {
            when 'CDC' {
                sourcingEntity = userData.CDC_Source_Entity__c;
            }
            when 'GROTH' {
                sourcingEntity = userData.Groth_Source_Entity__c;
            }
            when 'LAMOT' {
                sourcingEntity = userData.LaMOT_Source_Entity__c;
            }
            when 'LVA' {
                sourcingEntity = userData.LVA_Source_Entity__c;
            }
        }
        return sourcingEntity;
    }

    public static void runBeforeUpdateOperations(Map<Id,SBQQ__QuoteLine__c> oldQuoteLineMap, List<SBQQ__QuoteLine__c> lineItems) {

        System.debug('QuoteLineTriggerHelper.UpdateApprovalsFlags');
        Set<Id> quoteIdSet = new Set<Id>();
        Set<Id> quoteLineRefIdSet = new Set<Id>();
        Map<Id,SBQQ__Quote__c> quoteMap = new Map<Id,SBQQ__Quote__c>();
        Map<Id,SBQQ__QuoteLine__c> quoteLineRefMap = new Map<Id,SBQQ__QuoteLine__c>();

        for(SBQQ__QuoteLine__c lineItem : lineItems) {
            quoteIdSet.add(lineItem.SBQQ__Quote__c);
            if(!String.isBlank(lineItem.Quote_Line_Reference__c)) {
                quoteLineRefIdSet.add(lineItem.Quote_Line_Reference__c);
            }
        }
        if(quoteIdSet.size() > 0) {
            quoteMap = getQuoteData(new List<Id>(quoteIdSet));
        }
        if(quoteLineRefIdSet.size() > 0) {
            quoteLineRefMap = getQuoteLineRefData(new List<Id>(quoteLineRefIdSet));
        }

        for(SBQQ__QuoteLine__c lineItem:lineItems) {
            SBQQ__Quote__c quote = quoteMap.get(lineItem.SBQQ__Quote__c);

            //Feature #30261
            // Populate Default Line Number for Original Quote
            if(String.IsBlank(lineItem.Quote_Line_Number__c)) {
                lineItem.Quote_Line_Number__c = lineItem.Name;
            }

            //Feature #30404
            setSourcingEntityAndLeadtime(lineItem);
            setDiscountThresholds(quote,lineItem);
            setConfigValues(quoteLineRefMap,lineItem);
            setPricingAndCommissions(quote, lineItem);

            // Feature #30236/30237
            if(oldQuoteLineMap.containsKey(lineItem.Id)) {
                setDiscountApprovalFlags(
                    oldQuoteLineMap.get(lineItem.Id),
                    lineItem,
                    quote.Revision__c
                );
            }
            setReviewFlags(lineItem);
        }
    }
    /*public static void runAfterUpdateOperations(List<SBQQ__QuoteLine__c> newQuoteLines) {
        Map<Id,Decimal> maxLeadTimeMap = new Map<Id,Decimal>();
        Decimal maxLeadTime;
        for(SBQQ__QuoteLine__c lineItem : newQuoteLines) {
            Decimal currentLeadTime = 0;
            // Check if a max lead time is already present
            if(maxLeadTimeMap.containsKey(lineItem.SBQQ__Quote__c)) {
                currentLeadTime = maxLeadTimeMap.get(lineItem.SBQQ__Quote__c);
            }
            // Assign the current comparison value by hierarchy PP, then Customer, then Config default
            if(lineItem.Production_Planning_Leadtime__c != null && lineItem.Production_Planning_Leadtime__c != 0) {
                currentLeadTime = lineItem.Production_Planning_Leadtime__c;
            } else if(lineItem.Customer_Leadtime__c != null && lineItem.Customer_Leadtime__c != 0) {
                currentLeadTime = lineItem.Customer_Leadtime__c;
            } else if(lineItem.Leadtime__c != null && lineItem.Leadtime__c != 0) {
                currentLeadTime = lineItem.Leadtime__c;
            }
            // If the current lead time is greater than the currently recorded maximum, then store it.
            if(currentLeadTime > maxLeadTime) {
                maxLeadTime = currentLeadTime;
                maxLeadTimeMap.put(lineItem.SBQQ__Quote__c, currentLeadTime);
            }
        }
        // Retrieve all pertinent Quotes, and update them
        List<SBQQ__Quote__c> quotesToUpdate = [
            SELECT Id, Max_Lead_Time__c
            FROM SBQQ__Quote__c
            WHERE Id IN :maxLeadTimeMap.keySet()
        ];
        for(SBQQ__Quote__c qt : quotesToUpdate) {
            qt.Max_Lead_Time__c = maxLeadTimeMap.get(qt.Id);
        }
        update quotesToUpdate;
    }*/
    public static void setSourcingEntityAndLeadtime(SBQQ__QuoteLine__c lineItem) {
        String sourcingEntity = String.isBlank(lineItem.Sourcing_Entity__c) ?
                MappingUtil.brandDefaultSourcingEntityMap.get(lineItem.Brand__c) : lineItem.Sourcing_Entity__c;
        Decimal leadTime = getDefaultLeadTime(lineItem);

        if(leadTime == 7777 ) {
            sourcingEntity = getDefaultUserSourcingEntity(lineItem.Brand__c);
            leadTime = getDefaultLeadTime(lineItem);
            lineItem.Sourcing_Entity__c = sourcingEntity;
        }
        lineItem.Leadtime__c = leadTime;

        if(lineItem.Customer_Leadtime__c < lineItem.Leadtime__c) {
            lineItem.Priority__c ='1';
        } else {
            lineItem.Priority__c ='';
        }
    }
    public static void setDiscountThresholds(SBQQ__Quote__c quote, SBQQ__QuoteLine__c lineItem) {
        MappingUtil.DiscThresholds threshold = MappingUtil.getThresholds(
            quote.Brand__c,
            quote.Rep_Code__c
        );
        lineItem.Sales_Rep_Max_Discount__c = threshold.insideSales;
        lineItem.Inside_Sales_Max_Discount__c = threshold.director;
        lineItem.Director_Max_Discount__c = threshold.salesExec;
    }
    public static void setDiscountApprovalFlags(SBQQ__QuoteLine__c oldLine, SBQQ__QuoteLine__c lineItem, Decimal revisionNumber) {
        //if(revisionNumber == 0) {
            lineItem.Requires_Inside_Sales_Approval__c = lineItem.Discount__c > lineItem.Sales_Rep_Max_Discount__c;
            lineItem.Requires_Sales_Director_Approval__c = lineItem.Discount__c > lineItem.Inside_Sales_Max_Discount__c;
            lineItem.Requires_Sales_Executive_Approval__c = lineItem.Discount__c > lineItem.Director_Max_Discount__c;
        /* TODO: Update tracking to track the discount, and use that for smart approvals
        } else {
            Boolean discountIncreased = lineItem.Discount__c > oldLine.Discount__c;
            lineItem.Requires_Inside_Sales_Approval__c = oldLine.Requires_Inside_Sales_Approval__c &&
                lineItem.Discount__c > lineItem.Sales_Rep_Max_Discount__c && discountIncreased;
            lineItem.Requires_Sales_Director_Approval__c = oldLine.Requires_Sales_Director_Approval__c &&
                lineItem.Discount__c > lineItem.Inside_Sales_Max_Discount__c && discountIncreased;
            lineItem.Requires_Sales_Executive_Approval__c = oldLine.Requires_Sales_Executive_Approval__c &&
                lineItem.Discount__c > lineItem.Director_Max_Discount__c && discountIncreased;
        } */
    }
    public static void setReviewFlags(SBQQ__QuoteLine__c lineItem) {
        if(lineItem.Engineering_Status__c != 'Released' && lineItem.Total_List_Price__c <> 0 && (lineItem.Line_Status__c == 'Primary' || lineItem.Line_Status__c == 'Alternate')) {
            lineItem.Engineering_Status__c = (String.isBlank(lineItem.SBQQ__Description__c) || lineItem.Requires_Technical_Review__c == 'Yes' || lineItem.Total_List_Price__c >= 8000000 || lineItem.Total_List_Price__c <= 0 || lineItem.Drawings_Status__c == 'Requested' || lineItem.Drawings_Status__c == 'Required') ? 'Yes' : 'No';
        }
        if(lineItem.Product_Planning_Status__c != 'Released' && (lineItem.Line_Status__c == 'Primary' || lineItem.Line_Status__c == 'Alternate')) {
            lineItem.Product_Planning_Status__c = (
                lineItem.Priority__c == '1' ||
                (lineItem.Leadtime__c > 4000 && lineItem.Production_Planning_Leadtime__c == null && lineItem.Customer_Leadtime__c == null) ||
                (lineItem.Leadtime__c == 0 && lineItem.Production_Planning_Leadtime__c == null && lineItem.Customer_Leadtime__c == null)
            ) ? 'Yes' : 'No';
        }
    }
    //Feature #30232
    public static void setConfigValues(Map<Id,SBQQ__QuoteLine__c> quoteLineRefMap, SBQQ__QuoteLine__c lineItem) {
        System.debug('@Developer --> SetConfigValues 262: Limits.getLimitQueries() :' + Limits.getLimitQueries());
		System.debug('@Developer --> SetConfigValues 263: Limits.getQueries() :' + Limits.getQueries());
        try {
            if(String.IsNotBlank(lineItem.SBQQ__ProductCode__c)) {
                system.debug('@===> if ' );
                Id configId = String.isBlank(lineItem.Config_Record_Id__c) ? MappingUtil.getConfigSObjectIDFromQuoteLine(lineItem) : lineItem.Config_Record_Id__c;
                lineItem.Run_Config_Sync__c = false;
                if(lineItem.Run_Config_Sync__c && !String.isBlank(configId)) {

                    Result endResult = SyncConfiguratorData.runRulesForConfigData(configId);
                    system.debug('@Developer--> endResult ' + endResult  );
                    lineItem.Config_Record_Id__c = configId;
                    lineItem.Engineering_Notes__c = SyncConfiguratorData.ENG_NOTES;
                    lineItem.Non_Discountable_List_Price__c   = SyncConfiguratorData.NONDISCOUNTABLELISTPRICE != null ? SyncConfiguratorData.NONDISCOUNTABLELISTPRICE : 0;
                    //lineItem.Discountable_List_Price__c = SyncConfiguratorData.LISTPRICE - lineItem.Non_Discountable_List_Price__c;
                    lineItem.Discountable_List_Price__c = SyncConfiguratorData.LISTPRICE != null ? SyncConfiguratorData.LISTPRICE - lineItem.Non_Discountable_List_Price__c : 0;
                    lineItem.PARTNUMBER__c=SyncConfiguratorData.PARTNUMBER;
                    lineItem.Leadtime_Site_10__c = SyncConfiguratorData.LEADTIMEFORSITE10;
                    lineItem.Leadtime_Site_20__c = SyncConfiguratorData.LEADTIMEFORSITE20;
                    lineItem.Leadtime_Site_30__c = SyncConfiguratorData.LEADTIMEFORSITE30;
                    lineItem.Leadtime_Site_40__c = SyncConfiguratorData.LEADTIMEFORSITE40;
                    if(quoteLineRefMap.containsKey(lineItem.Id)) {
                        SBQQ__QuoteLine__c lineItemInfo = quoteLineRefMap.get(lineItem.Id);
                        //if(lineItemInfo.Delivery_Quantity_Total__c != SyncConfiguratorData.QTY) {
                        //    throw new AuraHandledException('Remove delivery info items before changing this line\'s quantity!');
                        //}
                        lineItem.SBQQ__Quantity__c = SyncConfiguratorData.QTY;
                    } else {
                        lineItem.SBQQ__Quantity__c = SyncConfiguratorData.QTY;
                    }
                    lineItem.Run_Config_Sync__c = false;
                }
                System.debug('configId: ' + configId);
            } else if(quoteLineRefMap.containsKey(lineItem.Quote_Line_Reference__c)) {
                system.debug('@===> else if ' );
                SBQQ__QuoteLine__c parentLineItem = quoteLineRefMap.get(lineItem.Quote_Line_Reference__c);
                lineItem.Config_Record_Id__c = parentLineItem.Config_Record_Id__c;
                lineItem.Engineering_Notes__c = parentLineItem.Engineering_Notes__c;
                lineItem.Non_Discountable_List_Price__c =  parentLineItem.Non_Discountable_List_Price__c;
                lineItem.Discountable_List_Price__c = parentLineItem.Discountable_List_Price__c;
                lineItem.Leadtime_Site_10__c = parentLineItem.Leadtime_Site_10__c;
                lineItem.Leadtime_Site_20__c = parentLineItem.Leadtime_Site_20__c;
                lineItem.Leadtime_Site_30__c = parentLineItem.Leadtime_Site_30__c;
                lineItem.Leadtime_Site_40__c = parentLineItem.Leadtime_Site_40__c;
            }
            system.debug('lineItem====> ' + lineItem);
        } catch(Exception e) {
            System.debug('Error on config rules :' + e.getMessage());
            system.debug(e.getLineNumber());
        }
    }
    public static void setPricingAndCommissions(SBQQ__Quote__c quote, SBQQ__QuoteLine__c lineItem) {
        try {
            lineItem.Discount_Amount__c = (lineItem.Discount__c != null && lineItem.Discountable_List_Price__c != null) ? lineItem.Discount__c/100 * lineItem.Discountable_List_Price__c : 0;
            //lineItem.SBQQ__ListPrice__c = lineItem.Discountable_List_Price__c + lineItem.Non_Discountable_List_Price__c;

            if(lineItem.Discountable_List_Price__c == null || lineItem.Non_Discountable_List_Price__c == null){
                if(lineItem.Discountable_List_Price__c != null){
                   lineItem.SBQQ__ListPrice__c = lineItem.Discountable_List_Price__c;
                }
                else if(lineItem.Non_Discountable_List_Price__c != null){
                    lineItem.SBQQ__ListPrice__c = lineItem.Non_Discountable_List_Price__c;
                }
                else{
                    lineItem.SBQQ__ListPrice__c = 0;
                }

            }else{
                lineItem.SBQQ__ListPrice__c =  lineItem.Discountable_List_Price__c + lineItem.Non_Discountable_List_Price__c ;
            }
            
            lineItem.SBQQ__NetPrice__c = lineItem.SBQQ__ListPrice__c;
            if(lineItem.Discountable_List_Price__c != null || lineItem.Non_Discountable_List_Price__c != null){
                lineItem.SBQQ__RegularPrice__c = lineItem.Non_Discountable_List_Price__c + (lineItem.Discountable_List_Price__c - lineItem.Discount_Amount__c);
            }
            //Feature #30339
            if(quote.SBQQ__Opportunity2__r.Quote_Type__c == 'Buy/Resell') {
                lineItem.Maximum_Commission__c = 0;
                lineItem.Discount__c = 20;
            } else {
                lineItem.Maximum_Commission__c = 20;
            }
            
            if(lineItem.Product_Group__c == 'Replacement Parts' || lineitem.Body_Material__c == '1' ){
                lineItem.Maximum_Commission__c = quote.SBQQ__Opportunity2__r.Quote_Type__c == 'Buy/Resell'? 0 : 15;
                
                if (quote.SBQQ__Opportunity2__r.Quote_Type__c == 'Buy/Resell'){
                    lineItem.Discount__c = 15;
                    lineItem.Sales_Rep_Max_Discount__c = 15;
                }
                /*if (lineItem.Discount__c == NULL){
                    lineItem.Discount__c = quote.SBQQ__Opportunity2__r.Quote_Type__c == 'Buy/Resell'? 15 : 20;
                } else {
                    lineItem.Sales_Rep_Max_Discount__c = 15;
                    lineItem.Discount__c = 15;
                       }*/
            } 
            /* TODO: UPDATE PARTNER and MATERIAL LOGIC AFTER CONFIG TALK
                vMaxCommission=20%
                vMaxPartnerOrgDiscount=20%

                if CONFIG PRODUCT LINE = Relief Valves OR Flame Products
                    if MCBODY = “1”[ALUMINUM]
                        MAX COMM=15% and MAX PRTNR DSC=15%
                else if CONFIG PRODUCT LINE = Parts AND PRODUCT = Parts or Kits OR MCBODY = “1”[ALUMINUM] (Verify code)
                    Then vMaxCommission=15% and vMaxPartnerOrgDiscount=15%
                End

            */
        } catch(Exception e) {
            System.debug(e.getMessage());
            System.debug(e.getLineNumber());
        }
    }
}