force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteGasBurner__c/WasteGasBurner__c.object-meta.xml
<CustomObject>
    <label>WasteGasBurner</label>
    <nameField>
        <displayFormat>WGB-{0000}</displayFormat>
        <label>WasteGasBurner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WasteGasBurners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteGasBurner__c/fields/OA__c.field-meta.xml
<CustomField>
    <fullName>OA__c</fullName>
    <label>OA</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/OB__c.field-meta.xml
<CustomField>
    <fullName>OB__c</fullName>
    <label>OB</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>WasteGasBurners</relationshipLabel>
    <relationshipName>WasteGasBurners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WGB_Outputs__c/WGB_Outputs__c.object-meta.xml
<CustomObject>
    <label>WGB Outputs</label>
    <nameField>
        <label>WGB Outputs</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WGB Outputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/WGB_Outputs__c/fields/OA_Override__c.field-meta.xml
<CustomField>
    <fullName>OA_Override__c</fullName>
    <label>OA Override</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WGB_Outputs__c/fields/OB_Override__c.field-meta.xml
<CustomField>
    <fullName>OB_Override__c</fullName>
    <label>OB Override</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WGB_Outputs__c/fields/WasteGasBurner__c.field-meta.xml
<CustomField>
    <fullName>WasteGasBurner__c</fullName>
    <label>WasteGasBurner</label>
    <referenceTo>WasteGasBurner__c</referenceTo>
    <relationshipLabel>WGB Outputs Relation Field</relationshipLabel>
    <relationshipName>WGB_Outputs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ConfigWGBUtilityBatch.cls
public class ConfigWGBUtilityBatch {
    
    public static Map<String, Object> updateWGBRecords(WasteGasBurner__c wgbRecord) {
        
        String errorDetails = '';
        String quoteDesc;
        Result resData = new Result();
        SBQQ__QuoteLine__c quoteLine;
        
        ConfigureWasteGasBurner conWGB = new ConfigureWasteGasBurner(wgbRecord.Quote_Line__c);        
        List<ConfigureWasteGasBurner.QuoteDescriptionWrapper> res1 = conWGB.GetQuoteDescriptionRec();
        WGB_Outputs__c wgbOutputs = conWGB.wgbOutsideInstance;
        WasteGasBurner__c wgbDetail = conWGB.WGBProd;
        
        try {
         	
            update wgbOutputs;
            update wgbDetail;
            
            if(wgbDetail.Quote_Description_Engineer_Override__c) {
                quoteDesc = '';
                if(wgbOutputs.OA_Override__c != null) {
                	
                    quoteDesc = wgbOutputs.OA_Override__c;
                }
                if(wgbOutputs.OB_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += wgbOutputs.OB_Override__c;
                }
                
            } else {
                
                quoteDesc = '';
                if(wgbDetail.OA__c != null) {
                	
                    quoteDesc = wgbDetail.OA__c;
                }
                if(wgbDetail.OB__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += wgbDetail.OB__c;
                }
            }
            quoteDesc = quoteDesc.replace('\\n', '\n');
            quoteDesc = quoteDesc.replace('\n', '<br/>');
            quoteLine = new SBQQ__QuoteLine__c();
            quoteLine.Id = wgbDetail.Quote_Line__c;
            quoteLine.SBQQ__Description__c = quoteDesc;
            
        } catch (Exception e) {
            
            errorDetails = 'Error:'+ wgbDetail.Quote_Line__c +' - '+e.getMessage();
        }
        
        Map<String, Object> response = new Map<String, Object>();
        response.put('QUOTE_LINE', quoteLine);
        response.put('ERROR_DETAILS', errorDetails);
        
        return response;
    }
}