force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Config_Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Config_Record_ID__c</fullName>
    <label>Config Record ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <defaultValue>TODAY() + 60</defaultValue>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Run_Config_Sync__c.field-meta.xml
<CustomField>
    <fullName>Run_Config_Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Run Config Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ReRunConfigController.cls
public class ReRunConfigController {
    
    @AuraEnabled 
    public static void rerun(Id quoteLineId) {
        
        try {
            SBQQ__QuoteLine__c lineItem =[
                SELECT ID,SBQQ__ProductCode__c,Expiration_Date__c,Config_Record_Id__c
                FROM SBQQ__QuoteLine__c 
                WHERE ID=:quoteLineId
                LIMIT 1
            ];
            lineItem.Run_Config_Sync__c = true; 
            lineItem.Expiration_Date__c = date.today().addDays(60);
            update lineItem;
        }
        catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
}