force-app/main/default/objects/AssyPartDefinition__c/AssyPartDefinition__c.object-meta.xml
<CustomObject>
    <label>AssyPartDefinition</label>
    <nameField>
        <label>AssyPartDefinition</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AssyPartDefinition</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AssyPartDefinition__c/fields/ASSYPARTNO__c.field-meta.xml
<CustomField>
    <fullName>ASSYPARTNO__c</fullName>
    <label>ASSYPARTNO</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AssyPartDefinition__c/fields/Configurator__c.field-meta.xml
<CustomField>
    <fullName>Configurator__c</fullName>
    <label>Configurator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGR__c/BGR__c.object-meta.xml
<CustomObject>
    <label>BGR</label>
    <nameField>
        <displayFormat>BGR-{0000}</displayFormat>
        <label>Blanket Gas Regulator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>BGR</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BGR__c/fields/ASSYPARTNOBASE__c.field-meta.xml
<CustomField>
    <fullName>ASSYPARTNOBASE__c</fullName>
    <label>ASSYPARTNOBASE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Part_Number_Base__c.field-meta.xml
<CustomField>
    <fullName>Part_Number_Base__c</fullName>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BGR__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>BGR</relationshipLabel>
    <relationshipName>BGR</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ConfigInputsTranslation__c/ConfigInputsTranslation__c.object-meta.xml
<CustomObject>
    <label>ConfigInputsTranslation</label>
    <nameField>
        <label>ConfigInputsTranslation</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ConfigInputsTranslation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ConfigInputsTranslation__c/fields/Configurator__c.field-meta.xml
<CustomField>
    <fullName>Configurator__c</fullName>
    <label>Configurator</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/Flame_Product__c.object-meta.xml
<CustomObject>
    <label>Flame Product</label>
    <nameField>
        <displayFormat>FL-{000000}</displayFormat>
        <label>Flame Product Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flame Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flame_Product__c/fields/ASSYPARTEXISTING__c.field-meta.xml
<CustomField>
    <fullName>ASSYPARTEXISTING__c</fullName>
    <label>ASSYPARTEXISTING</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/ASSYPARTNO__c.field-meta.xml
<CustomField>
    <fullName>ASSYPARTNO__c</fullName>
    <label>ASSYPARTNO</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Part_Number_Base__c.field-meta.xml
<CustomField>
    <fullName>Part_Number_Base__c</fullName>
    <label>ASSYPARTNOBASE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flame_Product__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Flame Products</relationshipLabel>
    <relationshipName>Flame_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/Holders__c.object-meta.xml
<CustomObject>
    <label>Holders</label>
    <nameField>
        <displayFormat>HLD-{0000}</displayFormat>
        <label>Holders Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Holders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Holders__c/fields/ASME_Section_VIII__c.field-meta.xml
<CustomField>
    <fullName>ASME_Section_VIII__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ASME Section VIII</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Bolting_Class__c.field-meta.xml
<CustomField>
    <fullName>Bolting_Class__c</fullName>
    <label>Bolting Class</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CDC</fullName>
            </value>
            <value>
                <fullName>LaMOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Cost_Override__c.field-meta.xml
<CustomField>
    <fullName>Cost_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cost Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Holder_Product_Code__c.field-meta.xml
<CustomField>
    <fullName>Holder_Product_Code__c</fullName>
    <label>Holder Product Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/NEWSPCLPARTNOBASE__c.field-meta.xml
<CustomField>
    <fullName>NEWSPCLPARTNOBASE__c</fullName>
    <label>New Special Part No Base</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CD50000</fullName>
            </value>
            <value>
                <fullName>LD50000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Part_Number_Base__c.field-meta.xml
<CustomField>
    <fullName>Part_Number_Base__c</fullName>
    <label>Part Number Base</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Holders</relationshipLabel>
    <relationshipName>Holders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Holders__c/fields/Size2__c.field-meta.xml
<CustomField>
    <fullName>Size2__c</fullName>
    <label>Size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/Part_Selector__c.object-meta.xml
<CustomObject>
    <label>Part Selector</label>
    <nameField>
        <label>Part Selector Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Part Selectors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part_Selector__c/fields/ASSYPARTEXISTING__c.field-meta.xml
<CustomField>
    <fullName>ASSYPARTEXISTING__c</fullName>
    <label>ASSYPARTEXISTING</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/ASSYPARTNO__c.field-meta.xml
<CustomField>
    <fullName>ASSYPARTNO__c</fullName>
    <label>ASSYPARTNO</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>Quote_Line__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/NEWSPCLPARTNOBASE__c.field-meta.xml
<CustomField>
    <fullName>NEWSPCLPARTNOBASE__c</fullName>
    <label>NEWSPCLPARTNOBASE</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CD#TBA</fullName>
            </value>
            <value>
                <fullName>LD#TBA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Part_Number_Base__c.field-meta.xml
<CustomField>
    <fullName>Part_Number_Base__c</fullName>
    <label>ASSYPARTNOBASE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Quote_Description_Engineer_Override__c.field-meta.xml
<CustomField>
    <fullName>Quote_Description_Engineer_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Description Engineer Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Part_Selector__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Part Selectors</relationshipLabel>
    <relationshipName>Part_Selectors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <formula>SBQQ__Quote__r.Brand__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Brand</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/WasteGasBurner__c.object-meta.xml
<CustomObject>
    <label>WasteGasBurner</label>
    <nameField>
        <displayFormat>WGB-{0000}</displayFormat>
        <label>WasteGasBurner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WasteGasBurners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteGasBurner__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>WasteGasBurners</relationshipLabel>
    <relationshipName>WasteGasBurners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AssyPartDefinationProcessorTest.cls
@isTest
public class AssyPartDefinationProcessorTest {
    
    @isTest
    public static void testCopyValuesFromTransData() {
        
        Test.startTest();
        
        Map<String, String> mapWithWGBValues = new Map<String, String>();
        mapWithWGBValues.put('BRAND','Groth');
        mapWithWGBValues.put('PRODUCT_CODE','WGB');
        mapWithWGBValues.put('PRODUCT_NAME','WasteGasBurner');
        
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithWGBValues);
        
        TestDataWGBUtility.quoteLine = quoteLine;
        TestDataWGBUtility.mapWithWGBValues = mapWithWGBValues;
        
        system.debug('TestDataWGBUtility.quoteLine:'+TestDataWGBUtility.quoteLine);
        system.debug('TestDataWGBUtility.mapWithWGBValues:'+TestDataWGBUtility.mapWithWGBValues);
        TestDataWGBUtility.createWGBTestRecords();
        TestDataWGBUtility.createWGBMasterTestRecords();
        TestDataWGBUtility.createWGBAssyPartRecords();
        
        PageReference pager = Page.ConfigWGBProduct;
        Test.setCurrentPage(pager);
        
        ApexPages.currentPage().getParameters().put('qid', String.valueOf(quoteLine.Id));
        
        WasteGasBurner__c conWGB = [SELECT Id FROM WasteGasBurner__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];
        
        ApexPages.StandardController sc = new ApexPages.StandardController(quoteLine);
        CustomReOrderController configWGB2 =new CustomReOrderController(sc);
        
        //  configWGB2.selectedProduct='byPartumber';
        
        configWGB2.quoteId=String.valueOf(quoteLine.Id);
        configWGB2.selectedProduct='byPartumber';
        configWGB2.reOrderProduct();
        
        Map<string,string> bgrFields = AssyPartDefinationProcessor.mapBGRFields;
        Map<string,string> faFields = AssyPartDefinationProcessor.mapFAFields;
        Map<string,string> rdFields = AssyPartDefinationProcessor.mapRDFields;
        Map<string,string> hldFields = AssyPartDefinationProcessor.mapHLDFields;
        Map<string,string> rvFields = AssyPartDefinationProcessor.mapRVFields;
        Map<string,string> wgbFields = AssyPartDefinationProcessor.mapWGBFields;
        Map<string,string> psFields = AssyPartDefinationProcessor.mapPSFields;
        Map<string,string> partBaseNo = AssyPartDefinationProcessor.mapPartBaseNo;
        Map<string,string> mapConfigWithObj = AssyPartDefinationProcessor.mapConfiguratorwithObject;
        Map<string,string> mapConfigWithObj1 = AssyPartDefinationProcessor.mapObjectwithConfigurator1;
        
        
        Test.stopTest();
    }
    
    @isTest
    public static void testGeneratePartNumber() {
        
        ConfigHoldersOutputController obj = new ConfigHoldersOutputController();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        Holders__c holder = [SELECT Id, Brand__c, ASSYPARTNOBASE__c, Holder_Product_Code__c, Size2__c, Bolting_Class__c, Part_Number_Base__c, ASSYPARTEXISTING__c  FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];        
        holder.ASSYPARTNOBASE__c = '100000100000';
        update holder;
        
        ConfigHoldersOutputController configHld = ConfigHoldersOutputControllerTest.getConfigHolderCntrl();
        
        Test.startTest();
        configHld.generatePartNumber();
        configHld.savePartNumber();
        Test.stopTest();
    }
    
    @isTest
    public static void testGetPartNumberExisting() {
        
        Test.startTest();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
        
        ConfigHolderControllerTest.configValues();
        
        TestDataUtility.createHoldersTestRecords();
        TestDataUtility.createHoldersMasterTestRecords();
        
        List<SBQQ__QuoteLine__c> quoteLine = [SELECT Id FROM SBQQ__QuoteLine__c LIMIT 1];
                
        Holders__c holder = [SELECT Id, Brand__c, Holder_Product_Code__c, Size2__c, Bolting_Class__c, Part_Number_Base__c, ASSYPARTEXISTING__c, ASME_Section_VIII__c  FROM Holders__c WHERE Quote_Line__c = :quoteLine[0].Id LIMIT 1];        
        holder.ASSYPARTNOBASE__c = '100000100000';
        update holder;
        
        AssyPartDefinition__c asd = new AssyPartDefinition__c();
        asd.ASSYPARTNO__c = '100000100000';
        asd.BRAND__c = 'CDC';
        asd.Configurator__c = 'HLD';
        insert asd;
        
        Test.loadData(ConfigInputsTranslation__c.sObjectType, 'ConfigInputsTranslation_Data');
        
        AssyPartDefinationProcessor.getPartNumberExisting(holder.ASSYPARTNOBASE__c, holder, 'HLD');
        AssyPartDefinationProcessor.copyValuesFromTransData(holder, holder.ASSYPARTNOBASE__c);
        Test.stopTest();  
    }
    
    @isTest
    public static void testGetPartNumberByRec() {
        
        Test.startTest();
        ConfigHoldersOutputController obj = new ConfigHoldersOutputController();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        Holders__c holder = [SELECT Id, Brand__c, ASSYPARTNOBASE__c, Holder_Product_Code__c, Size2__c, Bolting_Class__c, Part_Number_Base__c, ASSYPARTEXISTING__c  FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];        
        holder.ASSYPARTNOBASE__c = '100000100000';
        update holder;
        
        List<SBQQ__QuoteLine__c> quoteLines = [Select Id,Name,SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c LIMIT 1];
        
        Id currentId = wizardBaseDataProcessor.getCustomObjectIDbyLine(quoteLines[0].Id);
        Result sObj = wizardBaseDataProcessor.getObjectDataById(currentId); 
        AssyPartDefinationProcessor.getPartNumberByRec(sObj.objResultList[0]);
        
        Test.stopTest();
    }
    
    @isTest
    public static void testGetPartNumberByRec2() {
        
        Test.startTest();
        ConfigHoldersOutputController obj = new ConfigHoldersOutputController();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        Holders__c holder = [SELECT Id, Brand__c, ASSYPARTNOBASE__c, Holder_Product_Code__c, Size2__c, Bolting_Class__c, Part_Number_Base__c, ASSYPARTEXISTING__c  FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];        
        holder.ASSYPARTNOBASE__c = '100000100000';
        update holder;
        
        List<SBQQ__QuoteLine__c> quoteLines = [Select Id,Name,SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c LIMIT 1];
        
        Id currentId = wizardBaseDataProcessor.getCustomObjectIDbyLine(quoteLines[0].Id);
        Result sObj = wizardBaseDataProcessor.getObjectDataById(currentId); 
        AssyPartDefinationProcessor.getPartNumberByRec(sObj.objResultList[0]);
          AssyPartDefinationProcessor.mapObjectwithConfigurator=new Map<String,String>();
          AssyPartDefinationProcessor.mapObjectwithConfigurator.put('Holders__c','PS');
          AssyPartDefinationProcessor.mapQuoteNo.put('PS' ,'Cost_Override__c');
          Holders__c hld= (Holders__c) sObj.objResultList[0];
          hld.Cost_Override__c=true;
          Part_Selector__c pstest = new Part_Selector__c();
          pstest.Quote_Description_Engineer_Override__c=true;
          pstest.Quote_Line__c= quoteLines[0].id;
          pstest.NEWSPCLPARTNOBASE__c='LD#TBA';
          insert pstest ;
        AssyPartDefinationProcessor.generatePartNumber(pstest);
            AssyPartDefinationProcessor.mapFAFields=new Map<String,String>();
        AssyPartDefinationProcessor.mapBrandwithCode=new Map<String,String>();
         AssyPartDefinationProcessor.mapObjectwithConfigurator1=new Map<String,String>();
        
           AssyPartDefinationProcessor.mapBGRFields=new Map<String,String>();
            AssyPartDefinationProcessor.mapPSFields=new Map<String,String>();
             AssyPartDefinationProcessor.mapWGBFields=new Map<String,String>();
              AssyPartDefinationProcessor.mapHLDFields=new Map<String,String>();
               AssyPartDefinationProcessor.mapRDFields=new Map<String,String>();
                AssyPartDefinationProcessor.mapRVFields=new Map<String,String>();
                 AssyPartDefinationProcessor.mapConfiguratorwithObject=new Map<String,String>();
        
        
        
        
        
        
        
        
        
        Test.stopTest();
    }
    
      @isTest
    public static void testGetPartNumberByRec3() {
        
        Test.startTest();
        ConfigHoldersOutputController obj = new ConfigHoldersOutputController();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        Holders__c holder = [SELECT Id, Brand__c, ASSYPARTNOBASE__c, Holder_Product_Code__c, Size2__c, Bolting_Class__c, Part_Number_Base__c, ASSYPARTEXISTING__c  FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];        
        holder.ASSYPARTNOBASE__c = '100000100000';
        update holder;
        
        List<SBQQ__QuoteLine__c> quoteLines = [Select Id,Name,SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c LIMIT 1];
        
        Id currentId = wizardBaseDataProcessor.getCustomObjectIDbyLine(quoteLines[0].Id);
        Result sObj = wizardBaseDataProcessor.getObjectDataById(currentId); 
        AssyPartDefinationProcessor.getPartNumberByRec(sObj.objResultList[0]);
          AssyPartDefinationProcessor.mapObjectwithConfigurator=new Map<String,String>();
          AssyPartDefinationProcessor.mapObjectwithConfigurator.put('Holders__c','PS');
          AssyPartDefinationProcessor.mapQuoteNo.put('PS' ,'Cost_Override__c');
          Holders__c hld= (Holders__c) sObj.objResultList[0];
          hld.Cost_Override__c=true;
          Part_Selector__c pstest = new Part_Selector__c();
          pstest.Quote_Description_Engineer_Override__c=true;
          pstest.Quote_Line__c= quoteLines[0].id;
          //pstest.NEWSPCLPARTNOBASE__c='CD#TBA';
          insert pstest ;
        AssyPartDefinationProcessor.generatePartNumber(pstest);
        pstest.NEWSPCLPARTNOBASE__c='CD#TBA';
          update pstest ;
                  AssyPartDefinationProcessor.generatePartNumber(pstest);
            AssyPartDefinationProcessor.mapFAFields=new Map<String,String>();
        AssyPartDefinationProcessor.mapBrandwithCode=new Map<String,String>();
         AssyPartDefinationProcessor.mapObjectwithConfigurator1=new Map<String,String>();
        
           AssyPartDefinationProcessor.mapBGRFields=new Map<String,String>();
            AssyPartDefinationProcessor.mapPSFields=new Map<String,String>();
             AssyPartDefinationProcessor.mapWGBFields=new Map<String,String>();
              AssyPartDefinationProcessor.mapHLDFields=new Map<String,String>();
               AssyPartDefinationProcessor.mapRDFields=new Map<String,String>();
                AssyPartDefinationProcessor.mapRVFields=new Map<String,String>();
                 AssyPartDefinationProcessor.mapConfiguratorwithObject=new Map<String,String>();
        Test.stopTest();
    }
   @isTest
    public static void testGetPartNumberByRec4() {
        
        Test.startTest();
        ConfigHoldersOutputController obj = new ConfigHoldersOutputController();
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        Holders__c holder = [SELECT Id, Brand__c, ASSYPARTNOBASE__c, Holder_Product_Code__c, Size2__c, Bolting_Class__c, Part_Number_Base__c, ASSYPARTEXISTING__c  FROM Holders__c WHERE Quote_Line__c = :quoteLine.Id LIMIT 1];        
        holder.ASSYPARTNOBASE__c = '100000100000';
        update holder;
        
        List<SBQQ__QuoteLine__c> quoteLines = [Select Id,Name,SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c LIMIT 1];
        
        Id currentId = wizardBaseDataProcessor.getCustomObjectIDbyLine(quoteLines[0].Id);
        Result sObj = wizardBaseDataProcessor.getObjectDataById(currentId); 
       // AssyPartDefinationProcessor.getPartNumberByRec(sObj.objResultList[0]);
          AssyPartDefinationProcessor.mapObjectwithConfigurator=new Map<String,String>();
          AssyPartDefinationProcessor.mapObjectwithConfigurator.put('Holders__c','PS');
          AssyPartDefinationProcessor.mapQuoteNo.put('PS' ,'Cost_Override__c');
          Holders__c hld= (Holders__c) sObj.objResultList[0];
          hld.Cost_Override__c=true;
          BGR__c bgr = new BGR__c();
           bgr.Quote_Line__c= quoteLines[0].id;
           bgr.Quote_Description_Engineer_Override__c=false;
          insert bgr;
          Part_Selector__c pstest = new Part_Selector__c();
          pstest.Quote_Description_Engineer_Override__c=true;
          pstest.Quote_Line__c= quoteLines[0].id;
          //pstest.NEWSPCLPARTNOBASE__c='CD#TBA';
          insert pstest ;

        AssyPartDefinationProcessor.generatePartNumber(bgr);
         Flame_Product__c fp = new Flame_Product__c();
           fp.Quote_Line__c= quoteLines[0].id;
           fp.Quote_Description_Engineer_Override__c=false;
          insert fp;
        
                AssyPartDefinationProcessor.generatePartNumber(fp);
        Test.stopTest();
    }

}