force-app/main/default/objects/WasteGasBurner__c/WasteGasBurner__c.object-meta.xml
<CustomObject>
    <label>WasteGasBurner</label>
    <nameField>
        <displayFormat>WGB-{0000}</displayFormat>
        <label>WasteGasBurner Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WasteGasBurners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WasteGasBurner__c/fields/Back_up_Power_Supply__c.field-meta.xml
<CustomField>
    <fullName>Back_up_Power_Supply__c</fullName>
    <label>Back-up Power Supply</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Control_Panel_Alarm__c.field-meta.xml
<CustomField>
    <fullName>Control_Panel_Alarm__c</fullName>
    <label>Control Panel Alarm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>None</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>Audible</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Visible</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Both</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Control_Panel_Heater__c.field-meta.xml
<CustomField>
    <fullName>Control_Panel_Heater__c</fullName>
    <label>Control Panel Heater</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Enclosure_Type__c.field-meta.xml
<CustomField>
    <fullName>Enclosure_Type__c</fullName>
    <label>Enclosure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>4</fullName>
                <label>NEMA 4</label>
            </value>
            <value>
                <fullName>9</fullName>
                <label>NEMA 4X (304 SS)</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>NEMA 4X (316 SS)</label>
            </value>
            <value>
                <fullName>6</fullName>
                <label>NEMA 4X (Fiberglass)</label>
            </value>
            <value>
                <fullName>7</fullName>
                <label>NEMA 7</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>NEMA 7/4X</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Flame_Sensor__c.field-meta.xml
<CustomField>
    <fullName>Flame_Sensor__c</fullName>
    <label>Flame Sensor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>None</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Dual</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Single</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Lower_Stack_Pedestal_Matl__c.field-meta.xml
<CustomField>
    <fullName>Lower_Stack_Pedestal_Matl__c</fullName>
    <label>Lower Stack/Pedestal Matl</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>5</fullName>
                <label>316 SS</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>304 SS</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>Carbon Steel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Pedestal_Connection__c.field-meta.xml
<CustomField>
    <fullName>Pedestal_Connection__c</fullName>
    <label>Pedestal Connection</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>150 # ANSI Flange</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>PN16</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>PN10/16</label>
            </value>
            <value>
                <fullName>L</fullName>
                <label>Anchor Plate</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>02</fullName>
                <label>2&quot; (50mm)</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>3&quot; (80mm)</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>4&quot; (100mm)</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>6&quot; (150mm)</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>8&quot; (200mm)</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>10&quot; (250mm)</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>12&quot; (300mm)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Stand_Control_Material__c.field-meta.xml
<CustomField>
    <fullName>Stand_Control_Material__c</fullName>
    <label>Stand Control Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>None</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>316 SS</label>
            </value>
            <value>
                <fullName>T</fullName>
                <label>Galvanized Steel</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Step_Down_Transformer__c.field-meta.xml
<CustomField>
    <fullName>Step_Down_Transformer__c</fullName>
    <label>Step Down Transformer</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Sunshield_Control__c.field-meta.xml
<CustomField>
    <fullName>Sunshield_Control__c</fullName>
    <label>Sunshield Control</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>No</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>Yes</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/WasteGasBurner__c/fields/Thermocouple_Material__c.field-meta.xml
<CustomField>
    <fullName>Thermocouple_Material__c</fullName>
    <label>Thermocouple Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>N/A</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>Aluminum Head</label>
            </value>
            <value>
                <fullName>5</fullName>
                <label>316 SS Head</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/configWgbReferenceCtrl.cls
public class configWgbReferenceCtrl {
    public WasteGasBurner__c oWGB{get;set;}
    public User oUser {get;set;}
    public Map<String, String> LowerStackPedestalMatlMap { get;set;}
    public Map<String, String> PedestalConnectionMap { get;set;}
    public Map<String, String> FlameSensorMap { get;set;}
    public Map<String, String> ThermocoupleMaterialMap { get;set;}
    public Map<String, String> EnclosureTypeMap { get;set;}
    public Map<String, String> ControlPanelAlarmMap { get;set;}
    public Map<String, String> ControlPanelHeaterMap { get;set;}
    public Map<String, String> StandControlMaterialMap { get;set;}
    public Map<String, String> SunshieldControlMap { get;set;}
    public Map<String, String> StepDownTransformerMap { get;set;}
    public Map<String, String> BackupPowerSupplyMap { get;set;}
    
    
    

    public string getUserTimeZone(){
        return userinfo.getTimeZone().toString();
    }
    
    public configWgbReferenceCtrl(ApexPages.StandardController controller){
        LowerStackPedestalMatlMap = new Map<String, String>();
        PedestalConnectionMap = new Map<String, String>();
        FlameSensorMap = new Map<String, String>();
        ThermocoupleMaterialMap = new Map<String, String>();
        EnclosureTypeMap = new Map<String, String>();
        ControlPanelAlarmMap = new Map<String, String>();
        ControlPanelHeaterMap = new Map<String, String>();
        StandControlMaterialMap = new Map<String, String>();
        SunshieldControlMap = new Map<String, String>();
        StepDownTransformerMap = new Map<String, String>();
        BackupPowerSupplyMap = new Map<String, String>();
	   //controller.addFields(new String[]{'Soft_Goods_Material_dynamic__c','Size__c','Connection_dynamic__c'});
       oWGB = (WasteGasBurner__c)controller.getRecord();    
        for(User u : [Select Id,Name From User Where Id =: userinfo.getUserId()]){
            oUser = u;
        }

        
        for(PicklistEntry entry : WasteGasBurner__c.Lower_Stack_Pedestal_Matl__c.getDescribe().getPicklistValues()){
            LowerStackPedestalMatlMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Pedestal_Connection__c.getDescribe().getPicklistValues()){
            PedestalConnectionMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Flame_Sensor__c.getDescribe().getPicklistValues()){
            FlameSensorMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Thermocouple_Material__c.getDescribe().getPicklistValues()){
            ThermocoupleMaterialMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Enclosure_Type__c.getDescribe().getPicklistValues()){
            EnclosureTypeMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Control_Panel_Alarm__c.getDescribe().getPicklistValues()){
            ControlPanelAlarmMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Control_Panel_Heater__c.getDescribe().getPicklistValues()){
            ControlPanelHeaterMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Stand_Control_Material__c.getDescribe().getPicklistValues()){
            StandControlMaterialMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Sunshield_Control__c.getDescribe().getPicklistValues()){
            SunshieldControlMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Step_Down_Transformer__c.getDescribe().getPicklistValues()){
            StepDownTransformerMap.put(entry.getValue(), entry.getLabel());
        }

        for(PicklistEntry entry : WasteGasBurner__c.Back_up_Power_Supply__c.getDescribe().getPicklistValues()){
            BackupPowerSupplyMap.put(entry.getValue(), entry.getLabel());
        }

        

        
        

        
        
        

    }
}