force-app/main/default/objects/RD_Drawings__c/RD_Drawings__c.object-meta.xml
<CustomObject>
    <label>RD Drawings</label>
    <nameField>
        <label>RD Drawings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RD Drawings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RD_Drawings__c/fields/Drawing_ID__c.field-meta.xml
<CustomField>
    <fullName>Drawing_ID__c</fullName>
    <label>Drawing ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RD_Drawings__c/fields/Rupture_Disc__c.field-meta.xml
<CustomField>
    <fullName>Rupture_Disc__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rupture Disc</label>
    <referenceTo>Rupture_Disc__c</referenceTo>
    <relationshipLabel>RD Drawings</relationshipLabel>
    <relationshipName>RD_Drawings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/RD_Outputs__c.object-meta.xml
<CustomObject>
    <label>RD Outputs</label>
    <nameField>
        <label>RD Outputs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RD Outputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RD_Outputs__c/fields/LABDSC__c.field-meta.xml
<CustomField>
    <fullName>LABDSC__c</fullName>
    <label>LABDSC</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OA__c.field-meta.xml
<CustomField>
    <fullName>OA__c</fullName>
    <label>OA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OA_Override__c.field-meta.xml
<CustomField>
    <fullName>OA_Override__c</fullName>
    <label>OA Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OB__c.field-meta.xml
<CustomField>
    <fullName>OB__c</fullName>
    <label>OB</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OB_Override__c.field-meta.xml
<CustomField>
    <fullName>OB_Override__c</fullName>
    <label>OB Override</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORP__c.field-meta.xml
<CustomField>
    <fullName>ORP__c</fullName>
    <label>ORP</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORP_Override__c.field-meta.xml
<CustomField>
    <fullName>ORP_Override__c</fullName>
    <label>ORP Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORV__c.field-meta.xml
<CustomField>
    <fullName>ORV__c</fullName>
    <label>ORV</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORV_Override__c.field-meta.xml
<CustomField>
    <fullName>ORV_Override__c</fullName>
    <label>ORV Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OW__c.field-meta.xml
<CustomField>
    <fullName>OW__c</fullName>
    <label>OW</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OW_Override__c.field-meta.xml
<CustomField>
    <fullName>OW_Override__c</fullName>
    <label>OW Override</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/Rupture_Disc__c.object-meta.xml
<CustomObject>
    <label>Rupture Disc</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rupture Disc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rupture Discs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rupture_Disc__c/fields/Lead_Time_Override__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Lead Time Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/fields/Product_Narrowing_Flag__c.field-meta.xml
<CustomField>
    <fullName>Product_Narrowing_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Product Narrowing Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/fields/Quote_Descriptions_Override__c.field-meta.xml
<CustomField>
    <fullName>Quote_Descriptions_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Descriptions Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Rupture Discs</relationshipLabel>
    <relationshipName>Rupture_Discs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimB__c.field-meta.xml
<CustomField>
    <fullName>DimB__c</fullName>
    <label>DimB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimC__c.field-meta.xml
<CustomField>
    <fullName>DimC__c</fullName>
    <label>DimC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimF__c.field-meta.xml
<CustomField>
    <fullName>DimF__c</fullName>
    <label>DimF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Drawing_to_be_created_outside_of_Config__c.field-meta.xml
<CustomField>
    <fullName>Drawing_to_be_created_outside_of_Config__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Drawing to be created outside of Config</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DrawingID__c.field-meta.xml
<CustomField>
    <fullName>DrawingID__c</fullName>
    <description>This field will have the name of static resource</description>
    <label>DrawingID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Lead_Time_Override__c.field-meta.xml
<CustomField>
    <fullName>Lead_Time_Override__c</fullName>
    <label>Intl. Lead Time Adder Override</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ConfigRDUtilityBatch.cls
public class ConfigRDUtilityBatch {

    public static Map<String, Object> updateRDRecords(Rupture_Disc__c rdRecord) {
		system.debug('RD Update...');
        String errorDetails = '';
        String quoteDesc;
        Result resData = new Result();
        SBQQ__QuoteLine__c quoteLine;

        ConfigureRD conObj = new ConfigureRD(rdRecord.Quote_Line__c);
    
        //update diagrams
        Result diagramRes = conObj.loadDiagramData();
        
        //update sizing
        RuptureDiscController.ReorderFlagLWC = true;
        Rupture_Disc__c rdDetails  = conObj.conProd;
        if(rdDetails.Product_Narrowing_Flag__c) {
            RuptureDiscController.saveSizingFlowArea(rdDetails);
        }
        RuptureDiscController.saveProductSelection(rdDetails, rdDetails.Id, null);
        RuptureDiscController.saveHClass(rdDetails);

        //update pricing
        WizardPricingProcessor wzdPrz = new WizardPricingProcessor(rdDetails.id);
        Result resPric = wzdPrz.getRDAdderPriceValues();
        
        //update lead time  
        system.debug('RD Update...'+rdDetails.Lead_Time_Override__c);
        RdOutputBaseUtility RDOU = new RdOutputBaseUtility(rdDetails.id);
        List<RdOutputBaseUtility.RDStructureWrapper> structureDetails = RDOU.getConsolidatedStructureDetails();
        if(!rdDetails.Lead_Time_Override__c) {
            
            system.debug('RD Update...Invoke LeadTime:'+rdDetails.Id);
            RDOU.getRDLeadTime();
        }

        //fetch and update descriptions
        String resStrOA = '';
        String strOA = '';
        String strLABDSC = '';
        String strOB = '';
        String strOBOverRide = '';
        String strOW = '';
        
        Result resOA = conObj.RDOU.getOA();
        if (resOA.bResult) {
            for (sObject sOb:resOA.objResultList) {
                if ((String) sOb.get('OA__c')!=null){
                    strOA = (String) sOb.get('OA__c');
                    strOA = strOA.replace('\\n','\n');
                    strOA+= '\n';
                }

                if ((String) sOb.get('LABDSC__c')!=null)
                    strLABDSC+= (String) sOb.get('LABDSC__c')+'\n';
            }
        }

        Map<String, String> OBMAP = conObj.RDOU.getOB_LABMAT_Ouput();
        
        if(OBMAP.get('OB').length()>251) {
            strOB = OBMAP.get('OB').substring(0, 250);
            if(!rdRecord.Quote_Descriptions_Override__c)
                strOBOverRide=OBMAP.get('OB').substring(0, 250);
        } else {
            strOB=OBMAP.get('OB');
            if(!rdRecord.Quote_Descriptions_Override__c)
                strOBOverRide=OBMAP.get('OB');
        }

        Result resOW = conObj.RDOU.getOW();
        if (resOW.bResult) {
            strOW = resOW.strRetValue;
            strOW = strOW.replace('\\n','\n');
        }
        
        RD_Outputs__c outputs = conObj.rdOutput;
        List<RD_Outputs__c> rdOutputs = [SELECT Id, ORV__c, ORP__c, ORP_Override__c, ORV_Override__c, OA__c, OB__c, OW__c, OA_Override__c, OB_Override__c, OW_Override__c FROM RD_Outputs__c WHERE Id = :outputs.Id];
        outputs = rdOutputs[0];
        outputs.OA__c = strOA;
        outputs.OB__c = strOB;
        outputs.OW__c = strOW;
        Rupture_Disc__c recDetail = rdRecord;

        try {
            if(!recDetail.Quote_Descriptions_Override__c){
                outputs.OA_Override__c = strOA;
                outputs.OB_Override__c = strOB;
                outputs.OW_Override__c = strOW;
            }
            
            update outputs;
            //update recDetail;

            if(recDetail.Quote_Descriptions_Override__c) {
                quoteDesc = '';
                if(outputs.OA_Override__c != null) {
                	
                    quoteDesc = outputs.OA_Override__c;
                }
                if(outputs.OB_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.OB_Override__c;
                }
                
                if(outputs.ORP_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.ORP_Override__c;
                }
                
                if(outputs.ORV_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.ORV_Override__c;
                }
                
                if(outputs.OW_Override__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.OW_Override__c;
                }
                                
            } else {
                
                quoteDesc = '';
                if(outputs.OA__c != null) {
                	
                    quoteDesc = strOA;
                }
                if(outputs.OB__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += strOB;
                }
                if(outputs.ORP__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.ORP__c;
                }
                if(outputs.ORV__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += outputs.ORV__c;
                }
                
                if(outputs.OW__c != null) {
                    if(quoteDesc != '') {
                        
                       quoteDesc += '\n'; 
                    }
                    quoteDesc += strOW;
                }
            }

            quoteDesc = quoteDesc.replace('\\n', '\n');
            quoteDesc = quoteDesc.replace('\n', '<br/>');
            quoteLine = new SBQQ__QuoteLine__c();
            quoteLine.Id = recDetail.Quote_Line__c;
            quoteLine.SBQQ__Description__c = quoteDesc;
            
            //assign diagram dtails to QL
            
            if(diagramRes != null && diagramRes.bResult) {
                
                List<RD_Drawings__c> rdDiagrams = (List<RD_Drawings__c>) diagramRes.objResultList;
                List<RD_Drawings__c> rdDiagramDetails = [SELECT Drawing_Number__c, Rupture_Disc__r.Quote_Line__r.Drawing_to_be_created_outside_of_Config__c, Drawing_ID__c, Dim_A__c, Dim_B__c, Dim_C__c, Dim_D__c, Dim_E__c, Dim_F__c FROM RD_Drawings__c WHERE Id IN :rdDiagrams];
                for(RD_Drawings__c rdDiagram: rdDiagramDetails) {
                    
                    if(rdDiagram.Drawing_Number__c != null) {
                        
                        if(rdDiagram.Rupture_Disc__r.Quote_Line__r.Drawing_to_be_created_outside_of_Config__c == false) {
                            
                            quoteLine.DrawingID__c = rdDiagram.Drawing_ID__c;
                            quoteLine.DimA__c  = rdDiagram.Dim_A__c;
                            quoteLine.DimB__c  = rdDiagram.Dim_B__c;
                            quoteLine.DimC__c  = rdDiagram.Dim_C__c;
                            quoteLine.DimD__c  = rdDiagram.Dim_D__c;
                            quoteLine.DimE__c  = rdDiagram.Dim_E__c;
                            quoteLine.DimF__c  = rdDiagram.Dim_F__c;
                        }
                    }
                }
            }
            
        } catch (Exception e) {       
            
            errorDetails = 'Error:'+ recDetail.Quote_Line__c +' - '+e.getMessage();
        }

        Map<String, Object> response = new Map<String, Object>();
        response.put('QUOTE_LINE', quoteLine);
        response.put('ERROR_DETAILS', errorDetails);

        return response;
    }
}