force-app/main/default/objects/QuoteLine_Mass_Update__c/QuoteLine_Mass_Update__c.object-meta.xml
<CustomObject>
    <label>QuoteLine Mass Update</label>
    <nameField>
        <displayFormat>MU-{00000}</displayFormat>
        <label>QuoteLine Mass Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteLine Mass Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Trigger_QL_Update__c.field-meta.xml
<CustomField>
    <fullName>Trigger_QL_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Trigger QL Update</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/Regeneration_Request_Details__c.object-meta.xml
<CustomObject>
    <label>Regeneration Request Details</label>
    <nameField>
        <displayFormat>RRD-{00000}</displayFormat>
        <label>Regeneration Request Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regeneration Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Parent_Job__c.field-meta.xml
<CustomField>
    <fullName>Parent_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Job</label>
    <referenceTo>Regeneration_Request_Details__c</referenceTo>
    <relationshipLabel>Regeneration Request Details</relationshipLabel>
    <relationshipName>Parent_Job_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Status_for_Ordering__c.field-meta.xml
<CustomField>
    <fullName>Status_for_Ordering__c</fullName>
    <formula>CASE(Status__c,
                      &quot;Pending&quot;, 0,
                      &quot;Failed&quot;, 1,
                      &quot;Completed&quot;, 2,
                      0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status for Ordering</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RegenerationRequestDetailsTriggerHandler.cls
public class RegenerationRequestDetailsTriggerHandler {
	
    public static void updateParentJobStatus(Set<Id> parentJobIds) {
        
        system.debug('parentJobIds:'+parentJobIds);
        List<Regeneration_Request_Details__c> regenerationList = new List<Regeneration_Request_Details__c>();
        Regeneration_Request_Details__c regenerationDet;
        Map<Id, String> jobStatus = new Map<Id, String>();
        for(Regeneration_Request_Details__c rec: [SELECT Id, Status__c, Parent_Job__c FROM Regeneration_Request_Details__c 
                                                  WHERE Parent_Job__c  IN :parentJobIds ORDER BY Status_for_Ordering__c DESC]) {
            
        	jobStatus.put(rec.Parent_Job__c, rec.Status__c);
        }
        
        for(String key: jobStatus.keySet()) {
            
            regenerationDet = new Regeneration_Request_Details__c();
            regenerationDet.Id = key;
            regenerationDet.Status__c = jobStatus.get(key);
            regenerationList.add(regenerationDet);
        }
        
        if(regenerationList.size() > 0) {
        	
            system.debug('regenerationList:'+regenerationList);
            update regenerationList;
            
            /*
            List<QuoteLine_Mass_Update__c> qlMassUpdates = [SELECT Id, Trigger_QL_Update__c FROM QuoteLine_Mass_Update__c];
            
            if(qlMassUpdates.size() > 0) {
                
                for(QuoteLine_Mass_Update__c qlMassUpdate: qlMassUpdates) {
                    
                    qlMassUpdate.Trigger_QL_Update__c = true;
                }
                update qlMassUpdates;
            }
*/
            System.enqueueJob(new MassConfiguratorFutureEvnts());
            //ConfigHolderUtilityBatch.updateQLines();
        }
    }
}