force-app/main/default/objects/QuoteLine_Mass_Update__c/QuoteLine_Mass_Update__c.object-meta.xml
<CustomObject>
    <label>QuoteLine Mass Update</label>
    <nameField>
        <displayFormat>MU-{00000}</displayFormat>
        <label>QuoteLine Mass Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteLine Mass Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Batch_Job_Details__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Details__c</fullName>
    <label>Batch Job Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Delete_Record__c.field-meta.xml
<CustomField>
    <fullName>Delete_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Record?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/RD_Outputs__c.object-meta.xml
<CustomObject>
    <label>RD Outputs</label>
    <nameField>
        <label>RD Outputs Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RD Outputs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RD_Outputs__c/fields/OA__c.field-meta.xml
<CustomField>
    <fullName>OA__c</fullName>
    <label>OA</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OA_Override__c.field-meta.xml
<CustomField>
    <fullName>OA_Override__c</fullName>
    <label>OA Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OB__c.field-meta.xml
<CustomField>
    <fullName>OB__c</fullName>
    <label>OB</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OB_Override__c.field-meta.xml
<CustomField>
    <fullName>OB_Override__c</fullName>
    <label>OB Override</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORP__c.field-meta.xml
<CustomField>
    <fullName>ORP__c</fullName>
    <label>ORP</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORP_Override__c.field-meta.xml
<CustomField>
    <fullName>ORP_Override__c</fullName>
    <label>ORP Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORV__c.field-meta.xml
<CustomField>
    <fullName>ORV__c</fullName>
    <label>ORV</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/ORV_Override__c.field-meta.xml
<CustomField>
    <fullName>ORV_Override__c</fullName>
    <label>ORV Override</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OW__c.field-meta.xml
<CustomField>
    <fullName>OW__c</fullName>
    <label>OW</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RD_Outputs__c/fields/OW_Override__c.field-meta.xml
<CustomField>
    <fullName>OW_Override__c</fullName>
    <label>OW Override</label>
    <length>1500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/Regeneration_Request_Details__c.object-meta.xml
<CustomObject>
    <label>Regeneration Request Details</label>
    <nameField>
        <displayFormat>RRD-{00000}</displayFormat>
        <label>Regeneration Request Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regeneration Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Batch_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_ID__c</fullName>
    <label>Batch Job ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Quote_No__c.field-meta.xml
<CustomField>
    <fullName>Quote_No__c</fullName>
    <label>Quote No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Regeneration_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rupture_Disc__c/Rupture_Disc__c.object-meta.xml
<CustomObject>
    <label>Rupture Disc</label>
    <nameField>
        <displayFormat>RD-{0000000}</displayFormat>
        <label>Rupture Disc Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rupture Discs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rupture_Disc__c/fields/Quote_Descriptions_Override__c.field-meta.xml
<CustomField>
    <fullName>Quote_Descriptions_Override__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Quote Descriptions Override</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Pending Approvals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <description>Coincides with the Pending/In Review SBQQ Status</description>
    <label>Pending</label>
</RecordType>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <defaultValue>&quot;Primary&quot;</defaultValue>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>SBQQ__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegenerationRDTest.cls
@isTest
public class RegenerationRDTest {
	
    @testSetup
    public static void dataSetup() {
                
        Map<String, String> mapWithRDValues = new Map<String, String>();
        mapWithRDValues.put('BRAND','CDC');
        mapWithRDValues.put('PRODUCT_CODE','RD');
        mapWithRDValues.put('PRODUCT_NAME','Rupture Disc');
        
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithRDValues);
        TestDataRDUtility.quoteLine = quoteLine;        

        TestDataRDUtility.mapWithRDValues = mapWithRDValues;
        TestDataRDUtility.createRDMasterTestRecords();
        
        //TestDataRDUtility.createRDTestRecords1();
        TestDataRDUtility.createRDTestRecordWithOutput();
        
        TestDataHolderUtility.quoteLine = quoteLine;
        quoteLine.Line_Status__c = 'Primary';
        update quoteLine;
        
        SBQQ__Quote__c quote  = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id = :quoteLine.SBQQ__Quote__c];
        quote.SBQQ__Status__c = 'Pending';
        update quote;
    }
    
    @isTest
    public static void testRDRegeneration() {
        
        Test.startTest();
        SBQQ__QuoteLine__c quoteLine  = [SELECT Id, SBQQ__Quote__c, Line_Status__c FROM SBQQ__QuoteLine__c LIMIT 1];
        
        List<Rupture_Disc__c> rdDets  = [SELECT Id, Finish_Configuration_Flag__c, Quote_Descriptions_Override__c FROM Rupture_Disc__c LIMIT 1];
        system.debug('rdDet:'+rdDets);
        Rupture_Disc__c rdDet = rdDets[0];
        
        rdDet.Finish_Configuration_Flag__c = true;
        update rdDet;
        
        MassConfiguratorUpdateInitiation obj = new MassConfiguratorUpdateInitiation('RD', quoteLine.SBQQ__Quote__c);
        Id batchJobId = Database.executeBatch(obj); 
        
        Regeneration_Request_Details__c rrd = new Regeneration_Request_Details__c();
        rrd.Product_Name__c  = 'Rupture Disc';
        rrd.Product_Code__c = 'RD';
        rrd.Batch_Job_ID__c = batchJobId;
        rrd.Quote_No__c = null;
        rrd.Requested_By__c = UserInfo.getUserId();
        rrd.Status__c  = 'Pending';
        upsert rrd;
        
        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        quoteLines.add(quoteLine);
        System.enqueueJob(new MassConfiguratorFutureEvnts(quoteLines));
                
        QuoteLine_Mass_Update__c rec = new QuoteLine_Mass_Update__c();
        rec.Delete_Record__c = true;
        rec.Batch_Job_ID__c = 'Test1';
        rec.Batch_Job_Details__c = 'Test';
        insert rec;
        
        Regeneration_Request_Details__c rec1 = new Regeneration_Request_Details__c();
        rec1.Batch_Job_ID__c = 'Test1';
        insert rec1;
        
        QLMassUpdate.deleteMassQLRecords(null);
        
        List<SBQQ__QuoteLine__c> quoteLines2 = [SELECT Id FROM SBQQ__QuoteLine__c ORDER BY Id DESC LIMIT 1];
		ConfigHolderUtilityBatch.updateQuoteLineDesc(JSON.serialize(quoteLines2));
        
        Test.stopTest();
    }
    
    @isTest
    public static void testRDRegeneration2() {
        
        Test.startTest();
        SBQQ__QuoteLine__c quoteLine  = [SELECT Id, SBQQ__Quote__c, Line_Status__c FROM SBQQ__QuoteLine__c LIMIT 1];
        
        List<Rupture_Disc__c> rdDets  = [SELECT Id, Finish_Configuration_Flag__c, Quote_Descriptions_Override__c FROM Rupture_Disc__c LIMIT 1];
        system.debug('rdDet:'+rdDets);
        Rupture_Disc__c rdDet = rdDets[0];
        
        rdDet.Quote_Descriptions_Override__c = true;
        rdDet.Finish_Configuration_Flag__c = true;
        update rdDet;
        
        List<RD_Outputs__c> rdOutputs = [SELECT Id, ORV__c, ORP__c, ORP_Override__c, ORV_Override__c, OA__c, OB__c, OW__c, OA_Override__c, OB_Override__c, OW_Override__c FROM RD_Outputs__c LIMIT 1];
		RD_Outputs__c outputs = rdOutputs[0];
        outputs.OA_Override__c = 'Test';
        outputs.OB_Override__c = 'Test';
        outputs.ORP_Override__c = 'Test';
        outputs.ORV_Override__c = 'Test';
        outputs.OW_Override__c = 'Test';
        
		outputs.OA__c = 'Test';
        outputs.OB__c = 'Test';
        outputs.ORP__c = 'Test';
        outputs.ORV__c = 'Test';
        outputs.OW__c = 'Test';        
        update outputs;
        
        MassConfiguratorUpdateInitiation obj = new MassConfiguratorUpdateInitiation('RD', quoteLine.SBQQ__Quote__c);
        Id batchJobId = Database.executeBatch(obj); 
        
        Regeneration_Request_Details__c rrd = new Regeneration_Request_Details__c();
        rrd.Product_Name__c  = 'Rupture Disc';
        rrd.Product_Code__c = 'RD';
        rrd.Batch_Job_ID__c = batchJobId;
        rrd.Quote_No__c = null;
        rrd.Requested_By__c = UserInfo.getUserId();
        rrd.Status__c  = 'Pending';
        upsert rrd;
        
        List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
        quoteLines.add(quoteLine);
        System.enqueueJob(new MassConfiguratorFutureEvnts(quoteLines));
                
        QuoteLine_Mass_Update__c rec = new QuoteLine_Mass_Update__c();
        rec.Delete_Record__c = true;
        rec.Batch_Job_ID__c = 'Test1';
        rec.Batch_Job_Details__c = 'Test';
        insert rec;
        
        Regeneration_Request_Details__c rec1 = new Regeneration_Request_Details__c();
        rec1.Batch_Job_ID__c = 'Test1';
        insert rec1;
        
        QLMassUpdate.deleteMassQLRecords(null);
        
        List<SBQQ__QuoteLine__c> quoteLines2 = [SELECT Id FROM SBQQ__QuoteLine__c ORDER BY Id DESC LIMIT 1];
		ConfigHolderUtilityBatch.updateQuoteLineDesc(JSON.serialize(quoteLines2));
        
        Test.stopTest();
    }
}