force-app/main/default/objects/QuoteLine_Mass_Update__c/QuoteLine_Mass_Update__c.object-meta.xml
<CustomObject>
    <label>QuoteLine Mass Update</label>
    <nameField>
        <displayFormat>MU-{00000}</displayFormat>
        <label>QuoteLine Mass Update Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QuoteLine Mass Update</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Batch_Job_Details__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_Details__c</fullName>
    <label>Batch Job Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Batch_Status__c.field-meta.xml
<CustomField>
    <fullName>Batch_Status__c</fullName>
    <label>Batch Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Delete_Record__c.field-meta.xml
<CustomField>
    <fullName>Delete_Record__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Delete Record?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimB__c.field-meta.xml
<CustomField>
    <fullName>DimB__c</fullName>
    <label>DimB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimC__c.field-meta.xml
<CustomField>
    <fullName>DimC__c</fullName>
    <label>DimC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/DimF__c.field-meta.xml
<CustomField>
    <fullName>DimF__c</fullName>
    <label>DimF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Drawing_ID__c.field-meta.xml
<CustomField>
    <fullName>Drawing_ID__c</fullName>
    <label>Drawing ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>QuoteLine Mass Update</relationshipLabel>
    <relationshipName>QuoteLine_Mass_Update</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteLine_Mass_Update__c/fields/QuoteLine_Description__c.field-meta.xml
<CustomField>
    <fullName>QuoteLine_Description__c</fullName>
    <label>QuoteLine Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/Regeneration_Request_Details__c.object-meta.xml
<CustomObject>
    <label>Regeneration Request Details</label>
    <nameField>
        <displayFormat>RRD-{00000}</displayFormat>
        <label>Regeneration Request Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regeneration Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Batch_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_ID__c</fullName>
    <label>Batch Job ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Job_Details__c.field-meta.xml
<CustomField>
    <fullName>Job_Details__c</fullName>
    <label>Job Details</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimA__c.field-meta.xml
<CustomField>
    <fullName>DimA__c</fullName>
    <label>DimA</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimB__c.field-meta.xml
<CustomField>
    <fullName>DimB__c</fullName>
    <label>DimB</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimC__c.field-meta.xml
<CustomField>
    <fullName>DimC__c</fullName>
    <label>DimC</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimD__c.field-meta.xml
<CustomField>
    <fullName>DimD__c</fullName>
    <label>DimD</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimE__c.field-meta.xml
<CustomField>
    <fullName>DimE__c</fullName>
    <label>DimE</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DimF__c.field-meta.xml
<CustomField>
    <fullName>DimF__c</fullName>
    <label>DimF</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/DrawingID__c.field-meta.xml
<CustomField>
    <fullName>DrawingID__c</fullName>
    <description>This field will have the name of static resource</description>
    <label>DrawingID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QLMassUpdate.cls
public class QLMassUpdate {
    
    @InvocableMethod(label='Delete QL Mass Update Records' description='Delete QL Mass Update Records' category='QuoteLine_Mass_Update__c')
    public static void deleteMassQLRecords(List<Id> ids) {
        
        /*
List<QuoteLine_Mass_Update__c> records = [SELECT Id, Quote_Line__c, QuoteLine_Description__c, Drawing_ID__c, DimA__c, DimB__c, DimC__c, DimD__c, DimE__c, DimF__c FROM QuoteLine_Mass_Update__c WHERE Id IN :ids ORDER BY Id DESC];
List<SBQQ__QuoteLine__c> quoteLines = new List<SBQQ__QuoteLine__c>();
SBQQ__QuoteLine__c quoteLine;
for (QuoteLine_Mass_Update__c quoteLinesMassRecord: records) {

quoteLine = new SBQQ__QuoteLine__c();
quoteLine.Id  = quoteLinesMassRecord.Quote_Line__c;
quoteLine.DrawingID__c = quoteLinesMassRecord.Drawing_ID__c;
quoteLine.DimA__c = quoteLinesMassRecord.DimA__c;
quoteLine.DimB__c = quoteLinesMassRecord.DimB__c;
quoteLine.DimC__c = quoteLinesMassRecord.DimC__c;
quoteLine.DimD__c = quoteLinesMassRecord.DimD__c;
quoteLine.DimE__c = quoteLinesMassRecord.DimE__c;
quoteLine.DimF__c = quoteLinesMassRecord.DimF__c;
quoteLine.SBQQ__Description__c = quoteLinesMassRecord.QuoteLine_Description__c ;

quoteLines.add(quoteLine);
}
update quoteLines;
delete records;        
//ConfigHolderUtilityBatch.updateQLines();
*/
        
        List<QuoteLine_Mass_Update__c> deleteRecords = [SELECT Id, CreatedBy.Email, Batch_Job_Details__c, Batch_Status__c, Batch_Job_ID__c FROM QuoteLine_Mass_Update__c WHERE Delete_Record__c = true];
        
        if(deleteRecords.size() > 0) {
            
            // Send an email to the submitter notifying of job completion.
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            String[] toAddresses = new String[] {deleteRecords[0].CreatedBy.Email};
                mail.setToAddresses(toAddresses);
            mail.setSubject('ReGeneration Status ' + deleteRecords[0].Batch_Status__c);
            mail.setPlainTextBody(deleteRecords[0].Batch_Job_Details__c);
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
            
            //update batch job 
            List<Regeneration_Request_Details__c> regenerationReqDetails = [SELECT Id, Job_Details__c, Status__c FROM Regeneration_Request_Details__c WHERE Batch_Job_ID__c = :deleteRecords[0].Batch_Job_ID__c];
            if(regenerationReqDetails.size() > 0) {
                
                regenerationReqDetails[0].Status__c = deleteRecords[0].Batch_Status__c;
                update regenerationReqDetails;
            }
            
            if(deleteRecords.size() > 0) { 
                
                delete deleteRecords;
            }
        }
    }
}