force-app/main/default/objects/Regeneration_Request_Details__c/Regeneration_Request_Details__c.object-meta.xml
<CustomObject>
    <label>Regeneration Request Details</label>
    <nameField>
        <displayFormat>RRD-{00000}</displayFormat>
        <label>Regeneration Request Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regeneration Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Batch_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_ID__c</fullName>
    <label>Batch Job ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Pending Approvals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <description>Coincides with the Pending/In Review SBQQ Status</description>
    <label>Pending</label>
</RecordType>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <defaultValue>&quot;Primary&quot;</defaultValue>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RegenerationRequestControllerTest.cls
@isTest
public class RegenerationRequestControllerTest {
    
    @testSetup
    public static void dataSetup() {
        
        Map<String, String> mapWithHolderValues = new Map<String, String>();
        mapWithHolderValues.put('BOLTING_CLASS', 'A3');
        mapWithHolderValues.put('BRAND','CDC');
        mapWithHolderValues.put('PRODUCT_CODE','HLD');
        mapWithHolderValues.put('PRODUCT_NAME','Holder');
        mapWithHolderValues.put('HOLDER_PRODUCT','7I Insert (LL) Double Disc Holder');
        mapWithHolderValues.put('INLET_MATERIAL','002');
        mapWithHolderValues.put('OUTLET_MATERIAL','002');
        mapWithHolderValues.put('SIZE','1/2" (13mm)');
        mapWithHolderValues.put('SIZE_UNITS', 'US Units');
                
        SBQQ__QuoteLine__c quoteLine = TestDataBaseUtility.createQLAndAssociatedRecords(mapWithHolderValues);
        
        TestDataHolderUtility.quoteLine = quoteLine;
        TestDataHolderUtility.mapWithHolderValues = mapWithHolderValues;
        
        SBQQ__Quote__c quote  = [SELECT Id, SBQQ__Status__c FROM SBQQ__Quote__c WHERE Id = :quoteLine.SBQQ__Quote__c];
        
        system.debug('TestDataHolderUtility.quoteLine:'+TestDataHolderUtility.quoteLine);
        system.debug('TestDataHolderUtility.mapWithHolderValues:'+TestDataHolderUtility.mapWithHolderValues);
        TestDataHolderUtility.createHoldersTestRecords();
        TestDataHolderUtility.createHoldersMasterTestRecords();
        
        quoteLine.Line_Status__c = 'Primary';
        update quoteLine;
        
        
        quote.SBQQ__Status__c = 'Pending';
        update quote;
    }
    
    @isTest
    public static void genericCoverage() {

        Test.startTest();   
        
        SBQQ__Quote__c quote  = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
        
        Map<String, String> prodMap = RegenerationRequestController.productsMap();
        
        RegenerationRequestController.checkRegenerationRequest();
        
        RegenerationRequestController.submitRegenerationRequest('Holders', quote.Name);
        
        
        Test.stopTest();
    }
    
    @isTest
    public static void genericCoverage2() {

        Test.startTest();   
        
        SBQQ__Quote__c quote  = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
        
        Regeneration_Request_Details__c rec1 = new Regeneration_Request_Details__c();
        rec1.Batch_Job_ID__c = 'Test1';
        insert rec1;
                        
        RegenerationRequestController.submitRegenerationRequest('Waste Gas Burner', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Blanket Gas Regulator', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Relief Valve', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Flame Products', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Part Selector', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Rupture Disc', quote.Name);
        
        Test.stopTest();
    }
    
    @isTest
    public static void genericCoverage3() {

        Test.startTest();   
        
        SBQQ__QuoteLine__c quoteLine  = [SELECT Id, Line_Status__c FROM SBQQ__QuoteLine__c LIMIT 1];
        SBQQ__Quote__c quote  = [SELECT Id, Name FROM SBQQ__Quote__c LIMIT 1];
        
        quoteLine.Line_Status__c = '';
        update quoteLine;
        
        
        quote.SBQQ__Status__c = '';
        update quote;
        
        Regeneration_Request_Details__c rec1 = new Regeneration_Request_Details__c();
        rec1.Batch_Job_ID__c = 'Test1';
        insert rec1;
                        
        RegenerationRequestController.submitRegenerationRequest('Waste Gas Burner', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Blanket Gas Regulator', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Relief Valve', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Flame Products', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Part Selector', quote.Name);
        RegenerationRequestController.submitRegenerationRequest('Rupture Disc', quote.Name);
        
        Test.stopTest();
    }
    
}