force-app/main/default/objects/Regeneration_Request_Details__c/Regeneration_Request_Details__c.object-meta.xml
<CustomObject>
    <label>Regeneration Request Details</label>
    <nameField>
        <displayFormat>RRD-{00000}</displayFormat>
        <label>Regeneration Request Details ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Regeneration Request Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Batch_Job_ID__c.field-meta.xml
<CustomField>
    <fullName>Batch_Job_ID__c</fullName>
    <label>Batch Job ID</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Parent_Job__c.field-meta.xml
<CustomField>
    <fullName>Parent_Job__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Job</label>
    <referenceTo>Regeneration_Request_Details__c</referenceTo>
    <relationshipLabel>Regeneration Request Details</relationshipLabel>
    <relationshipName>Parent_Job_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Quote_No__c.field-meta.xml
<CustomField>
    <fullName>Quote_No__c</fullName>
    <label>Quote No</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Regeneration_Request_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Regeneration_Request_Details__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__Quote__c/fields/SBQQ__Status__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Status__c</fullName>
    <description>Status indicating where quote is in its lifecycle.</description>
    <inlineHelpText>Status indicating where quote is in its lifecycle.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Pending Approvals</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Order Submitted</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
            <value>
                <fullName>Partner Submitted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__Quote__c/recordTypes/Pending.recordType-meta.xml
<RecordType>
    <fullName>Pending</fullName>
    <active>true</active>
    <description>Coincides with the Pending/In Review SBQQ Status</description>
    <label>Pending</label>
</RecordType>

force-app/main/default/objects/SBQQ__QuoteLine__c/SBQQ__QuoteLine__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteLineHelp</customHelpPage>
    <description>Individual line item on a quote.</description>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL-{0000000}</displayFormat>
        <label>Line Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Line_Status__c.field-meta.xml
<CustomField>
    <fullName>Line_Status__c</fullName>
    <defaultValue>&quot;Primary&quot;</defaultValue>
    <label>Line Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Primary</fullName>
                <default>true</default>
                <label>Primary</label>
            </value>
            <value>
                <fullName>Alternate</fullName>
            </value>
            <value>
                <fullName>Removed</fullName>
            </value>
            <value>
                <fullName>Cancel</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Unblock</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Opportunity_Stage__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stage__c</fullName>
    <formula>TEXT(SBQQ__Quote__r.SBQQ__Opportunity2__r.StageName)</formula>
    <label>Opportunity Stage</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <formula>SBQQ__Product__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs..</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MassConfiguratorUpdateInitiation.cls
/***************************************************************************************************************
* @Name         MassConfiguratorUpdateInitiation
* @Author       Ashim Kumar Sahoo <ashim.kumar@apexit.com>
* @Date         10/16/2020
* @Description  This class is a batch class which groups the quote lines (ID) based on the product (Map<String, Set<String>>)
*				Once the grouping is completed, it creates multiple batch jobs based on the unique product.
*****************************************************************************************************************/
public class MassConfiguratorUpdateInitiation implements Database.Batchable<sObject>, Database.Stateful {
    
    private HandlerInterface genUtil; 
    private String quoteId;
    private String productType;
    Map<String, Set<String>> prodCodesAndQLDet = new Map<String, Set<String>>();
    
    /*******************************************************************************************************
    * @Description  This method is a constructor which either set the quote ID or the product type
    * @Param 1		String - productType (mandatory)
    * @Param 2		Id - quoteId (optional)
    * @Return       N/A
    * @Example     
    * MassConfiguratorUpdateInitiation('PRODUCT_TYPE', 'QUOTE_ID')
    *********************************************************************************************************/
    public MassConfiguratorUpdateInitiation(String productType, Id quoteId) {
        
        if(quoteId != null) {
            
            this.quoteId = quoteId;
        }
        
        if(productType != null) {
            
            this.productType = productType;
        }
    }
    
    /*******************************************************************************************************
    * @Description  This method fetched SBQQ__QuoteLine__c records based on the quote ID or Product Type 
    * @Param 1		Database.BatchableContext - ctx
    * @Return       Database.QueryLocator
    *********************************************************************************************************/
    public Database.QueryLocator start(Database.BatchableContext ctx){
        
        Database.QueryLocator ql;
        List<String> qStatuses = new List<String>();
        List<String> qlStatuses = new List<String>();
        List<String> oppStages = new List<String>();
        
        String oppStage = Label.ReGeneration_Opportunity_Stage_Condition;
        if(oppStage != null) {
            
            oppStages = oppStage.split(',');
        }
        
        String qlStatus = Label.ReGeneration_QuoteLine_Status_Condition;
        if(qlStatus != null) {
            
            qlStatuses = qlStatus.split(',');
        }
        
        String qStatus = Label.ReGeneration_Quote_Status_Condition;
        if(qStatus != null) {
            
            qStatuses = qStatus.split(',');
        }
        
        String sql = 'SELECT Id, SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c WHERE Id != null ';
        if(productType != null) {
            
            //sql += ' AND SBQQ__Product__r.Name = :productType ';
            sql += ' AND SBQQ__ProductCode__c = :productType ';
        }
        
        if(quoteId != null) {
            
            sql += ' AND SBQQ__Quote__c = :quoteId ';
        } 
        
        if(qStatuses.size() > 0) {
            
            sql += ' AND SBQQ__Quote__r.SBQQ__Status__c IN :qStatuses';
        }
        
        if(qlStatuses.size() > 0) {
            
            sql += ' AND Line_Status__c IN :qlStatuses';
        }
        
        if(oppStages.size() > 0) {
            
            sql += ' AND Opportunity_Stage__c IN :oppStages';
        }
        
        //String qlId = 'a1N8A00000G1HFnUAN';
        //sql = 'SELECT Id, SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c WHERE Id = :qlId';
        
        system.debug('oppStages:'+oppStages);
        system.debug('qlStatuses:'+qlStatuses);
        system.debug('qStatuses:'+qStatuses);
        system.debug('productType:'+productType);
        
        //String qlid = 'a1N8A00000GIl6KUAT';
        //sql = 'SELECT Id, SBQQ__ProductCode__c FROM SBQQ__QuoteLine__c WHERE Id = :qlid';
        
        system.debug('sql:'+sql);
        ql = Database.getQueryLocator(sql);
        return ql;
    }
    
    /*******************************************************************************************************
    * @Description  This method receives the SBQQ__QuoteLine__c records and process it
    * 				It groups the quote lines (ID) based on the product and creates a Map<String, Set<String>>
    * 				Set<String> contains the respective QuoteLine IDs
    * @Param 1		Database.BatchableContext - ctx
    * @Param 2		List<SBQQ__QuoteLine__c> - qlRecords
    * @Return       N/A
    *********************************************************************************************************/
    public void execute(Database.BatchableContext ctx, List<SBQQ__QuoteLine__c> qlRecords) {
        
        system.debug('prodCode Tot:'+qlRecords.size());
        Set<String> tmpValues;
        Map<String, String> prodCodeObjectMappingDetails = wizardBaseDataProcessor.mapProdwithObject;
        for(SBQQ__QuoteLine__c quoteLineDet: qlRecords) {
            
            if(prodCodesAndQLDet.get(quoteLineDet.SBQQ__ProductCode__c) != null) {
                
                tmpValues = prodCodesAndQLDet.get(quoteLineDet.SBQQ__ProductCode__c);
                
            } else {
                
                tmpValues = new Set<String>();
            }
            tmpValues.add(quoteLineDet.Id);
            prodCodesAndQLDet.put(quoteLineDet.SBQQ__ProductCode__c, tmpValues);
        }
    }
    
    /*******************************************************************************************************
* @Description  This method gets the QL details which is grouped by configurator, and creates multiple 
* 				batch jobs based on the unique product.
* @Param 1		Database.BatchableContext - ctx
* @Return       N/A
*********************************************************************************************************/
    public void finish(Database.BatchableContext ctx){
        
        Integer maxRecords = 10; //Label.Regeneration_Records_Chunk
        List<Regeneration_Request_Details__c> regenerationReqDetails;
        List<Regeneration_Request_Details__c> regenerationDetails = new List<Regeneration_Request_Details__c>();
        Regeneration_Request_Details__c rrd;
        String parentJobId = '';
        Id batchJobId;
        //Set<String> checkRecords;
        
        parentJobId = '';
        regenerationReqDetails = [SELECT Id FROM Regeneration_Request_Details__c WHERE Requested_By__c = :UserInfo.getUserId() ORDER BY Id DESC LIMIT 1];
        system.debug('regenerationReqDetails:'+regenerationReqDetails);
        if(regenerationReqDetails.size() > 0) {
            
            parentJobId = regenerationReqDetails[0].Id;
        }
        
        for(String prodCode: prodCodesAndQLDet.keySet()) {
            
            Set<String> checkRecords = prodCodesAndQLDet.get(prodCode);
            system.debug('TOT PRODS:'+ checkRecords.size());
            
            
            //Set<String> totalRecordChunksTmp = prodCodesAndQLDet.get(prodCode);
            //List<String> totalRecordChunks = new List<String>();
            //totalRecordChunks.addAll(totalRecordChunksTmp);
            //Set<String> recordChunks = new Set<String>();
            
            /*
Integer cntr = 0;
for(Integer i = 0; i < totalRecordChunks.size(); i++) {
cntr++;
if(cntr == maxRecords) {

if(recordChunks.size() > 0) {

MassConfiguratorUpdateProcess obj = new MassConfiguratorUpdateProcess(prodCode, recordChunks);
batchJobId = Database.executeBatch(obj, 10);  

rrd = new Regeneration_Request_Details__c();
if(parentJobId != null) {

rrd.Parent_Job__c = parentJobId;
}
rrd.Product_Name__c  	= productType;
rrd.Product_Code__c 	= prodCode;
rrd.Batch_Job_ID__c 	= batchJobId;
rrd.Quote_No__c 		= quoteId;
rrd.Requested_By__c 	= UserInfo.getUserId();
rrd.Status__c  			= 'Pending';
insert rrd;
//regenerationDetails.add(rrd);
}
recordChunks = new Set<String>();
cntr = 1;
}

recordChunks.add(totalRecordChunks[i]);
}
*/
            
            if(prodCodesAndQLDet.get(prodCode) != null) {
                
                MassConfiguratorUpdateProcess obj = new MassConfiguratorUpdateProcess(prodCode, prodCodesAndQLDet.get(prodCode), quoteId);
                if(prodCode == 'RD') {
                    
                    batchJobId = Database.executeBatch(obj, 1);
                    
                } else {
                	
                    batchJobId = Database.executeBatch(obj, 10);
                }
                
                rrd = new Regeneration_Request_Details__c();
                if(parentJobId != null) {
                    
                    rrd.Parent_Job__c = parentJobId;
                }
                rrd.Product_Name__c  	= productType;
                rrd.Product_Code__c 	= prodCode;
                rrd.Batch_Job_ID__c 	= batchJobId;
                rrd.Quote_No__c 		= quoteId;
                rrd.Requested_By__c 	= UserInfo.getUserId();
                rrd.Status__c  			= 'Pending';
                //regenerationDetails.add(rrd);
                insert rrd;
            }
            
            //List<SBQQ__QuoteLine__c> quoteLines = [SELECT Id FROM SBQQ__QuoteLine__c ORDER BY ID DESC LIMIT 10];
            //System.enqueueJob(new MassConfiguratorFutureEvnts(quoteLines));            
        }
    }
}